classdef AcquisitionPanel < handle
    %ACQUISITIONPANEL Owns panel controls and event bindings.
    % Receives only its parent, display values and explicit callbacks.
    properties
        AcquisitionLamp
        AcquisitionModeDropDown
        AcquisitionStartButton
        AcquisitionStateLabel
        AcquisitionStatusLabel
        AcquisitionStopButton
        AcquisitionStorageEstimateLabel
        CycleCountField
        CycleIntervalField
        LightStimLamp
        LightStimStatusLabel
        RecordDurationField
        RecordLengthSourceDropDown
        RecordLengthSummaryLabel
        RecordTiffCheckBox
        SafeExitButton
        TLIntervalField
        TLPointsField
        VisualStimLamp
        VisualStimStatusLabel
    end

    methods
        function view = AcquisitionPanel(parent, isRootGrid, callbacks)
            panel = uipanel(parent, 'Title', 'Acquisition');
            if isRootGrid
                panel.Layout.Row = 2;
                panel.Layout.Column = 3;
            end
            grid = uigridlayout(panel, [7 1]);
            grid.RowHeight = {30,32,28,30,38,24,26};
            grid.Padding = [5 4 5 4];
            grid.RowSpacing = 3;
            grid.Tag = 'AcquisitionPanelGrid';
            timingSettings = uigridlayout(grid, [1 10]);
            timingSettings.ColumnWidth = {45,55,112,65,70,65,90,65,45,55};
            timingSettings.ColumnSpacing = 6;
            timingSettings.Padding = [0 0 0 0];
            timingSettings.Tag = 'AcquisitionTimingGrid';
            uilabel(timingSettings, 'Text', 'Cycles');
            view.CycleCountField = uieditfield(timingSettings, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 1, ...
                'Tag', 'CycleCountField', ...
                'ValueChangedFcn', @(source,event) callbacks.acquisitionSettingEdited( ...
                    'Cycles', event.PreviousValue, source.Value));
            uilabel(timingSettings, 'Text', 'Start interval (s)');
            view.CycleIntervalField = uieditfield(timingSettings, 'numeric', ...
                'Limits', [0 Inf], 'Value', 45, 'Tag', 'CycleIntervalField', ...
                'ValueChangedFcn', @(source,event) callbacks.acquisitionSettingEdited( ...
                    'CycleStartIntervalSeconds', event.PreviousValue, source.Value));
            uilabel(timingSettings, 'Text', 'Record (s)');
            view.RecordDurationField = uieditfield(timingSettings, 'numeric', ...
                'Limits', [0.01 Inf], 'Value', 30, 'Tag', 'RecordDurationField', ...
                'ValueChangedFcn', @(source,event) callbacks.acquisitionSettingEdited( ...
                    'RecordDurationSeconds', event.PreviousValue, source.Value));
            uilabel(timingSettings, 'Text', 'TL interval (s)');
            view.TLIntervalField = uieditfield(timingSettings, 'numeric', ...
                'Limits', [0.05 Inf], 'Value', 5, ...
                'Tag', 'TLIntervalField', ...
                'ValueChangedFcn', @(source,event) callbacks.acquisitionSettingEdited( ...
                    'TLIntervalSeconds', event.PreviousValue, source.Value));
            uilabel(timingSettings, 'Text', 'Points');
            view.TLPointsField = uieditfield(timingSettings, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 10, ...
                'Tag', 'TLPointsField', ...
                'ValueChangedFcn', @(source,event) callbacks.acquisitionSettingEdited( ...
                    'TLPoints', event.PreviousValue, source.Value));

            modeSettings = uigridlayout(grid, [1 6]);
            modeSettings.ColumnWidth = {42,120,126,150,72,'1x'};
            modeSettings.ColumnSpacing = 6;
            modeSettings.Padding = [0 0 0 0];
            modeSettings.Tag = 'AcquisitionModeGrid';
            uilabel(modeSettings, 'Text', 'Mode');
            view.AcquisitionModeDropDown = uidropdown(modeSettings, ...
                'Items', {'Snap','Record','Time Lapse'}, ...
                'Value', 'Record', 'Tag', 'AcquisitionModeDropDown', ...
                'ValueChangedFcn', @(source,event) callbacks.acquisitionModeChanged( ...
                    event.PreviousValue, source.Value));
            uilabel(modeSettings, 'Text', 'Record length source');
            view.RecordLengthSourceDropDown = uidropdown(modeSettings, ...
                'Items', {'Custom','Light Stim DO'}, 'Value', 'Custom', ...
                'Tag', 'RecordLengthSourceDropDown', ...
                'Tooltip', ['Custom uses Record (s). Light Stim DO uses ', ...
                    'DO start offset plus the last time in the DO point table.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.recordLengthSourceChanged( ...
                    event.PreviousValue, source.Value));
            uilabel(modeSettings, 'Text', 'Resolved');
            view.RecordLengthSummaryLabel = uilabel(modeSettings, ...
                'Text', '30 s', 'Tag', 'RecordLengthSummaryLabel', ...
                'FontColor', [0.08 0.45 0.18]);

            view.RecordTiffCheckBox = uicheckbox(grid, ...
                'Text', 'Convert Record BIN to TIFF after all cycles', ...
                'Value', false, 'Tag', 'RecordTiffCheckBox', ...
                'Tooltip', ['Record always streams to BIN first. When checked, ', ...
                    'conversion starts only after every Record cycle is captured. ', ...
                    'Each cycle-camera unit is verified and its own BIN files are ', ...
                    'then deleted before the next unit is converted.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.acquisitionSettingEdited('ConvertRecordToTiff', ...
                    event.PreviousValue, source.Value));

            stimulusIndicators = uigridlayout(grid, [1 2]);
            stimulusIndicators.ColumnWidth = {'1x','1x'};
            stimulusIndicators.Padding = [0 0 0 0];
            visualState = uigridlayout(stimulusIndicators, [1 2]);
            visualState.ColumnWidth = {22,'1x'};
            visualState.Padding = [0 0 0 0];
            view.VisualStimLamp = uilamp(visualState, ...
                'Color', [0.65 0.65 0.65], 'Tag', 'VisualStimLamp');
            view.VisualStimStatusLabel = uilabel(visualState, ...
                'Text', 'Visual Stim OFF', 'FontWeight', 'bold', ...
                'Tag', 'VisualStimStatusLabel');
            lightState = uigridlayout(stimulusIndicators, [1 2]);
            lightState.ColumnWidth = {22,'1x'};
            lightState.Padding = [0 0 0 0];
            view.LightStimLamp = uilamp(lightState, ...
                'Color', [0.65 0.65 0.65], 'Tag', 'LightStimLamp');
            view.LightStimStatusLabel = uilabel(lightState, ...
                'Text', 'Light Stim OFF', 'FontWeight', 'bold', ...
                'Tag', 'LightStimStatusLabel');

            acquisitionButtons = uigridlayout(grid, [1 5]);
            acquisitionButtons.ColumnWidth = {22,'0.8x','1.25x','0.7x','0.9x'};
            acquisitionButtons.Padding = [0 0 0 0];
            view.AcquisitionLamp = uilamp(acquisitionButtons, ...
                'Color', [0.65 0.65 0.65], 'Tag', 'AcquisitionLamp');
            view.AcquisitionStateLabel = uilabel(acquisitionButtons, ...
                'Text', 'IDLE', 'FontWeight', 'bold', 'Tag', 'AcquisitionStateLabel');
            view.AcquisitionStartButton = uibutton(acquisitionButtons, 'push', ...
                'Text', 'Start Acquisition', 'Tag', 'AcquisitionStartButton', ...
                'FontWeight', 'bold', 'FontColor', [1 1 1], ...
                'BackgroundColor', [0.08 0.58 0.20], ...
                'ButtonPushedFcn', @(~,~) callbacks.startAcquisition());
            view.AcquisitionStopButton = uibutton(acquisitionButtons, 'push', ...
                'Text', 'Stop', 'Enable', 'off', 'Tag', 'AcquisitionStopButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.requestAcquisitionStop());
            view.SafeExitButton = uibutton(acquisitionButtons, 'push', ...
                'Text', 'Safe Exit', 'Tag', 'SafeExitButton', ...
                'FontWeight', 'bold', 'FontColor', [1 1 1], ...
                'BackgroundColor', [0.72 0.08 0.08], ...
                'Tooltip', ['Finish or safely stop acquisition, preserve data, ', ...
                    'turn outputs off, release all hardware, and close the view.'], ...
                'ButtonPushedFcn', @(~,~) callbacks.safeExitClicked());
            view.AcquisitionStatusLabel = uilabel(grid, ...
                'Text', 'Ready', 'Tag', 'AcquisitionStatusLabel');
            view.AcquisitionStorageEstimateLabel = uilabel(grid, ...
                'Text', 'Space: calculating...', ...
                'HorizontalAlignment', 'left', ...
                'FontWeight', 'bold', ...
                'Tag', 'AcquisitionStorageEstimateLabel');
        end
    end
end
