classdef AdvancedPanel < handle
    %ADVANCEDPANEL Owns panel controls and event bindings.
    % Receives only its parent, display values and explicit callbacks.
    properties
        AdvancedTimingSummaryLabel
        CameraPostStimField
        CameraPreStimField
        DaqSampleRateField
        DmdApplyParametersButton
        DmdBitDepthDropDown
        DmdDaqPortField
        DmdDataReverseCheckBox
        DmdDividedEdgeDropDown
        DmdHostAddressField
        DmdHostPortField
        DmdInputEdgeDropDown
        DmdInternalRateField
        DmdOutputEdgeDropDown
        DmdPictureCountActionDropDown
        DmdRepeatToFillTimelineCheckBox
        DmdRowAddressingCheckBox
        DmdTargetAddressField
        DmdTargetPortField
        DmdTrailingOffPaddingCheckBox
        DmdTriggerDivisionField
        DmdVerticalMirrorCheckBox
        LightLeadField
        LightStimDmdRateField
        LightTailField
        VisualAmplitudeField
        VisualBaselineColorField
        VisualBlackColorField
        VisualBlueColorField
        VisualFlipDeadlineField
        VisualIdleColorField
        VisualInitialPhaseField
        VisualScreenWidthField
        VisualSpatialFrequencyField
        VisualViewingDistanceField
        VisualWhiteColorField
    end

    methods
        function view = AdvancedPanel(parent, values, callbacks)
            grid = uigridlayout(parent, [6 1]);
            grid.RowHeight = {158,116,174,116,316,154};
            grid.Padding = [8 8 8 8];
            grid.RowSpacing = 8;
            if isprop(grid, 'Scrollable')
                grid.Scrollable = 'on';
            end

            timingPanel = uipanel(grid, 'Title', 'Independent offsets vs Camera START / END', ...
                'Tag', 'AdvancedStimulusPanel');
            timingGrid = uigridlayout(timingPanel, [3 4]);
            timingGrid.RowHeight = {30,30,52};
            timingGrid.ColumnWidth = {100,'1x',102,'1x'};
            timingGrid.Padding = [6 5 6 5];
            uilabel(timingGrid, 'Text', 'PTB start offset (s)');
            view.CameraPreStimField = uieditfield(timingGrid, 'numeric', ...
                'Limits', [-Inf Inf], 'Value', values.pre, ...
                'Tag', 'CameraPreStimField', ...
                'ValueChangedFcn', @(source,event) callbacks.advancedTimingEdited( ...
                    'CameraPreStimSeconds', event.PreviousValue, source.Value));
            uilabel(timingGrid, 'Text', 'PTB end padding (s)');
            view.CameraPostStimField = uieditfield(timingGrid, 'numeric', ...
                'Limits', [0 Inf], 'Value', values.post, ...
                'Tag', 'CameraPostStimField', ...
                'ValueChangedFcn', @(source,event) callbacks.advancedTimingEdited( ...
                    'CameraPostStimSeconds', event.PreviousValue, source.Value));
            uilabel(timingGrid, 'Text', 'Imaging TTL start offset (s)');
            view.LightLeadField = uieditfield(timingGrid, 'numeric', ...
                'Limits', [-Inf Inf], 'Value', values.lead, ...
                'Tag', 'LightLeadField', ...
                'ValueChangedFcn', @(source,event) callbacks.advancedTimingEdited( ...
                    'LightLeadSeconds', event.PreviousValue, source.Value));
            uilabel(timingGrid, 'Text', 'Imaging TTL end vs Camera END (s)');
            view.LightTailField = uieditfield(timingGrid, 'numeric', ...
                'Limits', [-Inf Inf], 'Value', values.tail, ...
                'Tag', 'LightTailField', ...
                'ValueChangedFcn', @(source,event) callbacks.advancedTimingEdited( ...
                    'LightTailSeconds', event.PreviousValue, source.Value));
            view.AdvancedTimingSummaryLabel = uilabel(timingGrid, ...
                'Text', '', 'WordWrap', 'on', ...
                'Tag', 'AdvancedTimingSummaryLabel', ...
                'FontColor', [0.08 0.42 0.18]);
            view.AdvancedTimingSummaryLabel.Layout.Column = [1 4];

            geometryPanel = uipanel(grid, 'Title', 'Visual Geometry');
            geometryGrid = uigridlayout(geometryPanel, [2 4]);
            geometryGrid.RowHeight = {30,30};
            geometryGrid.ColumnWidth = {92,'1x',102,'1x'};
            geometryGrid.Padding = [6 5 6 5];
            uilabel(geometryGrid, 'Text', 'Contrast');
            view.VisualAmplitudeField = uieditfield(geometryGrid, 'numeric', ...
                'Limits', [0 1], 'Value', 0.5, 'Tag', 'VisualAmplitudeField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'Amplitude', event.PreviousValue, source.Value));
            uilabel(geometryGrid, 'Text', 'SF (cpd)');
            view.VisualSpatialFrequencyField = uieditfield(geometryGrid, 'numeric', ...
                'Limits', [eps Inf], 'Value', 0.04, ...
                'Tag', 'VisualSpatialFrequencyField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'SpatialFrequencyCPD', event.PreviousValue, source.Value));
            uilabel(geometryGrid, 'Text', 'Distance (cm)');
            view.VisualViewingDistanceField = uieditfield(geometryGrid, 'numeric', ...
                'Limits', [eps Inf], 'Value', 9, 'Tag', 'VisualViewingDistanceField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'ViewingDistanceCm', event.PreviousValue, source.Value));
            uilabel(geometryGrid, 'Text', 'Screen width (cm)');
            view.VisualScreenWidthField = uieditfield(geometryGrid, 'numeric', ...
                'Limits', [eps Inf], 'Value', 11, 'Tag', 'VisualScreenWidthField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'ScreenWidthCm', event.PreviousValue, source.Value));

            displayPanel = uipanel(grid, ...
                'Title', 'PTB Display & Frame Timing', ...
                'Tag', 'AdvancedPtbDisplayPanel');
            displayGrid = uigridlayout(displayPanel, [4 4]);
            displayGrid.RowHeight = {30,30,30,48};
            displayGrid.ColumnWidth = {104,'1x',110,'1x'};
            displayGrid.Padding = [6 5 6 5];
            uilabel(displayGrid, 'Text', 'Idle RGB');
            view.VisualIdleColorField = uieditfield(displayGrid, 'text', ...
                'Value', '[0 0 0]', 'Tag', 'VisualIdleColorField', ...
                'Tooltip', 'PTB standby color when no stimulus is playing.', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.advancedVisualDisplayEdited('IdleColor', source, event));
            uilabel(displayGrid, 'Text', 'ISI/baseline RGB');
            view.VisualBaselineColorField = uieditfield(displayGrid, 'text', ...
                'Value', '[0.501961 0.501961 0.501961]', ...
                'Tag', 'VisualBaselineColorField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.advancedVisualDisplayEdited('BaselineColor', source, event));
            uilabel(displayGrid, 'Text', 'White RGB');
            view.VisualWhiteColorField = uieditfield(displayGrid, 'text', ...
                'Value', '[1 1 1]', 'Tag', 'VisualWhiteColorField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.advancedVisualDisplayEdited('WhiteColor', source, event));
            uilabel(displayGrid, 'Text', 'Black RGB');
            view.VisualBlackColorField = uieditfield(displayGrid, 'text', ...
                'Value', '[0 0 0]', 'Tag', 'VisualBlackColorField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.advancedVisualDisplayEdited('BlackColor', source, event));
            uilabel(displayGrid, 'Text', 'Blue RGB');
            view.VisualBlueColorField = uieditfield(displayGrid, 'text', ...
                'Value', '[0 0 1]', 'Tag', 'VisualBlueColorField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.advancedVisualDisplayEdited('BlueColor', source, event));
            uilabel(displayGrid, 'Text', 'Phase offset (deg)');
            view.VisualInitialPhaseField = uieditfield(displayGrid, 'numeric', ...
                'Value', 0, 'Tag', 'VisualInitialPhaseField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.advancedVisualDisplayEdited('InitialPhaseDeg', source, event));
            uilabel(displayGrid, 'Text', 'Flip deadline / IFI');
            view.VisualFlipDeadlineField = uieditfield(displayGrid, 'numeric', ...
                'Limits', [eps 1], 'Value', 0.5, ...
                'Tag', 'VisualFlipDeadlineField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.advancedVisualDisplayEdited('FlipDeadlineFraction', ...
                    source, event));
            displayHint = uilabel(displayGrid, 'Text', ...
                ['RGB values use 0–1. Idle is black by default; ISI remains gray. ', ...
                 'PTB sync tests and process priority are safety settings and remain fixed.'], ...
                'WordWrap', 'on', 'FontColor', [0.15 0.32 0.50]);
            displayHint.Layout.Column = [3 4];

            daqPanel = uipanel(grid, 'Title', 'DAQ Output');
            daqGrid = uigridlayout(daqPanel, [2 4]);
            daqGrid.RowHeight = {30,42};
            daqGrid.ColumnWidth = {112,'1x',112,'1x'};
            daqGrid.Padding = [6 5 6 5];
            uilabel(daqGrid, 'Text', 'Output rate (Hz)');
            view.DaqSampleRateField = uieditfield(daqGrid, 'numeric', ...
                'Limits', [100 Inf], 'Value', 10000, ...
                'Tag', 'DaqSampleRateField', ...
                'ValueChangedFcn', @(source,event) callbacks.advancedHardwareSettingEdited( ...
                    'DaqSampleRateHz', event.PreviousValue, source.Value));
            uilabel(daqGrid, 'Text', 'DMD IN1 line');
            view.DmdDaqPortField = uieditfield(daqGrid, 'text', ...
                'Value', char(values.dmdTriggerPort), ...
                'Editable', 'off', 'Tag', 'DmdDaqPortField');
            dmdPortHint = uilabel(daqGrid, 'Text', ...
                ['Output waveform rate is adjustable here; rebuilt input feedback is ', ...
                 '2000 Hz. Change physical mappings in Developer & Logs. Blank DMD IN1 ', ...
                 'blocks DMD arming.'], ...
                'WordWrap', 'on', 'FontColor', [0.15 0.32 0.50]);
            dmdPortHint.Layout.Column = [1 4];

            dmdDevicePanel = uipanel(grid, ...
                'Title', 'DMD Device Timing & Trigger Polarity', ...
                'Tag', 'AdvancedDmdDevicePanel');
            dmdDeviceGrid = uigridlayout(dmdDevicePanel, [7 4]);
            dmdDeviceGrid.RowHeight = {30,30,30,30,30,30,68};
            dmdDeviceGrid.ColumnWidth = {118,'1x',118,'1x'};
            dmdDeviceGrid.Padding = [6 5 6 5];
            view.DmdVerticalMirrorCheckBox = uicheckbox(dmdDeviceGrid, ...
                'Text', 'Vertical mirror', 'Value', false, ...
                'Tag', 'DmdVerticalMirrorCheckBox', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('VerticalMirror', ...
                    event.PreviousValue, source.Value));
            view.DmdVerticalMirrorCheckBox.Layout.Column = [1 2];
            view.DmdDataReverseCheckBox = uicheckbox(dmdDeviceGrid, ...
                'Text', 'Data reverse', 'Value', false, ...
                'Tag', 'DmdDataReverseCheckBox', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('DataReverse', ...
                    event.PreviousValue, source.Value));
            view.DmdDataReverseCheckBox.Layout.Column = 3;
            view.DmdRowAddressingCheckBox = uicheckbox(dmdDeviceGrid, ...
                'Text', 'Row addressing', 'Value', false, ...
                'Tag', 'DmdRowAddressingCheckBox', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('RowAddressing', ...
                    event.PreviousValue, source.Value));
            view.DmdRowAddressingCheckBox.Layout.Column = 4;
            uilabel(dmdDeviceGrid, 'Text', 'Input trigger edge');
            view.DmdInputEdgeDropDown = uidropdown(dmdDeviceGrid, ...
                'Items', {'Rising','Falling'}, 'Value', 'Rising', ...
                'Tag', 'DmdInputEdgeDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('InputTriggerEdge', ...
                    event.PreviousValue, source.Value));
            uilabel(dmdDeviceGrid, 'Text', 'Output trigger edge');
            view.DmdOutputEdgeDropDown = uidropdown(dmdDeviceGrid, ...
                'Items', {'Rising','Falling'}, 'Value', 'Rising', ...
                'Tag', 'DmdOutputEdgeDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('OutputTriggerEdge', ...
                    event.PreviousValue, source.Value));
            uilabel(dmdDeviceGrid, 'Text', 'Divided trigger edge');
            view.DmdDividedEdgeDropDown = uidropdown(dmdDeviceGrid, ...
                'Items', {'Rising','Falling'}, 'Value', 'Rising', ...
                'Tag', 'DmdDividedEdgeDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('DividedTriggerEdge', ...
                    event.PreviousValue, source.Value));
            uilabel(dmdDeviceGrid, 'Text', 'Trigger division');
            view.DmdTriggerDivisionField = uieditfield(dmdDeviceGrid, 'numeric', ...
                'Limits', [0 Inf], 'RoundFractionalValues', 'on', 'Value', 0, ...
                'Tag', 'DmdTriggerDivisionField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('TriggerDivision', ...
                    event.PreviousValue, source.Value));
            uilabel(dmdDeviceGrid, 'Text', 'Internal play (Hz)');
            view.DmdInternalRateField = uieditfield(dmdDeviceGrid, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 1, ...
                'Tag', 'DmdInternalRateField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('InternalPlaybackHz', ...
                    event.PreviousValue, source.Value));
            uilabel(dmdDeviceGrid, 'Text', 'Picture-count register');
            view.DmdPictureCountActionDropDown = uidropdown(dmdDeviceGrid, ...
                'Items', {'Clear','Write'}, 'Value', 'Clear', ...
                'Tag', 'DmdPictureCountActionDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdDeviceParameterEdited('PictureCountRegister', ...
                    event.PreviousValue, source.Value));
            uilabel(dmdDeviceGrid, 'Text', 'IN1 rate (frames/s)', ...
                'Tooltip', ['Default 10 binary frames/s. Each configured IN1 edge ', ...
                    'advances one DMD binary frame in External IN1 mode.']);
            view.LightStimDmdRateField = uieditfield(dmdDeviceGrid, 'numeric', ...
                'Limits', [0.001 Inf], 'Value', 10, ...
                'Tag', 'LightStimDmdRateField', ...
                'Tooltip', ['DMD external-trigger rate used to build the DAQ ', ...
                    'timeline; default is 10 binary frames/s (10 Hz).'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdTriggerRateEdited( ...
                    event.PreviousValue, source.Value));
            in1Hint = uilabel(dmdDeviceGrid, 'Text', ...
                ['Rising edge is the rig default. IN1 high time is configured ', ...
                 'beside DMD playback; the signal always returns low.'], ...
                'WordWrap', 'on', 'FontColor', [0.15 0.32 0.50]);
            in1Hint.Layout.Column = [3 4];
            uilabel(dmdDeviceGrid, 'Text', 'Compile depth');
            view.DmdBitDepthDropDown = uidropdown(dmdDeviceGrid, ...
                'Items', {'1-bit binary','8-bit grayscale'}, ...
                'Value', '1-bit binary', 'Tag', 'DmdBitDepthDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdPatternSettingEdited('BitDepth', ...
                    event.PreviousValue, source.Value));
            view.DmdTrailingOffPaddingCheckBox = uicheckbox(dmdDeviceGrid, ...
                'Text', 'Append trailing OFF frames (legacy block fill)', ...
                'Value', false, 'Tag', 'DmdTrailingOffPaddingCheckBox', ...
                'Tooltip', ['Generated Each ROI only: complete the final hardware ', ...
                    'block with dark frames instead of repeating the ROI sequence. ', ...
                    'Independent of inter-ROI OFF insertion.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdPatternSettingEdited('TrailingOffBlockFill', ...
                    event.PreviousValue, source.Value));
            view.DmdTrailingOffPaddingCheckBox.Layout.Column = [3 4];
            view.DmdApplyParametersButton = uibutton(dmdDeviceGrid, 'push', ...
                'Text', 'Apply DMD device settings', ...
                'Tag', 'DmdApplyParametersButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.applyDmdDeviceParametersClicked());
            view.DmdApplyParametersButton.Layout.Column = [1 2];
            view.DmdApplyParametersButton.Layout.Row = 7;
            view.DmdRepeatToFillTimelineCheckBox = uicheckbox(dmdDeviceGrid, ...
                'Text', 'Repeat IN1 train to fill Record (advanced)', ...
                'Value', false, 'Tag', 'DmdRepeatToFillTimelineCheckBox', ...
                'Tooltip', ['OFF (default): after the configured DMD trigger ', ...
                    'train ends, IN1 stays LOW. ON: repeat the complete IN1 ', ...
                    'train until Camera END, then truncate and return LOW.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdRepeatToFillEdited( ...
                    event.PreviousValue, source.Value));
            view.DmdRepeatToFillTimelineCheckBox.Layout.Column = [3 4];
            view.DmdRepeatToFillTimelineCheckBox.Layout.Row = 7;

            networkPanel = uipanel(grid, 'Title', 'DMD Network');
            networkGrid = uigridlayout(networkPanel, [3 4]);
            networkGrid.RowHeight = {30,30,48};
            networkGrid.ColumnWidth = {82,'1x',70,'1x'};
            networkGrid.Padding = [6 5 6 5];
            uilabel(networkGrid, 'Text', 'Host IP');
            view.DmdHostAddressField = uieditfield(networkGrid, 'text', ...
                'Value', char(values.dmdNetwork.host_address), ...
                'Editable', 'off', 'Tag', 'DmdHostAddressField');
            uilabel(networkGrid, 'Text', 'Port');
            view.DmdHostPortField = uieditfield(networkGrid, 'numeric', ...
                'Limits', [1 65535], 'RoundFractionalValues', 'on', ...
                'Value', values.dmdNetwork.host_port, ...
                'Editable', 'off', 'Tag', 'DmdHostPortField');
            uilabel(networkGrid, 'Text', 'DMD IP');
            view.DmdTargetAddressField = uieditfield(networkGrid, 'text', ...
                'Value', char(values.dmdNetwork.target_address), ...
                'Editable', 'off', 'Tag', 'DmdTargetAddressField');
            uilabel(networkGrid, 'Text', 'Port');
            view.DmdTargetPortField = uieditfield(networkGrid, 'numeric', ...
                'Limits', [1 65535], 'RoundFractionalValues', 'on', ...
                'Value', values.dmdNetwork.target_port, ...
                'Editable', 'off', 'Tag', 'DmdTargetPortField');
            networkHint = uilabel(networkGrid, 'Text', ...
                ['Values mirror Rig Wiring JSON. Connect performs Query/Analysis ', ...
                 'before pattern validation.'], ...
                'WordWrap', 'on');
            networkHint.Layout.Column = [1 4];

        end
    end
end
