classdef CameraPanel < handle
    %CAMERAPANEL Owns panel controls and event bindings.
    % Receives only its parent, display values and explicit callbacks.
    properties
        BinDropDowns
        CameraApplyButtons
        CameraAxes
        CameraModeLabels
        CameraPanels
        CameraPreviewStartButtons
        CameraPreviewStopButtons
        CameraSnapButtons
        CameraStatusLabels
        CameraTitleLabels
        ContrastHighFields
        ContrastLowFields
        ContrastModes
        ExposureFields
        ExposurePresetDropDowns
        FPSLabels
        ImageHandles
        ImagingLabels
        ROIFields
        ROIPresetDropDowns
        TransposeChecks
    end

    methods
        function view = CameraPanel(parent, cameraIndex, transposeDisplay, ...
                callbacks, axesImplementation)
            if nargin < 5
                axesImplementation = "axes";
            end
            panel = uipanel(parent, 'BorderType', 'line', ...
                'BackgroundColor', [0.985 0.985 0.985], ...
                'Tag', sprintf('CameraPanel%d', cameraIndex));
            panel.Layout.Row = 1;
            panel.Layout.Column = cameraIndex;
            view.CameraPanels = panel;

            grid = uigridlayout(panel, [9 1]);
            grid.RowHeight = {34, 24, '1x', 30, 70, 34, 38, 28, 24};
            grid.Padding = [6 6 6 6];
            grid.RowSpacing = 4;

            view.CameraTitleLabels = uilabel(grid, ...
                'FontWeight', 'bold', 'FontSize', 14, 'HorizontalAlignment', 'center');
            view.CameraModeLabels = uilabel(grid, ...
                'Text', 'Requested: 2304x2304 | 16-bit | Bin1 | Fast | ROI 512x512', ...
                'HorizontalAlignment', 'center', 'FontName', 'Consolas', ...
                'FontColor', [0.12 0.32 0.50], ...
                'Tag', sprintf('Camera%dModeLabel', cameraIndex));

            if strcmpi(string(axesImplementation), "axes")
                ax = axes(grid);
                disableDefaultInteractivity(ax);
                axtoolbar(ax, {});
            else
                ax = uiaxes(grid);
                ax.Toolbar.Visible = 'off';
            end
            ax.Tag = sprintf('Camera%dAxes', cameraIndex);
            ax.XTick = [];
            ax.YTick = [];
            ax.Box = 'on';
            ax.YDir = 'reverse';
            hImage = image(ax, zeros(512, 512, 'uint16'), 'CDataMapping', 'scaled');
            ax.Colormap = gray(256);
            hImage.Tag = sprintf('Camera%dPreviewImage', cameraIndex);
            axis(ax, 'image');
            ax.CLim = [0 65535];
            ax.XLimMode = 'manual';
            ax.YLimMode = 'manual';
            ax.CLimMode = 'manual';
            ax.ALimMode = 'manual';
            setappdata(hImage, 'UpdatePreviewWindowFcn', ...
                @(~, event, imageObject) callbacks.previewFrameCallback(cameraIndex, event, imageObject));
            view.CameraAxes = ax;
            view.ImageHandles = hImage;

            stateGrid = uigridlayout(grid, [1 2]);
            stateGrid.ColumnWidth = {'2x','1x'};
            stateGrid.Padding = [0 0 0 0];
            view.FPSLabels = uieditfield(stateGrid, 'text', ...
                'Editable', 'off', 'Value', 'Stream -- | View -- | Record --', ...
                'FontName', 'Consolas', 'Tag', sprintf('FPSLabel%d', cameraIndex));
            view.ImagingLabels = uilabel(stateGrid, ...
                'Text', 'Imaging: waiting', 'HorizontalAlignment', 'right', ...
                'Tag', sprintf('Camera%dImagingStatus', cameraIndex));

            settings = uigridlayout(grid, [2 6]);
            settings.ColumnWidth = {82,122,'1x',70,50,74};
            settings.RowHeight = {28,28};
            settings.Padding = [0 0 0 0];
            settings.RowSpacing = 2;
            settings.ColumnSpacing = 4;
            label = uilabel(settings, 'Text', 'Exposure (ms)');
            label.Layout.Row = 1;
            label.Layout.Column = 1;
            view.ExposurePresetDropDowns = uidropdown(settings, ...
                'Items', {'2.493 ms','10 ms','40 ms','100 ms', ...
                    'Custom (saved)'}, ...
                'Value', '2.493 ms', ...
                'Tag', sprintf('Camera%dExposurePresetDropDown', cameraIndex), ...
                'ValueChangedFcn', @(source,event) callbacks.exposurePresetChanged( ...
                    cameraIndex, event.PreviousValue, source.Value));
            view.ExposurePresetDropDowns.Layout.Row = 1;
            view.ExposurePresetDropDowns.Layout.Column = 2;
            view.ExposureFields = uieditfield(settings, 'numeric', ...
                'Limits', [0.001 Inf], 'Value', 2.493, ...
                'Tag', sprintf('Camera%dExposureField', cameraIndex), ...
                'ValueChangedFcn', @(source,event) callbacks.exposureValueEdited( ...
                    cameraIndex, event.PreviousValue, source.Value));
            view.ExposureFields.Layout.Row = 1;
            view.ExposureFields.Layout.Column = [3 4];
            label = uilabel(settings, 'Text', 'Bin');
            label.Layout.Row = 1;
            label.Layout.Column = 5;
            view.BinDropDowns = uidropdown(settings, ...
                'Items', {'1x','2x','4x'}, 'ItemsData', [1 2 4], 'Value', 1, ...
                'Tag', sprintf('Camera%dBinDropDown', cameraIndex), ...
                'ValueChangedFcn', @(source,event) callbacks.binChanged( ...
                    cameraIndex, event.PreviousValue, source.Value));
            view.BinDropDowns.Layout.Row = 1;
            view.BinDropDowns.Layout.Column = 6;
            label = uilabel(settings, 'Text', 'ROI [x y w h]');
            label.Layout.Row = 2;
            label.Layout.Column = 1;
            view.ROIPresetDropDowns = uidropdown(settings, ...
                'Items', {'512 center','1024 center','2304 full', ...
                    'Custom (saved)'}, ...
                'Value', '512 center', ...
                'Tag', sprintf('Camera%dROIPresetDropDown', cameraIndex), ...
                'ValueChangedFcn', @(source,event) callbacks.roiPresetChanged( ...
                    cameraIndex, event.PreviousValue, source.Value));
            view.ROIPresetDropDowns.Layout.Row = 2;
            view.ROIPresetDropDowns.Layout.Column = 2;
            view.ROIFields = uieditfield(settings, 'text', ...
                'Value', '[896 896 512 512]', ...
                'Tag', sprintf('Camera%dROIField', cameraIndex), ...
                'ValueChangedFcn', @(source,event) callbacks.roiValueEdited( ...
                    cameraIndex, event.PreviousValue, source.Value));
            view.ROIFields.Layout.Row = 2;
            view.ROIFields.Layout.Column = [3 5];
            view.CameraApplyButtons = uibutton(settings, 'push', ...
                'Text', 'Apply', 'Tag', sprintf('Camera%dApplySettingsButton', cameraIndex), ...
                'ButtonPushedFcn', @(~,~) callbacks.applyCameraSettings(cameraIndex));
            view.CameraApplyButtons.Layout.Row = 2;
            view.CameraApplyButtons.Layout.Column = 6;

            cameraButtons = uigridlayout(grid, [1 3]);
            cameraButtons.ColumnWidth = {'1x','1x','1x'};
            cameraButtons.Padding = [0 0 0 0];
            view.CameraPreviewStartButtons = uibutton(cameraButtons, 'push', ...
                'Text', 'Preview', 'Tag', sprintf('Camera%dPreviewButton', cameraIndex), ...
                'ButtonPushedFcn', @(~,~) callbacks.startCameraPreviewClicked(cameraIndex));
            view.CameraPreviewStopButtons = uibutton(cameraButtons, 'push', ...
                'Text', 'Stop', 'Enable', 'off', ...
                'Tag', sprintf('Camera%dStopPreviewButton', cameraIndex), ...
                'ButtonPushedFcn', @(~,~) callbacks.stopCameraPreview(cameraIndex, 'camera_button'));
            view.CameraSnapButtons = uibutton(cameraButtons, 'push', ...
                'Text', 'Snap', 'Tag', sprintf('Camera%dSnapButton', cameraIndex), ...
                'ButtonPushedFcn', @(~,~) callbacks.takeSnap(cameraIndex));

            contrastGrid = uigridlayout(grid, [1 7]);
            contrastGrid.ColumnWidth = {52,68,28,52,32,52,52};
            contrastGrid.Padding = [0 0 0 0];
            uilabel(contrastGrid, 'Text', 'Contrast');
            view.ContrastModes = uidropdown(contrastGrid, ...
                'Items', {'Auto','Manual'}, 'Value', 'Auto', ...
                'Tag', sprintf('Camera%dContrastMode', cameraIndex), ...
                'ValueChangedFcn', @(~,~) callbacks.contrastModeChanged(cameraIndex));
            uilabel(contrastGrid, 'Text', 'Low');
            view.ContrastLowFields = uieditfield(contrastGrid, 'numeric', ...
                'Limits', [0 65535], 'Value', 0, 'Enable', 'off', ...
                'Tag', sprintf('Camera%dContrastLow', cameraIndex), ...
                'ValueDisplayFormat', '%.0f', ...
                'ValueChangedFcn', @(source,event) callbacks.contrastBoundEdited( ...
                    cameraIndex, 'Low', event.PreviousValue, source.Value));
            uilabel(contrastGrid, 'Text', 'High');
            view.ContrastHighFields = uieditfield(contrastGrid, 'numeric', ...
                'Limits', [0 65535], 'Value', 65535, 'Enable', 'off', ...
                'Tag', sprintf('Camera%dContrastHigh', cameraIndex), ...
                'ValueDisplayFormat', '%.0f', ...
                'ValueChangedFcn', @(source,event) callbacks.contrastBoundEdited( ...
                    cameraIndex, 'High', event.PreviousValue, source.Value));
            uibutton(contrastGrid, 'push', 'Text', 'Apply', ...
                'Tag', sprintf('Camera%dContrastApply', cameraIndex), ...
                'ButtonPushedFcn', @(~,~) callbacks.applyContrast(cameraIndex));

            view.TransposeChecks = uicheckbox(grid, ...
                'Text', 'Transpose display only (raw uint16 unchanged)', ...
                'Tag', sprintf('Camera%dTranspose', cameraIndex), ...
                'Value', transposeDisplay, ...
                'ValueChangedFcn', @(source,~) callbacks.transposeChanged(cameraIndex, source.Value));
            view.CameraStatusLabels = uilabel(grid, ...
                'Text', 'Ready', 'FontColor', [0.25 0.25 0.25], ...
                'Tag', sprintf('Camera%dActionStatus', cameraIndex));
        end
    end
end
