classdef LedFlickerPanel < handle
    %LEDFLICKERPANEL Owns panel controls and event bindings.
    % Receives only its parent, display values and explicit callbacks.
    properties
        LedFlickerAoTable
        LedFlickerArmButton
        LedFlickerCyclesField
        LedFlickerDelayField
        LedFlickerDisarmButton
        LedFlickerDoTable
        LedFlickerFrequencyField
        LedFlickerLamp
        LedFlickerOffField
        LedFlickerOnField
        LedFlickerStatusLabel
    end

    methods
        function view = LedFlickerPanel(parent, callbacks)
            % Fill the whole LED tab instead of using uipanel's default
            % 260-by-221-pixel Position.
            tabGrid = uigridlayout(parent, [1 1]);
            tabGrid.RowHeight = {'1x'};
            tabGrid.ColumnWidth = {'1x'};
            tabGrid.Padding = [0 0 0 0];
            tabGrid.Tag = 'LedFlickerTabGrid';
            panel = uipanel(tabGrid, ...
                'Title', 'DAQ LED Flicker — DO enable + AO frequency');
            grid = uigridlayout(panel, [9 1]);
            grid.RowHeight = {102,32,32,34,'1x',32,'1x',32,48};
            grid.Padding = [8 6 8 6];
            grid.Tag = 'LedFlickerPanelGrid';

            callbacks.createModuleMethodPanel(grid, 'visual_led', ...
                'LED Flicker Method');

            status = uigridlayout(grid, [1 3]);
            status.ColumnWidth = {22,190,'1x'};
            status.Padding = [0 0 0 0];
            view.LedFlickerLamp = uilamp(status, ...
                'Color', [0.65 0.65 0.65], 'Tag', 'LedFlickerLamp');
            uilabel(status, 'Text', 'DAQ visual stimulus');
            view.LedFlickerStatusLabel = uilabel(status, ...
                'Text', 'OFF — configure tables, then Arm', ...
                'Tag', 'LedFlickerStatusLabel');

            preset = uigridlayout(grid, [1 10]);
            preset.ColumnWidth = {42,60,42,60,48,60,66,70,'1x',86};
            preset.Padding = [0 0 0 0];
            uilabel(preset, 'Text', 'ON (s)');
            view.LedFlickerOnField = uieditfield(preset, 'numeric', ...
                'Limits', [0.001 Inf], 'Value', 1, 'Tag', 'LedFlickerOnField');
            uilabel(preset, 'Text', 'OFF');
            view.LedFlickerOffField = uieditfield(preset, 'numeric', ...
                'Limits', [0 Inf], 'Value', 0, 'Tag', 'LedFlickerOffField');
            uilabel(preset, 'Text', 'Cycles');
            view.LedFlickerCyclesField = uieditfield(preset, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', ...
                'Value', 1, 'Tag', 'LedFlickerCyclesField');
            uilabel(preset, 'Text', 'Frequency');
            view.LedFlickerFrequencyField = uieditfield(preset, 'numeric', ...
                'Limits', [0 120], 'Value', 60, ...
                'Tag', 'LedFlickerFrequencyField');
            uilabel(preset, 'Text', 'Hz (AO = Hz / 24)');
            uibutton(preset, 'push', 'Text', 'Generate', ...
                'Tag', 'LedFlickerGenerateButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.generateLedFlickerPreset());

            delay = uigridlayout(grid, [1 3]);
            delay.ColumnWidth = {105,100,'1x'};
            delay.Padding = [0 0 0 0];
            uilabel(delay, 'Text', 'Start delay (s)');
            view.LedFlickerDelayField = uieditfield(delay, 'numeric', ...
                'Limits', [0 Inf], 'Value', 0, 'Tag', 'LedFlickerDelayField', ...
                'ValueChangedFcn', @(source,event) ...
                callbacks.ledFlickerSettingEdited('Delay', ...
                event.PreviousValue, source.Value));
            uilabel(delay, 'Text', ...
                'Time zero = camera PRE end; remaining PRE/POST outputs are safe 0.', ...
                'FontColor', [0.25 0.35 0.48]);

            view.LedFlickerDoTable = uitable(grid, ...
                'Data', [0 0; 0 1; 1 1; 1 0], ...
                'ColumnName', {'Time (s)','Enable (0/1)'}, ...
                'ColumnEditable', [true true], ...
                'Tag', 'LedFlickerDoTable', ...
                'CellSelectionCallback', @(~,event) ...
                callbacks.ledFlickerRowsSelected('do', event.Indices), ...
                'CellEditCallback', @(source,event) ...
                callbacks.ledFlickerDoEdited(source, event));
            doButtons = uigridlayout(grid, [1 5]);
            doButtons.ColumnWidth = {'1x','1x','1x','1x','1x'};
            doButtons.Padding = [0 0 0 0];
            callbacks.ledFlickerTableButtons(doButtons, 'do');

            view.LedFlickerAoTable = uitable(grid, ...
                'Data', [0 0 0; 0 60 2.5; 1 60 2.5; 1 0 0], ...
                'ColumnName', {'Time (s)','Frequency (Hz)','AO (V)'}, ...
                'ColumnEditable', [true true true], ...
                'Tag', 'LedFlickerAoTable', ...
                'CellSelectionCallback', @(~,event) ...
                callbacks.ledFlickerRowsSelected('ao', event.Indices), ...
                'CellEditCallback', @(source,event) ...
                callbacks.ledFlickerAoEdited(source, event));
            aoButtons = uigridlayout(grid, [1 5]);
            aoButtons.ColumnWidth = {'1x','1x','1x','1x','1x'};
            aoButtons.Padding = [0 0 0 0];
            callbacks.ledFlickerTableButtons(aoButtons, 'ao');

            actions = uigridlayout(grid, [1 4]);
            actions.ColumnWidth = {'1x','1x','1x','2x'};
            actions.Padding = [0 0 0 0];
            view.LedFlickerArmButton = uibutton(actions, 'push', ...
                'Text', 'Arm LED Flicker', 'Tag', 'LedFlickerArmButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.armLedFlicker());
            view.LedFlickerDisarmButton = uibutton(actions, 'push', ...
                'Text', 'Disarm', 'Enable', 'off', ...
                'Tag', 'LedFlickerDisarmButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.disarmLedFlicker('user'));
            uibutton(actions, 'push', 'Text', 'Reset default', ...
                'Tag', 'LedFlickerResetButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.resetLedFlicker());
            uilabel(actions, 'Text', ...
                ['Record uses one camera START, finite frame targets, and ', ...
                 'DAQ-counter VSYNC alignment; no frame-by-frame trigger.'], ...
                'WordWrap', 'on');
        end
    end
end
