classdef LightSourcesPanel < handle
    %LIGHTSOURCESPANEL Owns panel controls and event bindings.
    % Receives only its parent, display values and explicit callbacks.
    properties
        LightIntensityField
        LightIntensitySlider
        LightIntensityUnitLabel
        LightLamp
        LightStatusLabel
        LightTable
        ObisLamps cell = {[], []}
        ObisStatusLabels cell = {[], []}
        SpectraStateLabel
    end

    methods
        function view = LightSourcesPanel(parent, callbacks)
            panel = uipanel(parent, 'Title', 'Light Sources');
            grid = uigridlayout(panel, [6 1]);
            grid.RowHeight = {30,32,24,'1x',42,24};
            grid.Padding = [5 4 5 4];
            grid.RowSpacing = 4;
            indicators = uigridlayout(grid, [1 3]);
            indicators.ColumnWidth = {'1x','1x','1x'};
            indicators.Padding = [0 0 0 0];
            spectraState = uigridlayout(indicators, [1 2]);
            spectraState.ColumnWidth = {22,'1x'};
            spectraState.Padding = [0 0 0 0];
            view.LightLamp = uilamp(spectraState, ...
                'Color', [0.65 0.65 0.65], 'Tag', 'LightLamp');
            view.SpectraStateLabel = uilabel(spectraState, ...
                'Text', 'Spectra OFF', 'FontWeight', 'bold');
            for laserIndex = 1:2
                laserState = uigridlayout(indicators, [1 2]);
                laserState.ColumnWidth = {22,'1x'};
                laserState.Padding = [0 0 0 0];
                view.ObisLamps{laserIndex} = uilamp(laserState, ...
                    'Color', [0.65 0.65 0.65], ...
                    'Tag', sprintf('Obis%dLamp', laserIndex));
                wavelength = [405 445];
                view.ObisStatusLabels{laserIndex} = uilabel(laserState, ...
                    'Text', sprintf('%d OFF', wavelength(laserIndex)), ...
                    'FontWeight', 'bold');
            end
            buttons = uigridlayout(grid, [1 3]);
            buttons.ColumnWidth = {'1x','1x','1x'};
            buttons.Padding = [0 0 0 0];
            uibutton(buttons, 'push', 'Text', 'Connect all USB', ...
                'Tag', 'ConnectLightSourcesButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.connectLightSources());
            uibutton(buttons, 'push', 'Text', 'Refresh all', ...
                'ButtonPushedFcn', @(~,~) callbacks.refreshLightSources());
            uibutton(buttons, 'push', 'Text', 'All OFF', ...
                'FontColor', [0.75 0.1 0.1], 'ButtonPushedFcn', @(~,~) callbacks.allLightsOff());
            uilabel(grid, 'Text', ...
                'Select a row; State controls it manually. Every request and result is logged.', ...
                'FontColor', [0.3 0.3 0.3]);
            view.LightTable = uitable(grid, ...
                'ColumnName', {'Use','ID','Control','Alias','Role','Camera','Level %','State'}, ...
                'ColumnEditable', [true false false true true true false true], ...
                'ColumnFormat', {'logical','numeric','char','char', ...
                    {'Off','Imaging','Stimulus'}, {'None','Camera 1','Camera 2','Both'}, ...
                    'numeric',{'OFF','ON'}}, ...
                'RowName', {}, ...
                'ColumnWidth', {35,30,58,94,82,88,46,52}, ...
                'CellEditCallback', @(~,event) callbacks.lightTableEdited(event), ...
                'CellSelectionCallback', @(~,event) callbacks.lightSelectionChanged(event), ...
                'Tag', 'LightTable');
            view.LightTable.Data = { ...
                false, 100, 'AO3/DO23', 'Laser405', 'Off',     'None',     0, 'OFF'; ...
                false, 101, 'AO2/DO11', 'Laser445', 'Off',     'None',     0, 'OFF'; ...
                true,  2,   'CYAN/DO12','LEDcyan',  'Imaging', 'Camera 1', 0, 'OFF'; ...
                false, 3,   'GREEN/DO16','LEDgreen', 'Off',    'None',     0, 'OFF'; ...
                true,  4,   'RED/DO18',  'LEDred',   'Imaging','Camera 2', 0, 'OFF'};
            intensity = uigridlayout(grid, [1 4]);
            intensity.ColumnWidth = {62,'1x',70,34};
            intensity.Padding = [0 0 0 0];
            uilabel(intensity, 'Text', 'Intensity');
            view.LightIntensitySlider = uislider(intensity, 'Limits', [0 100], 'Value', 0, ...
                'MajorTicks', 0:10:100, ...
                'Tag', 'LightIntensitySlider', ...
                'ValueChangingFcn', @(source,event) callbacks.lightSliderChanging(source, event), ...
                'ValueChangedFcn', @(source,~) callbacks.lightSliderChanged(source.Value));
            view.LightIntensityField = uieditfield(intensity, 'numeric', ...
                'Limits', [0 100], 'Value', 0, 'Tag', 'LightIntensityField', ...
                'ValueChangedFcn', @(source,event) callbacks.lightNumericChanged( ...
                    event.PreviousValue, source.Value));
            view.LightIntensityUnitLabel = uilabel(intensity, 'Text', '%');
            view.LightStatusLabel = uilabel(grid, 'Text', 'Ready.', ...
                'Tag', 'LightSourceActionStatus');
        end
    end
end
