classdef LightStimulusPanel < handle
    %LIGHTSTIMULUSPANEL Owns panel controls and event bindings.
    % Receives only its parent, display values and explicit callbacks.
    properties
        DmdAdminRecoverButton
        DmdCalibrationCameraDropDown
        DmdCalibrationLamp
        DmdCalibrationMatrixField
        DmdCalibrationRootField
        DmdCalibrationSourceDropDown
        DmdCalibrationStatusLabel
        DmdCalibrationTiffField
        DmdGridModeDropDown
        DmdGridResolvedPathField
        DmdInsertOffBetweenRoisCheckBox
        DmdLamp
        DmdMaskEachRoiCheckBox
        DmdMaskExpansionField
        DmdMaskGenerateButton
        DmdMaskMinAreaField
        DmdMaskModeDropDown
        DmdMaskReverseCheckBox
        DmdMaskSourceField
        DmdMaskStatusLabel
        DmdMaskThresholdField
        DmdPatternFolderField
        DmdPatternLamp
        DmdPatternStateLabel
        DmdPatternSummaryLabel
        DmdPauseButton
        DmdPictureCountField
        DmdPlayButton
        DmdRecoverPortButton
        DmdStartPositionField
        DmdStatusLabel
        DmdTotalTriggerField
        DmdTriggerDelayField
        DmdTriggerModeDropDown
        DmdTriggerPeriodField
        DmdTriggerRepeatField
        DmdTriggerTable
        LightStimAnalogCalculatedDurationField
        LightStimAnalogDelayField
        LightStimAnalogDurationField
        LightStimAnalogGenerateButton
        LightStimAnalogHighVoltageField
        LightStimAnalogLowVoltageField
        LightStimAnalogOffVoltageField
        LightStimAnalogPointTable
        LightStimAnalogPulseWidthField
        LightStimAnalogRepeatField
        LightStimAnalogTargetDropDown
        LightStimAnalogTimingModeDropDown
        LightStimAnalogWaveformDropDown
        LightStimArmButton
        LightStimDelayField
        LightStimDigitalPointTable
        LightStimDigitalRepeatField
        LightStimDisarmButton
        LightStimDmdLoopSwitch
        LightStimDmdPatternDropDown
        LightStimDmdPulseField
        LightStimDmdSwitch
        LightStimDurationField
        LightStimFrameworkStatusLabel
        LightStimPulsePeriodField
        LightStimPulseWidthField
        LightStimSourceDropDown
        LightStimTimelinePreviewButton
        LightStimWaveformDropDown
    end

    methods
        function view = LightStimulusPanel(parent, callbacks)
            grid = uigridlayout(parent, [2 1]);
            grid.RowHeight = {720,184};
            grid.Padding = [8 8 8 8];
            grid.RowSpacing = 8;
            if isprop(grid, 'Scrollable')
                grid.Scrollable = 'on';
            end

            moduleTabs = uitabgroup(grid, 'Tag', 'LightStimulusModuleTabs');
            laserTab = uitab(moduleTabs, 'Title', 'Laser Waveforms');
            dmdTab = uitab(moduleTabs, 'Title', ...
                'DMD Calibration & Projection');
            laserGrid = uigridlayout(laserTab, [3 1]);
            laserGrid.RowHeight = {102,400,604};
            laserGrid.Padding = [6 6 6 6];
            laserGrid.RowSpacing = 8;
            if isprop(laserGrid, 'Scrollable')
                laserGrid.Scrollable = 'on';
            end
            dmdModuleGrid = uigridlayout(dmdTab, [4 1]);
            dmdModuleGrid.RowHeight = {102,414,294,770};
            dmdModuleGrid.Padding = [6 6 6 6];
            dmdModuleGrid.RowSpacing = 8;
            if isprop(dmdModuleGrid, 'Scrollable')
                dmdModuleGrid.Scrollable = 'on';
            end

            callbacks.createModuleMethodPanel(laserGrid, 'light_stim_laser', ...
                'Laser Waveform Method');
            callbacks.createModuleMethodPanel(dmdModuleGrid, 'dmd', ...
                'DMD Method');

            waveformPanel = uipanel(laserGrid, ...
                'Title', 'Laser DO Gate — full ON/OFF sequence (0/1)');
            waveformGrid = uigridlayout(waveformPanel, [7 4]);
            waveformGrid.RowHeight = {30,30,30,30,160,32,46};
            waveformGrid.ColumnWidth = {112,'1x',112,'1x'};
            waveformGrid.Padding = [6 5 6 5];
            uilabel(waveformGrid, 'Text', 'Source');
            view.LightStimSourceDropDown = uidropdown(waveformGrid, ...
                'Items', {'405','445','405 + 445'}, 'Value', '405', ...
                'Tag', 'LightStimSourceDropDown', ...
                'ValueChangedFcn', @(source,event) callbacks.lightStimulusSettingEdited( ...
                    'Source', event.PreviousValue, source.Value));
            uilabel(waveformGrid, 'Text', 'Generator');
            view.LightStimWaveformDropDown = uidropdown(waveformGrid, ...
                'Items', {'Continuous ON','ON/OFF Cycles','Manual Points'}, ...
                'Value', 'ON/OFF Cycles', ...
                'Tag', 'LightStimWaveformDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusDigitalModeChanged( ...
                    event.PreviousValue, source.Value));
            uilabel(waveformGrid, 'Text', 'DO offset vs Camera START (s)');
            view.LightStimDelayField = uieditfield(waveformGrid, 'numeric', ...
                'Limits', [-Inf Inf], 'Value', 0, 'Tag', 'LightStimDelayField', ...
                'ValueChangedFcn', @(source,event) callbacks.lightStimulusSettingEdited( ...
                    'DelaySeconds', event.PreviousValue, source.Value));
            uilabel(waveformGrid, 'Text', 'Calculated duration (s)');
            view.LightStimDurationField = uieditfield(waveformGrid, 'numeric', ...
                'Limits', [0 Inf], 'Value', 1, 'Editable', 'off', ...
                'Tag', 'LightStimDurationField', ...
                'Tooltip', '(Cycle ON length + Cycle OFF length) x Cycles.');
            uilabel(waveformGrid, 'Text', 'Cycle ON length (s)');
            view.LightStimPulseWidthField = uieditfield(waveformGrid, 'numeric', ...
                'Limits', [0 Inf], 'Value', 0.1, ...
                'Tag', 'LightStimPulseWidthField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusDigitalParameterEdited( ...
                    'CycleOnSeconds', event.PreviousValue, source.Value));
            uilabel(waveformGrid, 'Text', 'Cycle OFF length (s)');
            view.LightStimPulsePeriodField = uieditfield(waveformGrid, 'numeric', ...
                'Limits', [0 Inf], 'Value', 0.9, ...
                'Tag', 'LightStimPulsePeriodField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusDigitalParameterEdited( ...
                    'CycleOffSeconds', event.PreviousValue, source.Value));
            uilabel(waveformGrid, 'Text', 'Cycles');
            view.LightStimDigitalRepeatField = uieditfield(waveformGrid, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 1, ...
                'Tag', 'LightStimDigitalRepeatField', ...
                'Tooltip', 'Number of complete ON/OFF cycles generated into the table.', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusDigitalParameterEdited( ...
                    'Cycles', event.PreviousValue, source.Value));
            durationHint = uilabel(waveformGrid, ...
                'Text', 'Preset changes regenerate the table automatically.', ...
                'FontColor', [0.3 0.3 0.3], ...
                'HorizontalAlignment', 'right');
            durationHint.Layout.Row = 4;
            durationHint.Layout.Column = [3 4];
            view.LightStimDigitalPointTable = uitable(waveformGrid, ...
                'Data', [0 0; 0 1; 0.1 1; 0.1 0; 1 0], ...
                'ColumnName', {'Time in sequence (s)','DO state (0/1)'}, ...
                'ColumnEditable', [true true], 'ColumnWidth', {'auto','auto'}, ...
                'RowName', 'numbered', 'Tag', 'LightStimDigitalPointTable', ...
                'CellSelectionCallback', @(~,event) ...
                    callbacks.waveformTableSelectionChanged('DO', event), ...
                'CellEditCallback', @(source,event) ...
                    callbacks.lightStimulusDigitalPointTableEdited(source, event));
            view.LightStimDigitalPointTable.Layout.Row = 5;
            view.LightStimDigitalPointTable.Layout.Column = [1 4];
            digitalButtons = uigridlayout(waveformGrid, [1 5]);
            digitalButtons.Layout.Row = 6;
            digitalButtons.Layout.Column = [1 4];
            digitalButtons.ColumnWidth = {'1x','1x','1x','1x','1x'};
            digitalButtons.Padding = [0 0 0 0];
            uibutton(digitalButtons, 'push', 'Text', 'Add', ...
                'Tag', 'LightStimDigitalAddPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.addWaveformPoint('DO'));
            uibutton(digitalButtons, 'push', 'Text', 'Insert', ...
                'Tag', 'LightStimDigitalInsertPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.insertWaveformPoint('DO'));
            uibutton(digitalButtons, 'push', 'Text', 'Delete', ...
                'Tag', 'LightStimDigitalDeletePointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.deleteWaveformPoints('DO'));
            uibutton(digitalButtons, 'push', 'Text', 'Clear', ...
                'Tag', 'LightStimDigitalClearPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.clearWaveformPoints('DO'));
            uibutton(digitalButtons, 'push', 'Text', 'Reset', ...
                'Tag', 'LightStimDigitalResetPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.resetDigitalPointTable());
            customHint = uilabel(waveformGrid, 'Text', ...
                ['Preset parameters generate the complete point table after editing stops. ', ...
                 'The table always remains editable and is the exact output source. ', ...
                 'Changing a preset parameter regenerates and replaces the table.'], ...
                'WordWrap', 'on', 'FontColor', [0.3 0.3 0.3]);
            customHint.Layout.Row = 7;
            customHint.Layout.Column = [1 4];

            analogPanel = uipanel(laserGrid, ...
                'Title', 'Laser AO Intensity — full voltage sequence (0–5 V)');
            analogGrid = uigridlayout(analogPanel, [11 4]);
            analogGrid.RowHeight = {30,30,30,30,30,30,32,170,30,34,42};
            analogGrid.ColumnWidth = {112,'1x',112,'1x'};
            analogGrid.Padding = [6 5 6 5];
            uilabel(analogGrid, 'Text', 'AO target');
            view.LightStimAnalogTargetDropDown = uidropdown(analogGrid, ...
                'Items', {'405','445'}, 'Value', '405', ...
                'Tag', 'LightStimAnalogTargetDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogTargetChanged( ...
                    event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'Timing mode');
            view.LightStimAnalogTimingModeDropDown = uidropdown(analogGrid, ...
                'Items', {'Follow DO','Independent'}, 'Value', 'Follow DO', ...
                'Tag', 'LightStimAnalogTimingModeDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogTimingModeChanged( ...
                    event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'Generator');
            view.LightStimAnalogWaveformDropDown = uidropdown(analogGrid, ...
                'Items', {'Constant','Linear','Triangle','Custom'}, ...
                'Value', 'Constant', ...
                'Tag', 'LightStimAnalogWaveformDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogHelperEdited( ...
                    'Preset', event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'AO offset vs Camera START (s)');
            view.LightStimAnalogDelayField = uieditfield(analogGrid, 'numeric', ...
                'Limits', [-Inf Inf], 'Value', 0, 'Tag', 'LightStimAnalogDelayField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogSettingEdited( ...
                    'DelaySeconds', event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'Cycle ON length (s)');
            view.LightStimAnalogDurationField = uieditfield(analogGrid, 'numeric', ...
                'Limits', [0 Inf], 'Value', 0.1, ...
                'Tag', 'LightStimAnalogDurationField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogHelperEdited( ...
                    'CycleOnSeconds', event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'Cycle OFF length (s)');
            view.LightStimAnalogPulseWidthField = uieditfield(analogGrid, 'numeric', ...
                'Limits', [0 Inf], 'Value', 0.9, ...
                'Tag', 'LightStimAnalogPulseWidthField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogHelperEdited( ...
                    'CycleOffSeconds', event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'Cycles');
            view.LightStimAnalogRepeatField = uieditfield(analogGrid, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 1, ...
                'Tag', 'LightStimAnalogRepeatField', ...
                'Tooltip', 'Number of complete AO cycles generated into the table.', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogHelperEdited( ...
                    'RepeatCount', event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'Calculated duration (s)');
            view.LightStimAnalogCalculatedDurationField = uieditfield( ...
                analogGrid, 'numeric', 'Limits', [0 Inf], 'Value', 1, ...
                'Editable', 'off', 'Tag', ...
                'LightStimAnalogCalculatedDurationField');
            uilabel(analogGrid, 'Text', 'End / peak / level (V)');
            view.LightStimAnalogHighVoltageField = uieditfield(analogGrid, 'numeric', ...
                'Limits', [0 5], 'Value', 1, ...
                'Tag', 'LightStimAnalogHighVoltageField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogHelperEdited( ...
                    'HighVoltage', event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'Start / low (V)');
            view.LightStimAnalogLowVoltageField = uieditfield(analogGrid, 'numeric', ...
                'Limits', [0 5], 'Value', 0, ...
                'Tag', 'LightStimAnalogLowVoltageField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogHelperEdited( ...
                    'LowVoltage', event.PreviousValue, source.Value));
            uilabel(analogGrid, 'Text', 'OFF voltage (V)');
            view.LightStimAnalogOffVoltageField = uieditfield(analogGrid, 'numeric', ...
                'Limits', [0 5], 'Value', 0, ...
                'Tag', 'LightStimAnalogOffVoltageField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.lightStimulusAnalogHelperEdited( ...
                    'OffVoltage', event.PreviousValue, source.Value));
            view.LightStimAnalogGenerateButton = uibutton(analogGrid, 'push', ...
                'Text', 'Generate AO waveform', ...
                'Tag', 'LightStimAnalogGenerateButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.generateAnalogPointTable());
            view.LightStimAnalogGenerateButton.Layout.Row = 7;
            view.LightStimAnalogGenerateButton.Layout.Column = [1 4];
            view.LightStimAnalogPointTable = uitable(analogGrid, ...
                'Data', [0 0; 0 1; 0.1 1; 0.1 0; 1 0], ...
                'ColumnName', {'Time in sequence (s)','Voltage (V)'}, ...
                'ColumnEditable', [true true], ...
                'ColumnWidth', {'auto','auto'}, ...
                'RowName', 'numbered', 'Tag', 'LightStimAnalogPointTable', ...
                'CellSelectionCallback', @(~,event) ...
                    callbacks.waveformTableSelectionChanged('AO', event), ...
                'CellEditCallback', @(source,event) ...
                    callbacks.lightStimulusAnalogPointTableEdited(source, event));
            view.LightStimAnalogPointTable.Layout.Row = 8;
            view.LightStimAnalogPointTable.Layout.Column = [1 4];
            analogButtons = uigridlayout(analogGrid, [1 5]);
            analogButtons.Layout.Row = 9;
            analogButtons.Layout.Column = [1 4];
            analogButtons.ColumnWidth = {'1x','1x','1x','1x','1x'};
            analogButtons.Padding = [0 0 0 0];
            uibutton(analogButtons, 'push', 'Text', 'Add', ...
                'Tag', 'LightStimAnalogAddPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.addWaveformPoint('AO'));
            uibutton(analogButtons, 'push', 'Text', 'Insert', ...
                'Tag', 'LightStimAnalogInsertPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.insertWaveformPoint('AO'));
            uibutton(analogButtons, 'push', 'Text', 'Delete', ...
                'Tag', 'LightStimAnalogDeletePointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.deleteWaveformPoints('AO'));
            uibutton(analogButtons, 'push', 'Text', 'Clear', ...
                'Tag', 'LightStimAnalogClearPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.clearWaveformPoints('AO'));
            uibutton(analogButtons, 'push', 'Text', 'Reset', ...
                'Tag', 'LightStimAnalogResetPointButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.generateAnalogPointTable());
            view.LightStimTimelinePreviewButton = uibutton(analogGrid, 'push', ...
                'Text', 'Show', ...
                'Tag', 'LightStimTimelinePreviewButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.toggleLightStimulusTimeline());
            view.LightStimTimelinePreviewButton.Layout.Row = 10;
            view.LightStimTimelinePreviewButton.Layout.Column = [1 4];
            analogHint = uilabel(analogGrid, 'Text', ...
                ['Follow DO copies DO timing; Independent keeps separate timing. Generate expands ', ...
                 'all cycles. Rows are joined linearly; equal-time rows are immediate edges. ', ...
                 'AO is forced to 0 V whenever its corresponding DO gate is OFF.'], ...
                'FontColor', [0.3 0.3 0.3]);
            analogHint.Layout.Row = 11;
            analogHint.Layout.Column = [1 4];

            calibrationPanel = uipanel(dmdModuleGrid, ...
                'Title', '1. Camera-to-DMD Calibration (required before stimulation)', ...
                'Tag', 'DmdCalibrationPanel');
            calibrationGrid = uigridlayout(calibrationPanel, [10 4]);
            calibrationGrid.RowHeight = {30,30,30,30,30,38,30,30,30,46};
            calibrationGrid.ColumnWidth = {108,'1x',108,'1x'};
            calibrationGrid.Padding = [6 5 6 5];
            calibrationState = uigridlayout(calibrationGrid, [1 2]);
            calibrationState.Layout.Row = 1;
            calibrationState.Layout.Column = [1 4];
            calibrationState.ColumnWidth = {22,'1x'};
            calibrationState.Padding = [0 0 0 0];
            view.DmdCalibrationLamp = uilamp(calibrationState, ...
                'Color', [0.85 0.15 0.12], 'Tag', 'DmdCalibrationLamp');
            view.DmdCalibrationStatusLabel = uilabel(calibrationState, ...
                'Text', 'NOT CALIBRATED — choose camera and generate both grids', ...
                'FontWeight', 'bold', 'Tag', 'DmdCalibrationStatusLabel');
            calibrationCameraLabel = uilabel(calibrationGrid, ...
                'Text', 'Calibration camera');
            calibrationCameraLabel.Layout.Row = 2;
            calibrationCameraLabel.Layout.Column = 1;
            view.DmdCalibrationCameraDropDown = uidropdown(calibrationGrid, ...
                'Items', {'Camera 1 (Standard grid)', ...
                    'Camera 2 (Flipped grid)'}, ...
                'Value', 'Camera 1 (Standard grid)', ...
                'Tag', 'DmdCalibrationCameraDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdCalibrationCameraChanged( ...
                    event.PreviousValue, source.Value));
            view.DmdCalibrationCameraDropDown.Layout.Row = 2;
            view.DmdCalibrationCameraDropDown.Layout.Column = [2 4];
            gridModeLabel = uilabel(calibrationGrid, 'Text', 'Grid source');
            gridModeLabel.Layout.Row = 3;
            gridModeLabel.Layout.Column = 1;
            view.DmdGridModeDropDown = uidropdown(calibrationGrid, ...
                'Items', {'Auto by camera','Standard','Flipped'}, ...
                'Value', 'Auto by camera', 'Tag', 'DmdGridModeDropDown', ...
                'Tooltip', 'Auto: Camera 1 = Standard, Camera 2 = Flipped.', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdGridModeChanged(event.PreviousValue, source.Value));
            view.DmdGridModeDropDown.Layout.Row = 3;
            view.DmdGridModeDropDown.Layout.Column = 2;
            view.DmdGridResolvedPathField = uieditfield(calibrationGrid, 'text', ...
                'Editable', 'off', 'Value', '', ...
                'Tag', 'DmdGridResolvedPathField', ...
                'Tooltip', 'Exact Standard_Matrix or Flipped_Matrix folder used for playback.');
            view.DmdGridResolvedPathField.Layout.Row = 3;
            view.DmdGridResolvedPathField.Layout.Column = [3 4];
            calibrationRootLabel = uilabel(calibrationGrid, ...
                'Text', 'SaveRoot/_cal');
            calibrationRootLabel.Layout.Row = 4;
            calibrationRootLabel.Layout.Column = 1;
            view.DmdCalibrationRootField = uieditfield(calibrationGrid, 'text', ...
                'Value', '', 'Editable', 'off', ...
                'Tag', 'DmdCalibrationRootField');
            view.DmdCalibrationRootField.Layout.Row = 4;
            view.DmdCalibrationRootField.Layout.Column = [2 3];
            browseCalibrationRootButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Uses SaveRoot', 'Enable', 'off', ...
                'Tag', 'BrowseDmdCalibrationRootButton');
            browseCalibrationRootButton.Layout.Row = 4;
            browseCalibrationRootButton.Layout.Column = 4;
            generateGridButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Generate Both', ...
                'Tag', 'GenerateDmdCalibrationGridsButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.generateDmdCalibrationGrids());
            generateGridButton.Layout.Column = [1 2];
            generateGridButton.Layout.Row = 5;
            projectGridButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Load & Play Grid', ...
                'Tag', 'ProjectDmdCalibrationGridButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.projectDmdCalibrationGrid());
            projectGridButton.Layout.Row = 5;
            projectGridButton.Layout.Column = 3;
            stopGridButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Stop Grid', ...
                'Tag', 'StopDmdCalibrationGridButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.stopDmd());
            stopGridButton.Layout.Row = 5;
            stopGridButton.Layout.Column = 4;
            gridHint = uilabel(calibrationGrid, 'Text', ...
                'Cam1 uses Standard; Cam2 uses horizontally Flipped. Internal DMD playback, no DAQ.', ...
                'FontColor', [0.15 0.32 0.50], 'WordWrap', 'on');
            gridHint.Layout.Row = 6;
            gridHint.Layout.Column = [1 4];
            calibrationSourceLabel = uilabel(calibrationGrid, ...
                'Text', 'Snap source');
            calibrationSourceLabel.Layout.Row = 7;
            calibrationSourceLabel.Layout.Column = 1;
            view.DmdCalibrationSourceDropDown = uidropdown(calibrationGrid, ...
                'Items', {'Fresh Snap','Latest Preview','Load TIFF'}, ...
                'Value', 'Fresh Snap', 'Tag', 'DmdCalibrationSourceDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdCalibrationSourceChanged( ...
                    event.PreviousValue, source.Value));
            view.DmdCalibrationSourceDropDown.Layout.Row = 7;
            view.DmdCalibrationSourceDropDown.Layout.Column = 2;
            snapSolveButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Snap & Select 3 Points', ...
                'Tag', 'SnapSolveDmdCalibrationButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.snapAndSolveDmdCalibration());
            snapSolveButton.Layout.Row = 7;
            snapSolveButton.Layout.Column = [3 4];
            calibrationTiffLabel = uilabel(calibrationGrid, ...
                'Text', 'Calibration TIFF');
            calibrationTiffLabel.Layout.Row = 8;
            calibrationTiffLabel.Layout.Column = 1;
            view.DmdCalibrationTiffField = uieditfield(calibrationGrid, 'text', ...
                'Value', '', 'Tag', 'DmdCalibrationTiffField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdCalibrationPathEdited('Tiff', ...
                    event.PreviousValue, source.Value));
            view.DmdCalibrationTiffField.Layout.Row = 8;
            view.DmdCalibrationTiffField.Layout.Column = 2;
            saveCalibrationTiffButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Capture source', ...
                'Tag', 'SaveDmdCalibrationPreviewButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.saveDmdCalibrationPreview());
            saveCalibrationTiffButton.Layout.Row = 8;
            saveCalibrationTiffButton.Layout.Column = 3;
            chooseCalibrationTiffButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Choose', ...
                'Tag', 'ChooseDmdCalibrationTiffButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.chooseDmdCalibrationTiff());
            chooseCalibrationTiffButton.Layout.Row = 8;
            chooseCalibrationTiffButton.Layout.Column = 4;
            solveCalibrationButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Solve 3 Points', ...
                'Tag', 'SolveDmdCalibrationButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.solveDmdCalibration());
            solveCalibrationButton.Layout.Row = 9;
            solveCalibrationButton.Layout.Column = 1;
            loadCalibrationButton = uibutton(calibrationGrid, 'push', ...
                'Text', 'Load Matrix', ...
                'Tag', 'LoadDmdCalibrationButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.loadDmdCalibration());
            loadCalibrationButton.Layout.Row = 9;
            loadCalibrationButton.Layout.Column = 2;
            view.DmdCalibrationMatrixField = uieditfield( ...
                calibrationGrid, 'text', 'Editable', 'off', ...
                'Value', 'No calibration matrix loaded', ...
                'Tag', 'DmdCalibrationMatrixField');
            view.DmdCalibrationMatrixField.Layout.Row = 9;
            view.DmdCalibrationMatrixField.Layout.Column = [3 4];
            calibrationFooter = uilabel(calibrationGrid, 'Text', ...
                ['Workflow: generate → project → preview selected camera → Save View ', ...
                 '→ choose 3 numbered intersections. Display transpose is corrected before solving.'], ...
                'WordWrap', 'on', 'FontColor', [0.30 0.30 0.30]);
            calibrationFooter.Layout.Row = 10;
            calibrationFooter.Layout.Column = [1 4];

            maskPanel = uipanel(dmdModuleGrid, ...
                'Title', '2. Mask Generation — camera Snap to DMD coordinates', ...
                'Tag', 'DmdMaskPanel');
            maskGrid = uigridlayout(maskPanel, [7 4]);
            maskGrid.RowHeight = {30,30,30,30,30,30,42};
            maskGrid.ColumnWidth = {104,'1x',104,'1x'};
            maskGrid.Padding = [6 5 6 5];
            uilabel(maskGrid, 'Text', 'Mode');
            view.DmdMaskModeDropDown = uidropdown(maskGrid, ...
                'Items', {'Manual','Threshold','Fiji ROI','Cellpose'}, ...
                'Value', 'Manual', 'Tag', 'DmdMaskModeDropDown', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdMaskModeChanged(event.PreviousValue, source.Value));
            uilabel(maskGrid, 'Text', 'Source');
            view.DmdMaskSourceField = uieditfield(maskGrid, 'text', ...
                'Editable', 'off', 'Value', 'Use fresh camera Snap', ...
                'Tag', 'DmdMaskSourceField');
            uibutton(maskGrid, 'push', 'Text', 'Snap source', ...
                'Tag', 'SnapDmdMaskSourceButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.snapDmdMaskSource());
            uibutton(maskGrid, 'push', 'Text', 'Load TIFF', ...
                'Tag', 'LoadDmdMaskSourceButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.loadDmdMaskSource());
            uilabel(maskGrid, 'Text', 'Threshold %');
            view.DmdMaskThresholdField = uieditfield(maskGrid, 'numeric', ...
                'Limits', [0 100], 'Value', 99.5, ...
                'Tag', 'DmdMaskThresholdField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdMaskSettingEdited('ThresholdPercent', ...
                    event.PreviousValue, source.Value));
            uilabel(maskGrid, 'Text', 'Min area (px)');
            view.DmdMaskMinAreaField = uieditfield(maskGrid, 'numeric', ...
                'Limits', [0 Inf], 'RoundFractionalValues', 'on', ...
                'Value', 10, 'Tag', 'DmdMaskMinAreaField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdMaskSettingEdited('MinimumAreaPixels', ...
                    event.PreviousValue, source.Value));
            uilabel(maskGrid, 'Text', 'Expansion (px)');
            view.DmdMaskExpansionField = uieditfield(maskGrid, 'numeric', ...
                'Limits', [0 Inf], 'RoundFractionalValues', 'on', ...
                'Value', 0, 'Tag', 'DmdMaskExpansionField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdMaskSettingEdited('ExpansionPixels', ...
                    event.PreviousValue, source.Value));
            view.DmdMaskEachRoiCheckBox = uicheckbox(maskGrid, ...
                'Text', 'Create Each ROI', 'Value', true, ...
                'Tag', 'DmdMaskEachRoiCheckBox', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdMaskSettingEdited('CreateEachRoi', ...
                    event.PreviousValue, source.Value));
            view.DmdMaskEachRoiCheckBox.Layout.Row = 4;
            view.DmdMaskEachRoiCheckBox.Layout.Column = [1 2];
            view.DmdInsertOffBetweenRoisCheckBox = uicheckbox(maskGrid, ...
                'Text', 'Insert OFF frame after every ROI', 'Value', false, ...
                'Tag', 'DmdInsertOffBetweenRoisCheckBox', ...
                'Tooltip', ['Generated Each ROI only: inserts one explicit dark ', ...
                    'image after each ROI, including the final ROI.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdPatternSettingEdited('InsertOffBetweenRois', ...
                    event.PreviousValue, source.Value));
            view.DmdInsertOffBetweenRoisCheckBox.Layout.Row = 5;
            view.DmdInsertOffBetweenRoisCheckBox.Layout.Column = [1 2];
            view.DmdMaskReverseCheckBox = uicheckbox(maskGrid, ...
                'Text', 'Create reverse', 'Value', true, ...
                'Tag', 'DmdMaskReverseCheckBox', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdMaskSettingEdited('CreateReverse', ...
                    event.PreviousValue, source.Value));
            view.DmdMaskReverseCheckBox.Layout.Row = 4;
            view.DmdMaskReverseCheckBox.Layout.Column = [3 4];
            view.DmdMaskGenerateButton = uibutton(maskGrid, 'push', ...
                'Text', 'Generate & map to DMD', ...
                'Tag', 'GenerateDmdMaskButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.generateDmdMask());
            view.DmdMaskGenerateButton.Layout.Column = [1 2];
            view.DmdMaskGenerateButton.Layout.Row = 6;
            view.DmdMaskStatusLabel = uilabel(maskGrid, ...
                'Text', 'Load calibration, then choose a camera-space source.', ...
                'WordWrap', 'on', 'Tag', 'DmdMaskStatusLabel');
            view.DmdMaskStatusLabel.Layout.Column = [3 4];
            view.DmdMaskStatusLabel.Layout.Row = 6;
            maskHint = uilabel(maskGrid, 'Text', ...
                ['Each ROI keeps separate masks. Optional inter-ROI OFF images ', ...
                 'are part of the repeated sequence; trailing block padding is ', ...
                 'a separate Advanced setting.'], ...
                'WordWrap', 'on', 'FontColor', [0.30 0.30 0.30]);
            maskHint.Layout.Row = 7;
            maskHint.Layout.Column = [1 4];

            dmdPanel = uipanel(dmdModuleGrid, ...
                'Title', '3. Compile, Transfer & Playback');
            dmdGrid = uigridlayout(dmdPanel, [17 4]);
            dmdGrid.RowHeight = {30,30,30,30,30,30,190,32,30,30,34,30,42,44,34,44,44};
            dmdGrid.ColumnWidth = {112,'1x',116,'1x'};
            dmdGrid.Padding = [6 5 6 5];
            dmdState = uigridlayout(dmdGrid, [1 2]);
            dmdState.Layout.Column = [1 2];
            dmdState.ColumnWidth = {22,'1x'};
            dmdState.Padding = [0 0 0 0];
            view.DmdLamp = uilamp(dmdState, 'Color', [0.65 0.65 0.65], ...
                'Tag', 'DmdLamp');
            uilabel(dmdState, 'Text', 'DMD hardware', 'FontWeight', 'bold');
            connectDmdButton = uibutton(dmdGrid, 'push', 'Text', 'Connect DMD', ...
                'Tag', 'ConnectDmdButton', 'ButtonPushedFcn', @(~,~) callbacks.connectDmd());
            connectDmdButton.Layout.Row = 1;
            connectDmdButton.Layout.Column = [3 4];
            uilabel(dmdGrid, 'Text', 'Use DMD');
            view.LightStimDmdSwitch = uiswitch(dmdGrid, 'slider', ...
                'Items', {'OFF','ON'}, 'Value', 'ON', 'Tag', 'LightStimDmdSwitch', ...
                'ValueChangedFcn', @(source,event) callbacks.lightStimulusSettingEdited( ...
                    'DmdEnabled', event.PreviousValue, source.Value));
            uilabel(dmdGrid, 'Text', 'Trigger mode');
            view.DmdTriggerModeDropDown = uidropdown(dmdGrid, ...
                'Items', {'Internal','External IN1'}, 'Value', 'Internal', ...
                'Tag', 'DmdTriggerModeDropDown', ...
                'Tooltip', ['Internal: DMD loops itself. External IN1: each ', ...
                    'configured input edge advances one binary frame.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdTriggerModeChanged(event.PreviousValue, source.Value));
            uilabel(dmdGrid, 'Text', 'Pattern');
            view.LightStimDmdPatternDropDown = uidropdown(dmdGrid, ...
                'Items', {'ALL OFF','ALL ON','Folder'}, 'Value', 'ALL OFF', ...
                'Tag', 'LightStimDmdPatternDropDown', ...
                'ValueChangedFcn', @(source,event) callbacks.dmdPatternSettingEdited( ...
                    'PatternSelection', event.PreviousValue, source.Value));
            uilabel(dmdGrid, 'Text', 'Playback');
            view.LightStimDmdLoopSwitch = uiswitch(dmdGrid, 'slider', ...
                'Items', {'Single','Loop'}, 'Value', 'Loop', ...
                'Tag', 'LightStimDmdLoopSwitch', ...
                'ValueChangedFcn', @(source,event) callbacks.lightStimulusSettingEdited( ...
                    'DmdPlayback', event.PreviousValue, source.Value));
            uilabel(dmdGrid, 'Text', 'Pattern folder');
            view.DmdPatternFolderField = uieditfield(dmdGrid, 'text', ...
                'Value', '', 'Tag', 'DmdPatternFolderField', ...
                'ValueChangedFcn', @(source,event) callbacks.dmdPatternSettingEdited( ...
                    'PatternFolder', event.PreviousValue, source.Value));
            uibutton(dmdGrid, 'push', 'Text', 'Browse', ...
                'Tag', 'BrowseDmdPatternButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.browseDmdPatternFolder());
            uibutton(dmdGrid, 'push', 'Text', 'Load Pattern', ...
                'Tag', 'LoadDmdPatternButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.loadDmdPattern());
            uilabel(dmdGrid, 'Text', 'Start position');
            view.DmdStartPositionField = uieditfield(dmdGrid, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 1, ...
                'Tag', 'DmdStartPositionField', ...
                'ValueChangedFcn', @(source,event) callbacks.dmdPatternSettingEdited( ...
                    'StartPosition', event.PreviousValue, source.Value));
            uilabel(dmdGrid, 'Text', 'Frames / block');
            view.DmdPictureCountField = uieditfield(dmdGrid, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 16, ...
                'Editable', 'off', 'Tag', 'DmdPictureCountField');
            uilabel(dmdGrid, 'Text', 'DMD offset vs Camera START (s)');
            view.DmdTriggerDelayField = uieditfield(dmdGrid, 'numeric', ...
                'Limits', [-Inf Inf], 'Value', 0, ...
                'Tag', 'DmdTriggerDelayField', ...
                'Tooltip', ['Signed time from Camera START to the first IN1 ', ...
                    'rising edge. Zero starts with the camera; negative starts earlier.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdTriggerGeneratorSettingEdited('FirstTriggerDelay', ...
                    event.PreviousValue, source.Value));
            uilabel(dmdGrid, 'Text', 'Trigger high (ms)');
            view.LightStimDmdPulseField = uieditfield(dmdGrid, 'numeric', ...
                'Limits', [0.005 Inf], 'Value', 1, ...
                'Tag', 'LightStimDmdPulseField', ...
                'Tooltip', ['Time IN1 remains high before returning low. ', ...
                    'This is not camera exposure time.'], ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdTriggerGeneratorSettingEdited( ...
                    'TriggerHighMilliseconds', event.PreviousValue, source.Value));
            view.DmdTriggerTable = uitable(dmdGrid, ...
                'Data', [0 0 0; 0 1 1; 0.001 1 1; 0.001 0 1; 0.1 0 1], ...
                'ColumnName', {'Time (s)','IN1 state (0/1)','Expected frame'}, ...
                'ColumnEditable', [true true true], ...
                'ColumnWidth', {'auto','auto','auto'}, 'RowName', 'numbered', ...
                'Tag', 'DmdTriggerTable', ...
                'CellSelectionCallback', @(~,event) ...
                    callbacks.waveformTableSelectionChanged('IN1', event), ...
                'CellEditCallback', @(source,event) ...
                    callbacks.dmdTriggerTableEdited(source, event));
            view.DmdTriggerTable.Layout.Row = 7;
            view.DmdTriggerTable.Layout.Column = [1 4];
            in1Buttons = uigridlayout(dmdGrid, [1 5]);
            in1Buttons.Layout.Row = 8;
            in1Buttons.Layout.Column = [1 4];
            in1Buttons.ColumnWidth = {'1x','1x','1x','1x','1x'};
            in1Buttons.Padding = [0 0 0 0];
            uibutton(in1Buttons, 'push', 'Text', 'Add', ...
                'Tag', 'AddDmdTriggerEdgeButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.addDmdTriggerEdge());
            uibutton(in1Buttons, 'push', 'Text', 'Insert', ...
                'Tag', 'InsertDmdTriggerEdgeButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.insertDmdTriggerEdge());
            uibutton(in1Buttons, 'push', 'Text', 'Delete', ...
                'Tag', 'DeleteDmdTriggerEdgeButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.deleteDmdTriggerEdges());
            uibutton(in1Buttons, 'push', 'Text', 'Clear', ...
                'Tag', 'ClearDmdTriggerTableButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.clearDmdTriggerTable());
            uibutton(in1Buttons, 'push', 'Text', 'Generate', ...
                'Tag', 'GenerateDmdTriggerTableButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.resetDmdTriggerTableForPattern( ...
                    view.DmdPictureCountField.Value));
            uilabel(dmdGrid, 'Text', 'Trigger period (s)', ...
                'Tooltip', 'Time from one IN1 rising edge to the next.');
            view.DmdTriggerPeriodField = uieditfield(dmdGrid, 'numeric', ...
                'Limits', [eps Inf], 'Value', 0.1, ...
                'Tag', 'DmdTriggerPeriodField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdTriggerGeneratorSettingEdited('TriggerPeriod', ...
                    event.PreviousValue, source.Value));
            in1CycleLabel = uilabel(dmdGrid, 'Text', 'Pattern cycles', ...
                'Tooltip', ['May be fractional. Cycles equal total IN1 triggers ', ...
                    'divided by binary frames per pattern.']);
            in1CycleLabel.Layout.Row = 9;
            in1CycleLabel.Layout.Column = 3;
            view.DmdTriggerRepeatField = uieditfield(dmdGrid, 'numeric', ...
                'Limits', [0 Inf], 'Value', 1, ...
                'Tag', 'DmdTriggerRepeatField', ...
                'ValueChangedFcn', @(source,event) ...
                    callbacks.dmdTriggerGeneratorSettingEdited('SequenceCycles', ...
                    event.PreviousValue, source.Value));
            view.DmdTriggerRepeatField.Layout.Row = 9;
            view.DmdTriggerRepeatField.Layout.Column = 4;
            uilabel(dmdGrid, 'Text', 'Total IN1 triggers');
            view.DmdTotalTriggerField = uieditfield(dmdGrid, 'numeric', ...
                'Limits', [0 Inf], 'RoundFractionalValues', 'on', 'Value', 16, ...
                'Tag', 'DmdTotalTriggerField', ...
                'Tooltip', ['Editable integer trigger count. Editing it updates ', ...
                    'Pattern cycles, including transparent fractional cycles.'], ...
                'ValueChangedFcn', @(source,event) callbacks.dmdTotalTriggerEdited( ...
                    event.PreviousValue, source.Value));
            view.DmdTotalTriggerField.Layout.Row = 10;
            view.DmdTotalTriggerField.Layout.Column = [2 4];
            view.DmdPlayButton = uibutton(dmdGrid, 'push', ...
                'Text', 'PLAY (Internal)', ...
                'Tag', 'PreviewDmdPatternButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.previewDmdPattern());
            view.DmdPlayButton.Layout.Row = 11;
            view.DmdPlayButton.Layout.Column = [1 2];
            view.DmdPauseButton = uibutton(dmdGrid, 'push', ...
                'Text', 'PAUSE / RESUME', 'Tag', 'PauseDmdButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.pauseDmd());
            view.DmdPauseButton.Layout.Row = 11;
            view.DmdPauseButton.Layout.Column = 3;
            stopDmdButton = uibutton(dmdGrid, 'push', 'Text', 'STOP / RESET', ...
                'Tag', 'StopDmdButton', 'ButtonPushedFcn', @(~,~) callbacks.stopDmd());
            stopDmdButton.Layout.Row = 11;
            stopDmdButton.Layout.Column = 4;
            patternState = uigridlayout(dmdGrid, [1 2]);
            patternState.Layout.Row = 12;
            patternState.Layout.Column = [1 4];
            patternState.ColumnWidth = {22, '1x'};
            patternState.Padding = [0 0 0 0];
            view.DmdPatternLamp = uilamp(patternState, ...
                'Color', [0.65 0.65 0.65], 'Tag', 'DmdPatternLamp');
            view.DmdPatternStateLabel = uilabel(patternState, ...
                'Text', 'PATTERN NOT LOADED — Load Pattern before Play', ...
                'FontWeight', 'bold', 'Tag', 'DmdPatternStateLabel');
            patternHint = uilabel(dmdGrid, 'Text', ...
                ['Generate writes the full pulse sequence: Trigger low = period − high. ', ...
                 'Expected frame is editable audit metadata; DMD pages still advance sequentially.'], ...
                'FontColor', [0.15 0.32 0.50]);
            patternHint.Layout.Row = 13;
            patternHint.Layout.Column = [1 4];
            view.DmdPatternSummaryLabel = uilabel(dmdGrid, ...
                'Text', 'Not compiled.', 'WordWrap', 'on', ...
                'Tag', 'DmdPatternSummaryLabel', ...
                'FontColor', [0.15 0.32 0.50]);
            view.DmdPatternSummaryLabel.Layout.Row = 14;
            view.DmdPatternSummaryLabel.Layout.Column = [1 4];
            view.DmdRecoverPortButton = uibutton(dmdGrid, 'push', ...
                'Text', 'Recover UDP 6002...', ...
                'Tag', 'RecoverDmdPortButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.recoverDmdHostPort());
            view.DmdRecoverPortButton.Layout.Row = 15;
            view.DmdRecoverPortButton.Layout.Column = 1;
            view.DmdAdminRecoverButton = uibutton(dmdGrid, 'push', ...
                'Text', 'Fix -99 (Admin)...', ...
                'Tag', 'DmdAdminRecoverButton', ...
                'Tooltip', 'Runs the project-owned 6002PortKill.bat after confirmation and Windows UAC.', ...
                'ButtonPushedFcn', @(~,~) callbacks.runDmdAdminPortKill());
            view.DmdAdminRecoverButton.Layout.Row = 15;
            view.DmdAdminRecoverButton.Layout.Column = [2 3];
            recoverHint = uilabel(dmdGrid, 'Text', ...
                'Only for UDP bind error -99.', ...
                'FontColor', [0.65 0.25 0.05]);
            recoverHint.Layout.Row = 15;
            recoverHint.Layout.Column = 4;
            view.DmdStatusLabel = uilabel(dmdGrid, ...
                'Text', 'DMD is idle. Connect hardware, load a pattern, then Play.', ...
                'WordWrap', 'on', 'Tag', 'DmdStatusLabel', ...
                'FontColor', [0.25 0.25 0.25]);
            view.DmdStatusLabel.Layout.Row = [16 17];
            view.DmdStatusLabel.Layout.Column = [1 4];

            safetyPanel = uipanel(grid, 'Title', 'Synchronization & Safety');
            safetyGrid = uigridlayout(safetyPanel, [3 1]);
            safetyGrid.RowHeight = {42,34,34};
            safetyGrid.Padding = [6 5 6 5];
            uilabel(safetyGrid, 'Text', ...
                ['DAQ drives laser TTL and DMD IN1. DMD requires 5 V CMOS and common ground. ', ...
                 'OUT1 feedback remains unverified until a DAQ input is configured.'], ...
                'WordWrap', 'on', 'FontColor', [0.65 0.25 0.05]);
            buttons = uigridlayout(safetyGrid, [1 2]);
            buttons.RowHeight = {28};
            buttons.ColumnWidth = {'1x','1x'};
            buttons.Padding = [0 0 0 0];
            view.LightStimArmButton = uibutton(buttons, 'push', ...
                'Text', 'Arm Light Stimulus', 'Tag', 'LightStimArmButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.armLightStimulus());
            view.LightStimDisarmButton = uibutton(buttons, 'push', ...
                'Text', 'Disarm', 'Enable', 'off', ...
                'Tag', 'LightStimDisarmButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.disarmLightStimulus('user'));
            view.LightStimFrameworkStatusLabel = uilabel(safetyGrid, ...
                'Text', 'Ready to configure; no light stimulus is armed.', ...
                'Tag', 'LightStimulusStatusLabel');
        end
    end
end
