classdef VisualStimulusPanel < handle
    %VISUALSTIMULUSPANEL Owns panel controls and event bindings.
    % Receives only its parent, display values and explicit callbacks.
    properties
        VisualArmButton
        VisualDisarmButton
        VisualDurationField
        VisualFrequencyField
        VisualISIField
        VisualPlayButton
        VisualPreviewAngleField
        VisualPreviewModeDropDown
        VisualProgramDropDown
        VisualRepeatsField
        VisualScreenCloseButton
        VisualScreenField
        VisualScreenLamp
        VisualScreenSetupButton
        VisualScreenStatusLabel
        VisualSequenceField
        VisualSequenceLabel
        VisualStopPlaybackButton
        VisualSummaryLabel
        LedTab
    end

    methods
        function view = VisualStimulusPanel(parent, callbacks)
            grid = uigridlayout(parent, [1 1]);
            grid.RowHeight = {'1x'};
            grid.Padding = [8 8 8 8];
            grid.RowSpacing = 8;
            if isprop(grid, 'Scrollable')
                grid.Scrollable = 'on';
            end

            visualTabs = uitabgroup(grid, 'Tag', 'VisualStimulusModeTabs');
            ptbTab = uitab(visualTabs, 'Title', 'Screen / PTB');
            ledTab = uitab(visualTabs, 'Title', 'LED Flicker / DAQ');

            % Components parented directly to a uitab retain MATLAB's small
            % default Position.  A one-cell grid makes the PTB panel fill the
            % complete tab viewport and resize with the desktop window.
            ptbTabGrid = uigridlayout(ptbTab, [1 1]);
            ptbTabGrid.RowHeight = {'1x'};
            ptbTabGrid.ColumnWidth = {'1x'};
            ptbTabGrid.Padding = [0 0 0 0];
            ptbTabGrid.Tag = 'VisualPtbTabGrid';
            visualPanel = uipanel(ptbTabGrid, 'Title', 'Visual Stimulus — Psychtoolbox', ...
                'Tag', 'VisualStimulusPanel');
            visualGrid = uigridlayout(visualPanel, [11 1]);
            visualGrid.RowHeight = ...
                {30,102,32,48,32,32,32,44,48,32,38};
            visualGrid.Padding = [6 5 6 5];
            top = uigridlayout(visualGrid, [1 2]);
            top.ColumnWidth = {22,'1x'};
            top.Padding = [0 0 0 0];
            uilamp(top, 'Color', [0.65 0.65 0.65], 'Tag', 'VisualSetupLamp');
            uilabel(top, 'Text', ...
                'Configure, then Arm. ARMED means the next Record includes this stimulus.', ...
                'FontColor', [0.2 0.35 0.5]);

            callbacks.createModuleMethodPanel(visualGrid, 'visual_ptb', ...
                'PTB Method');

            programRow = uigridlayout(visualGrid, [1 2]);
            programRow.ColumnWidth = {54,'1x'};
            programRow.Padding = [0 0 0 0];
            uilabel(programRow, 'Text', 'Program');
            view.VisualProgramDropDown = uidropdown(programRow, ...
                'Items', {'Drifting grating','Random drifting grating', ...
                    'Gray-Blue-Gray','Gray-White-Gray-Black','Flash', ...
                    'Contrast Reverse'}, ...
                'ItemsData', {'drifting_grating','random_drifting_grating', ...
                    'gray_blue_gray','gray_white_gray_black','flash', ...
                    'contrast_reverse'}, ...
                'Value', 'drifting_grating', 'Tag', 'VisualProgramDropDown', ...
                'ValueChangedFcn', @(source,event) callbacks.visualProgramChanged( ...
                    event.PreviousValue, source.Value));
            screenPanel = uipanel(visualGrid, 'Title', 'PTB Screen', ...
                'Tag', 'VisualScreenPanel');
            screenRow = uigridlayout(screenPanel, [1 7]);
            screenRow.ColumnWidth = {46,64,86,86,22,88,'1x'};
            screenRow.Padding = [5 2 5 2];
            screenRow.ColumnSpacing = 5;
            uilabel(screenRow, 'Text', 'Index');
            view.VisualScreenField = uieditfield(screenRow, 'numeric', ...
                'Limits', [0 Inf], 'RoundFractionalValues', 'on', 'Value', 1, ...
                'Tag', 'VisualScreenField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'ScreenIndex', event.PreviousValue, source.Value));
            view.VisualScreenSetupButton = uibutton(screenRow, 'push', ...
                'Text', 'Set Screen', 'Tag', 'VisualScreenSetupButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.setupVisualScreen());
            view.VisualScreenCloseButton = uibutton(screenRow, 'push', ...
                'Text', 'Close Screen', 'Enable', 'off', ...
                'Tag', 'VisualScreenCloseButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.closeVisualScreen('user'));
            view.VisualScreenLamp = uilamp(screenRow, ...
                'Color', [0.65 0.65 0.65], 'Tag', 'VisualScreenLamp');
            uilabel(screenRow, 'Text', 'PTB Screen');
            view.VisualScreenStatusLabel = uilabel(screenRow, ...
                'Text', 'NOT SET — set before Play or Arm', ...
                'FontColor', [0.72 0.18 0.12], ...
                'Tag', 'VisualScreenStatusLabel');

            timingRow = uigridlayout(visualGrid, [1 4]);
            timingRow.ColumnWidth = {74,'1x',82,'1x'};
            timingRow.Padding = [0 0 0 0];
            uilabel(timingRow, 'Text', 'Duration (s)');
            view.VisualDurationField = uieditfield(timingRow, 'numeric', ...
                'Limits', [0.001 Inf], 'Value', 2, 'Tag', 'VisualDurationField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'DurationSeconds', event.PreviousValue, source.Value));
            uilabel(timingRow, 'Text', 'Temporal Hz');
            view.VisualFrequencyField = uieditfield(timingRow, 'numeric', ...
                'Limits', [0.001 Inf], 'Value', 2, 'Tag', 'VisualFrequencyField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'FrequencyHz', event.PreviousValue, source.Value));

            repeatRow = uigridlayout(visualGrid, [1 4]);
            repeatRow.ColumnWidth = {48,'1x',54,'1x'};
            repeatRow.Padding = [0 0 0 0];
            uilabel(repeatRow, 'Text', 'ISI (s)');
            view.VisualISIField = uieditfield(repeatRow, 'numeric', ...
                'Limits', [0 Inf], 'Value', 1, 'Tag', 'VisualISIField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'ISISeconds', event.PreviousValue, source.Value));
            uilabel(repeatRow, 'Text', 'Repeats');
            view.VisualRepeatsField = uieditfield(repeatRow, 'numeric', ...
                'Limits', [1 Inf], 'RoundFractionalValues', 'on', 'Value', 1, ...
                'Tag', 'VisualRepeatsField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'Repeats', event.PreviousValue, source.Value));

            sequenceRow = uigridlayout(visualGrid, [1 2]);
            sequenceRow.ColumnWidth = {118,'1x'};
            sequenceRow.Padding = [0 0 0 0];
            view.VisualSequenceLabel = uilabel(sequenceRow, 'Text', 'Angles (deg)');
            view.VisualSequenceField = uieditfield(sequenceRow, 'text', ...
                'Value', '[0 45 90 135 180 225 270 315]', ...
                'Tag', 'VisualSequenceField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'Sequence', event.PreviousValue, source.Value));

            uilabel(visualGrid, 'Text', ...
                ['Set PTB Screen first. Start camera Preview before Play; an active ', ...
                 'Preview remains running while camera buttons are timing-locked. ', ...
                 'Playback needs no DAQ and is not hardware synchronized. ', ...
                 'Armed Acquisition: DAQ synchronized.'], ...
                'WordWrap', 'on', 'FontColor', [0.68 0.28 0.05]);
            view.VisualSummaryLabel = uilabel(visualGrid, 'Text', '', ...
                'WordWrap', 'on', 'Tag', 'VisualSummaryLabel');
            previewRow = uigridlayout(visualGrid, [1 4]);
            previewRow.ColumnWidth = {70,'1x',74,'1x'};
            previewRow.Padding = [0 0 0 0];
            uilabel(previewRow, 'Text', 'Play mode');
            view.VisualPreviewModeDropDown = uidropdown(previewRow, ...
                'Items', {'Loaded program','Fixed direction','Random one direction'}, ...
                'ItemsData', {'full','fixed','random'}, 'Value', 'full', ...
                'Tag', 'VisualPreviewModeDropDown', ...
                'ValueChangedFcn', @(source,event) callbacks.visualPreviewModeChanged( ...
                    event.PreviousValue, source.Value));
            uilabel(previewRow, 'Text', 'Angle (deg)');
            view.VisualPreviewAngleField = uieditfield(previewRow, 'numeric', ...
                'Value', 0, 'Enable', 'off', 'Tag', 'VisualPreviewAngleField', ...
                'ValueChangedFcn', @(source,event) callbacks.visualSettingEdited( ...
                    'PreviewFixedAngle', event.PreviousValue, source.Value));

            visualButtons = uigridlayout(visualGrid, [1 4]);
            visualButtons.ColumnWidth = {'1x','1x','1x','1x'};
            visualButtons.Padding = [0 0 0 0];
            view.VisualPlayButton = uibutton(visualButtons, 'push', ...
                'Text', 'Play Preview', 'Tag', 'VisualPlayButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.playVisualPreview());
            view.VisualStopPlaybackButton = uibutton(visualButtons, 'push', ...
                'Text', 'Stop Playback', 'Enable', 'off', ...
                'Tag', 'VisualStopPlaybackButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.stopVisualPreview());
            view.VisualArmButton = uibutton(visualButtons, 'push', ...
                'Text', 'Arm Visual Stimulus', 'Tag', 'VisualArmButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.armVisualStimulus());
            view.VisualDisarmButton = uibutton(visualButtons, 'push', ...
                'Text', 'Disarm', 'Enable', 'off', 'Tag', 'VisualDisarmButton', ...
                'ButtonPushedFcn', @(~,~) callbacks.disarmVisualStimulus('user'));

            view.LedTab = ledTab;
        end
    end
end
