classdef AcquisitionWorkerService
    %ACQUISITIONWORKERSERVICE Own cameras and BIN writers in another MATLAB.
    % The UI/PTB process communicates only through small control files.

    methods (Static)
        function run(configPath)
            configPath = string(configPath);
            config = jsondecode(fileread(configPath));
            addpath(string(config.app_root));
            controlFolder = string(config.control_folder);
            logger = zoulab.AppLogger(string(config.log_folder));
            loggerCleanup = onCleanup(@() logger.close()); %#ok<NASGU>
            if isfield(config, 'operator_id') && isfield(config, 'operator_name')
                logger.setIdentity(config.operator_id, config.operator_name);
            end
            if isfield(config, 'session_id')
                logger.setSession(config.session_id);
            end
            cameras = zoulab.CameraManager();
            cameraCleanup = onCleanup(@() cameras.release(logger)); %#ok<NASGU>
            recorder = [];
            armed = false;
            serviceStartedUtc = zoulab.BinInfo.utcNow();
            logger.log('INFO', 'ACQUISITION_WORKER_START', ...
                ['Config=%s | PID=%d | Cameras=%s | TriggerMode=%s | ', ...
                 'LightControl=none | DMDControl=none | PTBControl=none'], ...
                configPath, feature('getpid'), mat2str(config.cameras), ...
                string(config.trigger_mode));
            try
                cameras.Adaptor = string(config.adaptor);
                cameras.VideoFormats = string(config.video_formats);
                cameras.ROIs = zoulab.AcquisitionWorkerService.decodeRois( ...
                    config.rois);
                cameras.ExposureTimes = double(config.exposure_seconds(:).');
                cameras.Bins = double(config.bins(:).');
                indices = unique(double(config.cameras(:).'), 'stable');
                cameras.connect(indices, logger);

                frameSizes = {[], []};
                outputFolders = {"", ""};
                expectedFrames = zeros(1, 2);
                expectedFPS = nan(1, 2);
                cameraMetadata = {struct(), struct()};
                for position = 1:numel(indices)
                    cameraIndex = indices(position);
                    settings = cameras.getActualSettings(cameraIndex);
                    frameSizes{cameraIndex} = ...
                        [settings.ROI(4) settings.ROI(3)];
                    outputFolders{cameraIndex} = string( ...
                        config.output_folders{cameraIndex});
                    expectedFrames(cameraIndex) = double( ...
                        config.expected_frames(cameraIndex));
                    expectedFPS(cameraIndex) = double( ...
                        config.expected_fps(cameraIndex));
                    cameraMetadata{cameraIndex} = struct( ...
                        'logical_name', char(cameras.LogicalNames(cameraIndex)), ...
                        'serial', char(cameras.Serials(cameraIndex)), ...
                        'device_name', char(cameras.DeviceNames(cameraIndex)), ...
                        'format', settings.VideoFormat, ...
                        'roi_xywh', settings.ROI, ...
                        'bin', settings.Bin, ...
                        'exposure_seconds', settings.ExposureTime);
                end
                bufferPolicy = ...
                    zoulab.AcquisitionWorkerService.bufferPolicy(config, ...
                    indices, frameSizes);
                recorder = zoulab.BufferedBinRecorder(indices, ...
                    outputFolders, frameSizes, expectedFrames, expectedFPS, ...
                    logger, bufferPolicy, cameraMetadata);
                useExternal = strcmpi(string(config.trigger_mode), 'external');
                finiteTarget = isfield(config, 'frame_limit_mode') && ...
                    strcmpi(string(config.frame_limit_mode), 'finite');
                if finiteTarget
                    cameras.prepareFiniteAcquisition(indices, ...
                        expectedFrames(indices), useExternal, logger);
                else
                    cameras.prepareOpenEndedAcquisition(indices, ...
                        useExternal, logger);
                end
                armed = true;
                ready = struct( ...
                    'status', 'ready', ...
                    'pid', feature('getpid'), ...
                    'ready_utc', zoulab.BinInfo.utcNow(), ...
                    'service_started_utc', serviceStartedUtc, ...
                    'cameras', indices, ...
                    'trigger_mode', char(string(config.trigger_mode)), ...
                    'frame_limit_mode', char(zoulab.AcquisitionWorkerService.pick( ...
                        finiteTarget, "finite", "open_ended")), ...
                    'frame_sizes', {frameSizes}, ...
                    'expected_frames', expectedFrames, ...
                    'expected_fps', expectedFPS);
                zoulab.BinInfo.write(fullfile(controlFolder, ...
                    'worker_ready.json'), ready);
                logger.log('SUCCESS', 'ACQUISITION_WORKER_READY', ...
                    ['Cameras=%s | TriggerMode=%s | FrameLimitMode=%s | ', ...
                     'FrameSizes=%s | ExpectedFrames=%s'], mat2str(indices), ...
                    string(config.trigger_mode), ...
                    zoulab.AcquisitionWorkerService.pick( ...
                        finiteTarget, "finite", "open_ended"), ...
                    jsonencode(frameSizes(indices)), ...
                    mat2str(expectedFrames(indices)));

                acquisitionClock = tic;
                lastHealth = -Inf;
                lastControlCheck = -Inf;
                stopRequested = false;
                protectionStop = false;
                maxFramesAvailable = zeros(1, 2);
                while ~stopRequested
                    recorder.processMessages(0);
                    metrics = cameras.bufferedAcquisitionMetrics(indices);
                    maxFramesAvailable(indices) = max( ...
                        maxFramesAvailable(indices), [metrics.FramesAvailable]);
                    protectionStop = ...
                        zoulab.AcquisitionWorkerService.protectionRequired( ...
                        metrics, indices, frameSizes, bufferPolicy);
                    if protectionStop
                        logger.log('ERROR', ...
                            'IAT_BUFFER_80_PERCENT_PROTECTION_TRIGGERED', ...
                            ['FramesAvailable=%s | StopFraction=%.3f | ', ...
                             'AcquisitionStopped=1 | BufferedFramesWillDrain=1'], ...
                            mat2str([metrics.FramesAvailable]), ...
                            bufferPolicy.iat_stop_fraction);
                        stopRequested = true;
                    end
                    zoulab.AcquisitionWorkerService.drainAvailable( ...
                        cameras, recorder, indices, metrics, false, 2, logger);
                    elapsed = toc(acquisitionClock);
                    if elapsed - lastControlCheck >= 0.01
                        stopRequested = stopRequested || isfile(fullfile( ...
                            controlFolder, 'worker_stop.request.json'));
                        lastControlCheck = elapsed;
                    end
                    if elapsed - lastHealth >= 5
                        metrics = cameras.bufferedAcquisitionMetrics(indices);
                        logger.log('INFO', 'ACQUISITION_WORKER_HEALTH', ...
                            ['Elapsed=%.3f | FramesAcquired=%s | ', ...
                             'FramesAvailable=%s | Retrieved=%s | ', ...
                             'Written=%s | QueueBlocks=%s'], elapsed, ...
                            mat2str([metrics.FramesAcquired]), ...
                            mat2str([metrics.FramesAvailable]), ...
                            mat2str(recorder.RetrievedFrames(indices)), ...
                            mat2str(recorder.WrittenFrames(indices)), ...
                            mat2str(recorder.InFlightBlocks(indices)));
                        lastHealth = elapsed;
                    end
                    if elapsed > double(config.watchdog_seconds)
                        error('ZouLab:AcquisitionWorkerWatchdog', ...
                            'Worker watchdog expired after %.3f seconds.', elapsed);
                    end
                    pause(0.0005);
                end

                cameras.stopBufferedAcquisition(indices, logger, ...
                    'worker_stop_request');
                armed = false;
                zoulab.AcquisitionWorkerService.drainStopped( ...
                    cameras, recorder, indices, logger);
                streamManifest = recorder.finish();
                metrics = cameras.bufferedAcquisitionMetrics(indices);
                measuredFps = nan(1, numel(indices));
                for position = 1:numel(indices)
                    cameraIndex = indices(position);
                    span = recorder.LastTimestamp(cameraIndex) - ...
                        recorder.FirstTimestamp(cameraIndex);
                    if recorder.RetrievedFrames(cameraIndex) > 1 && span > 0
                        measuredFps(position) = ...
                            (recorder.RetrievedFrames(cameraIndex) - 1) / span;
                    end
                end
                result = struct( ...
                    'status', char(zoulab.AcquisitionWorkerService.statusText( ...
                        protectionStop)), ...
                    'service_started_utc', serviceStartedUtc, ...
                    'completed_utc', zoulab.BinInfo.utcNow(), ...
                    'elapsed_seconds', toc(acquisitionClock), ...
                    'cameras', indices, ...
                    'frames_acquired', [metrics.FramesAcquired], ...
                    'frames_retrieved', recorder.RetrievedFrames(indices), ...
                    'frames_written', recorder.WrittenFrames(indices), ...
                    'metadata_measured_fps', measuredFps, ...
                    'max_frames_available', maxFramesAvailable(indices), ...
                    'stream_manifest', streamManifest, ...
                    'worker_log', char(logger.FilePath));
                resultPath = fullfile(controlFolder, 'worker_result.mat');
                save(resultPath, 'result', '-v7.3');
                zoulab.BinInfo.write(fullfile(controlFolder, ...
                    'worker_complete.json'), rmfield(result, 'stream_manifest'));
                logger.log('SUCCESS', 'ACQUISITION_WORKER_COMPLETE', ...
                    ['Status=%s | FramesAcquired=%s | Retrieved=%s | ', ...
                     'Written=%s | MetadataFPS=%s | ', ...
                     'MaxFramesAvailable=%s | Result=%s'], ...
                    result.status, mat2str(result.frames_acquired), ...
                    mat2str(result.frames_retrieved), ...
                    mat2str(result.frames_written), ...
                    mat2str(result.metadata_measured_fps), ...
                    mat2str(result.max_frames_available), resultPath);
            catch ME
                logger.logException('ACQUISITION_WORKER_FAILED', ME);
                if armed
                    try
                        cameras.stopBufferedAcquisition(indices, logger, ...
                            'worker_error_preserve_partial');
                    catch stopError
                        logger.logException('WORKER_CAMERA_STOP_FAILED', stopError);
                    end
                end
                if ~isempty(recorder) && ~recorder.Closed
                    try
                        zoulab.AcquisitionWorkerService.drainStopped( ...
                            cameras, recorder, indices, logger);
                        streamManifest = recorder.finish();
                        partialPath = fullfile(controlFolder, ...
                            'worker_partial_manifest.mat');
                        save(partialPath, 'streamManifest', '-v7.3');
                    catch preserveError
                        logger.logException('WORKER_PARTIAL_PRESERVE_FAILED', ...
                            preserveError);
                    end
                end
                errorValue = struct( ...
                    'status', 'error', ...
                    'failed_utc', zoulab.BinInfo.utcNow(), ...
                    'identifier', ME.identifier, ...
                    'message', ME.message, ...
                    'worker_log', char(logger.FilePath), ...
                    'partial_preservation_attempted', ~isempty(recorder));
                zoulab.BinInfo.write(fullfile(controlFolder, ...
                    'worker_error.json'), errorValue);
                rethrow(ME);
            end
        end
    end

    methods (Static, Access = private)
        function rois = decodeRois(value)
            rois = {[896 896 512 512], [896 896 512 512]};
            if iscell(value)
                for index = 1:min(2, numel(value))
                    rois{index} = double(value{index}(:).');
                end
            elseif isnumeric(value) && size(value, 1) == 2
                rois = {double(value(1, :)), double(value(2, :))};
            else
                error('ZouLab:WorkerRoiConfigInvalid', ...
                    'Worker ROIs must decode as two ROI rows or cells.');
            end
        end

        function policy = bufferPolicy(config, indices, frameSizes)
            queueBytes = 0;
            for cameraIndex = indices
                queueBytes = queueBytes + ...
                    zoulab.BufferedBinRecorder.MaxInFlightBlocksPerCamera * ...
                    zoulab.BufferedBinRecorder.BlockFrames * ...
                    prod(frameSizes{cameraIndex}) * 2;
            end
            availableBytes = Inf;
            try
                memoryInfo = memory;
                availableBytes = double(memoryInfo.MemAvailableAllArrays);
            catch
            end
            policy = zoulab.BufferedBinRecorder.computeIatBufferPolicy( ...
                availableBytes, queueBytes);
            if isfield(config, 'iat_stop_fraction') && ...
                    isfinite(double(config.iat_stop_fraction))
                fraction = double(config.iat_stop_fraction);
                policy.iat_stop_fraction = fraction;
                policy.iat_stop_bytes = fraction * policy.iat_capacity_bytes;
            end
        end

        function value = protectionRequired(metrics, indices, frameSizes, policy)
            bytesPerFrame = zeros(1, numel(indices));
            for position = 1:numel(indices)
                bytesPerFrame(position) = prod(frameSizes{indices(position)}) * 2;
            end
            pressure = zoulab.BufferedBinRecorder.computeIatPressure( ...
                [metrics.FramesAvailable], bytesPerFrame, policy);
            value = any([metrics.Running]) && pressure.stop_required;
        end

        function drainAvailable(cameras, recorder, indices, metrics, ...
                includePartial, maxBlocks, logger)
            for position = 1:numel(indices)
                cameraIndex = indices(position);
                available = double(metrics(position).FramesAvailable);
                blocks = 0;
                while available > 0 && blocks < maxBlocks
                    if ~includePartial && available < ...
                            zoulab.BufferedBinRecorder.BlockFrames
                        break;
                    end
                    if ~recorder.canAccept(cameraIndex)
                        break;
                    end
                    take = min(available, ...
                        zoulab.BufferedBinRecorder.BlockFrames);
                    block = cameras.takeBufferedFrames(cameraIndex, take);
                    recorder.ingest(cameraIndex, block.Data, block.Times, ...
                        block.Metadata);
                    available = available - take;
                    blocks = blocks + 1;
                end
                if blocks == 0 && available >= ...
                        zoulab.BufferedBinRecorder.BlockFrames && ...
                        ~recorder.canAccept(cameraIndex)
                    logger.log('WARNING', 'WORKER_WRITER_BACKPRESSURE', ...
                        ['Camera=%d | FramesAvailable=%d | QueueBlocks=%d | ', ...
                         'IatContinuesBuffering=1'], cameraIndex, available, ...
                        recorder.InFlightBlocks(cameraIndex));
                end
            end
        end

        function drainStopped(cameras, recorder, indices, logger)
            drainClock = tic;
            while true
                recorder.processMessages(0);
                metrics = cameras.bufferedAcquisitionMetrics(indices);
                if all([metrics.FramesAvailable] == 0)
                    break;
                end
                zoulab.AcquisitionWorkerService.drainAvailable(cameras, ...
                    recorder, indices, metrics, true, 8, logger);
                if toc(drainClock) > 300
                    error('ZouLab:WorkerIatDrainTimeout', ...
                        'Worker could not drain stopped IAT buffers in 300 seconds.');
                end
                pause(0.0005);
            end
            logger.log('SUCCESS', 'WORKER_IAT_DRAIN_COMPLETE', ...
                'Cameras=%s | Retrieved=%s | Elapsed=%.6g', ...
                mat2str(indices), mat2str(recorder.RetrievedFrames(indices)), ...
                toc(drainClock));
        end

        function value = statusText(protectionStop)
            if protectionStop
                value = "iat_protection_stop";
            else
                value = "complete";
            end
        end

        function value = pick(condition, trueValue, falseValue)
            if condition
                value = trueValue;
            else
                value = falseValue;
            end
        end
    end
end
