classdef BinInfo
    %BININFO Read/write the self-describing sidecar for a headerless BIN file.

    methods (Static)
        function value = create(binPath, cameraIndex, segmentIndex, ...
                frameSize, frameCount, expectedFPS, recorderCreatedUtc, ...
                cameraMetadata)
            if nargin < 8 || isempty(cameraMetadata)
                cameraMetadata = struct();
            end
            binPath = string(binPath);
            frameSize = double(frameSize(:).');
            fileEntry = dir(binPath);
            if isempty(fileEntry)
                error('ZouLab:BinInfoFileMissing', ...
                    'Cannot create BIN info because the file is missing: %s', ...
                    binPath);
            end
            bytesPerFrame = prod(frameSize) * 2;
            expectedBytes = double(frameCount) * bytesPerFrame;
            if double(fileEntry.bytes) ~= expectedBytes
                error('ZouLab:BinInfoSizeMismatch', ...
                    ['BIN %s contains %.0f bytes; %.0f bytes are required for ', ...
                     '%d uint16 frames of size %s.'], binPath, ...
                    double(fileEntry.bytes), expectedBytes, frameCount, ...
                    mat2str(frameSize));
            end
            [~, name, extension] = fileparts(binPath);
            lifecycle = zoulab.BinInfo.fileLifecycle(binPath);
            storage = zoulab.BinInfo.storageNamespace(binPath);
            infoWrittenUtc = zoulab.BinInfo.utcNow();
            value = struct( ...
                'schema_version', '1.0.0', ...
                'kind', 'zoulab_headerless_uint16_movie', ...
                'bin_file_name', char(name + extension), ...
                'camera_index', double(cameraIndex), ...
                'segment_index', double(segmentIndex), ...
                'data_type', 'uint16', ...
                'bits_per_pixel', 16, ...
                'byte_order', 'ieee-le', ...
                'header_bytes', 0, ...
                'frame_order', ...
                    'MATLAB column-major [height width channel frame]', ...
                'dimensions_hwf', [frameSize double(frameCount)], ...
                'height', frameSize(1), ...
                'width', frameSize(2), ...
                'channels', 1, ...
                'frame_count', double(frameCount), ...
                'bytes_per_frame', bytesPerFrame, ...
                'file_size_bytes', double(fileEntry.bytes), ...
                'expected_fps', double(expectedFPS), ...
                'raw_transposed', false, ...
                'camera', cameraMetadata, ...
                'storage', storage, ...
                'timestamps_utc', struct( ...
                    'recorder_created', char(recorderCreatedUtc), ...
                    'bin_file_created', lifecycle.created_utc, ...
                    'bin_file_last_write', lifecycle.last_write_utc, ...
                    'info_written', infoWrittenUtc), ...
                'conversion', struct( ...
                    'status', 'not_requested', ...
                    'completed_utc', '', ...
                    'tiff_files', {{}}, ...
                    'error', ''), ...
                'reader_contract', zoulab.BinInfo.readerContract( ...
                    frameSize, frameCount));
        end

        function path = sidecarPath(binPath)
            binPath = string(binPath);
            [folder, name] = fileparts(binPath);
            path = string(fullfile(folder, name + ".info.json"));
        end

        function write(path, value)
            path = string(path);
            folder = string(fileparts(path));
            if strlength(folder) > 0 && ~exist(folder, 'dir')
                mkdir(folder);
            end
            temporaryPath = path + ".tmp";
            fid = fopen(temporaryPath, 'w', 'n', 'UTF-8');
            if fid < 0
                error('ZouLab:BinInfoOpenFailed', ...
                    'Cannot open BIN info temporary file: %s', temporaryPath);
            end
            cleanup = onCleanup(@() zoulab.BinInfo.closeFile(fid));
            fprintf(fid, '%s', jsonencode(value, PrettyPrint=true));
            fclose(fid);
            cleanup = []; %#ok<NASGU>
            [moved, message] = movefile(temporaryPath, path, 'f');
            if ~moved
                error('ZouLab:BinInfoCommitFailed', ...
                    'Cannot commit BIN info %s: %s', path, message);
            end
        end

        function [infos, binFiles, frameSize, totalFrames] = ...
                loadAndValidate(infoFiles)
            infoFiles = string(infoFiles(:).');
            if isempty(infoFiles)
                error('ZouLab:BinInfoInputEmpty', ...
                    'At least one BIN info file is required.');
            end
            infoCells = cell(1, numel(infoFiles));
            binFiles = strings(1, numel(infoFiles));
            totalFrames = 0;
            frameSize = [];
            for index = 1:numel(infoFiles)
                if ~isfile(infoFiles(index))
                    error('ZouLab:BinInfoMissing', ...
                        'BIN info file is missing: %s', infoFiles(index));
                end
                value = jsondecode(fileread(infoFiles(index)));
                zoulab.BinInfo.validateContract(value, infoFiles(index));
                thisSize = [double(value.height) double(value.width)];
                if isempty(frameSize)
                    frameSize = thisSize;
                elseif ~isequal(frameSize, thisSize)
                    error('ZouLab:BinInfoFrameSizeConflict', ...
                        'BIN info files describe different frame sizes.');
                end
                folder = string(fileparts(infoFiles(index)));
                binFiles(index) = string(fullfile(folder, ...
                    string(value.bin_file_name)));
                if ~isfile(binFiles(index))
                    error('ZouLab:BinConversionFileMissing', ...
                        'BIN file named by %s is missing: %s', ...
                        infoFiles(index), binFiles(index));
                end
                fileEntry = dir(binFiles(index));
                if double(fileEntry.bytes) ~= double(value.file_size_bytes) || ...
                        double(fileEntry.bytes) ~= double(value.frame_count) * ...
                        double(value.bytes_per_frame)
                    error('ZouLab:BinInfoSizeMismatch', ...
                        'BIN byte size no longer matches its info file: %s', ...
                        binFiles(index));
                end
                infoCells{index} = value;
                totalFrames = totalFrames + double(value.frame_count);
            end
            infos = [infoCells{:}];
        end

        function markConversion(infoFiles, status, tiffFiles, errorText)
            if nargin < 3
                tiffFiles = strings(1, 0);
            end
            if nargin < 4
                errorText = "";
            end
            infoFiles = string(infoFiles(:).');
            for index = 1:numel(infoFiles)
                value = jsondecode(fileread(infoFiles(index)));
                zoulab.BinInfo.validateContract(value, infoFiles(index));
                value.conversion = struct( ...
                    'status', char(string(status)), ...
                    'completed_utc', zoulab.BinInfo.utcNow(), ...
                    'tiff_files', {cellstr(string(tiffFiles(:).'))}, ...
                    'error', char(string(errorText)));
                value.timestamps_utc.info_written = ...
                    zoulab.BinInfo.utcNow();
                zoulab.BinInfo.write(infoFiles(index), value);
            end
        end

        function markVisualAlignment(infoFiles, alignment)
            infoFiles = string(infoFiles(:).');
            globalOffset = 0;
            selectedRange = double(alignment.applied_frame_range(:).');
            for index = 1:numel(infoFiles)
                value = jsondecode(fileread(infoFiles(index)));
                zoulab.BinInfo.validateContract(value, infoFiles(index));
                segmentFrames = double(value.frame_count);
                segmentGlobalRange = globalOffset + [1 segmentFrames];
                overlap = [max(selectedRange(1), segmentGlobalRange(1)), ...
                    min(selectedRange(2), segmentGlobalRange(2))];
                if any(~isfinite(overlap)) || overlap(2) < overlap(1)
                    localRange = [NaN NaN];
                    selectedFrames = 0;
                else
                    localRange = overlap - globalOffset;
                    selectedFrames = overlap(2) - overlap(1) + 1;
                end
                segmentAlignment = alignment;
                segmentAlignment.segment_global_frame_range = ...
                    segmentGlobalRange;
                segmentAlignment.segment_selected_local_frame_range = ...
                    localRange;
                segmentAlignment.segment_selected_frame_count = ...
                    selectedFrames;
                value.visual_alignment = segmentAlignment;
                value.timestamps_utc.info_written = ...
                    zoulab.BinInfo.utcNow();
                zoulab.BinInfo.write(infoFiles(index), value);
                globalOffset = globalOffset + segmentFrames;
            end
        end

        function value = updateForPhysicalCrop(value, contentPath, ...
                outputFrameCount, alignment, segmentCrop)
            outputFrameCount = double(outputFrameCount);
            if outputFrameCount < 1 || mod(outputFrameCount, 1) ~= 0
                error('ZouLab:BinPhysicalCropCountInvalid', ...
                    'A retained BIN segment must contain positive whole frames.');
            end
            frameSize = [double(value.height) double(value.width)];
            expectedBytes = outputFrameCount * prod(frameSize) * 2;
            entry = dir(contentPath);
            if isempty(entry) || double(entry.bytes) ~= expectedBytes
                error('ZouLab:BinPhysicalCropSizeMismatch', ...
                    ['Prepared BIN segment %s has %.0f bytes; %.0f bytes are ', ...
                     'required.'], contentPath, zoulab.BinInfo.entryBytes(entry), ...
                    expectedBytes);
            end
            if ~isfield(value, 'source_before_visual_crop')
                sourceAlignment = struct();
                if isfield(value, 'visual_alignment')
                    sourceAlignment = value.visual_alignment;
                end
                value.source_before_visual_crop = struct( ...
                    'frame_count', double(value.frame_count), ...
                    'file_size_bytes', double(value.file_size_bytes), ...
                    'dimensions_hwf', double(value.dimensions_hwf), ...
                    'timestamps_utc', value.timestamps_utc, ...
                    'visual_alignment', sourceAlignment);
            end
            value.frame_count = outputFrameCount;
            value.dimensions_hwf = [frameSize outputFrameCount];
            value.file_size_bytes = expectedBytes;
            value.reader_contract = zoulab.BinInfo.readerContract( ...
                frameSize, outputFrameCount);
            value.visual_alignment = alignment;
            value.visual_alignment.segment_source_global_frame_range = ...
                segmentCrop.source_global_frame_range;
            value.visual_alignment.segment_source_local_frame_range = ...
                segmentCrop.source_local_frame_range;
            value.visual_alignment.segment_stored_global_frame_range = ...
                segmentCrop.stored_global_frame_range;
            value.visual_alignment.segment_stored_frame_count = ...
                outputFrameCount;
            value.physical_crop = segmentCrop;
            lifecycle = zoulab.BinInfo.fileLifecycle(contentPath);
            value.timestamps_utc.bin_file_created = lifecycle.created_utc;
            value.timestamps_utc.bin_file_last_write = ...
                lifecycle.last_write_utc;
            value.timestamps_utc.physical_crop_completed = ...
                char(segmentCrop.completed_utc);
            value.timestamps_utc.info_written = zoulab.BinInfo.utcNow();
        end

        function value = utcNow()
            stamp = datetime('now', 'TimeZone', 'UTC', ...
                'Format', "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'");
            value = char(stamp);
        end
    end

    methods (Static, Access = private)
        function value = storageNamespace(binPath)
            cameraFolder = string(fileparts(binPath));
            cycleFolder = string(fileparts(cameraFolder));
            [~, cameraFolderName] = fileparts(cameraFolder);
            [~, cycleFolderName] = fileparts(cycleFolder);
            token = regexp(char(cycleFolderName), ...
                '^Cycle([0-9]+)$', 'tokens', 'once', 'ignorecase');
            cycleIndex = [];
            if ~isempty(token)
                cycleIndex = str2double(token{1});
            end
            [~, binName, binExtension] = fileparts(binPath);
            value = struct( ...
                'cycle_index', cycleIndex, ...
                'cycle_folder_name', char(cycleFolderName), ...
                'cycle_folder', char(cycleFolder), ...
                'camera_folder_name', char(cameraFolderName), ...
                'camera_folder', char(cameraFolder), ...
                'bin_file_name', char(string(binName) + string(binExtension)));
        end

        function value = readerContract(frameSize, frameCount)
            value = struct( ...
                'matlab', sprintf([ ...
                    'fid=fopen(file,''r'',''ieee-le''); ', ...
                    'x=fread(fid,[%d*%d Inf],''*uint16''); fclose(fid); ', ...
                    'movie=reshape(x,%d,%d,[]);'], ...
                    frameSize(1), frameSize(2), frameSize(1), ...
                    frameSize(2)), ...
                'python', sprintf([ ...
                    'movie=np.fromfile(file,dtype=''<u2'').reshape(', ...
                    '(%d,%d,%d),order=''F'')'], frameSize(1), ...
                    frameSize(2), frameCount));
        end

        function value = entryBytes(entry)
            if isempty(entry)
                value = 0;
            else
                value = double(entry(1).bytes);
            end
        end

        function validateContract(value, sourcePath)
            required = {'schema_version','kind','bin_file_name', ...
                'data_type','byte_order','header_bytes','height','width', ...
                'frame_count','bytes_per_frame','file_size_bytes'};
            for index = 1:numel(required)
                if ~isfield(value, required{index})
                    error('ZouLab:BinInfoFieldMissing', ...
                        'BIN info %s lacks required field %s.', ...
                        sourcePath, required{index});
                end
            end
            valid = strcmp(value.kind, 'zoulab_headerless_uint16_movie') && ...
                strcmp(value.data_type, 'uint16') && ...
                strcmp(value.byte_order, 'ieee-le') && ...
                double(value.header_bytes) == 0 && ...
                double(value.height) >= 1 && double(value.width) >= 1 && ...
                double(value.frame_count) >= 0 && ...
                double(value.bytes_per_frame) == ...
                    double(value.height) * double(value.width) * 2;
            if ~valid
                error('ZouLab:BinInfoContractInvalid', ...
                    'BIN info contract is invalid: %s', sourcePath);
            end
        end

        function value = fileLifecycle(path)
            value = struct('created_utc', '', 'last_write_utc', '');
            try
                created = System.IO.File.GetCreationTimeUtc(char(path));
                modified = System.IO.File.GetLastWriteTimeUtc(char(path));
                format = "yyyy-MM-dd'T'HH:mm:ss.fff'Z'";
                value.created_utc = char(created.ToString(format));
                value.last_write_utc = char(modified.ToString(format));
            catch
                entry = dir(path);
                if isempty(entry)
                    return;
                end
                stamp = datetime(entry.datenum, 'ConvertFrom', 'datenum', ...
                    'TimeZone', 'local');
                stamp.TimeZone = 'UTC';
                stamp.Format = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
                value.created_utc = char(stamp);
                value.last_write_utc = char(stamp);
            end
        end

        function closeFile(fid)
            try
                fclose(fid);
            catch
            end
        end
    end
end
