classdef BufferedBinRecorder < handle
    %BUFFEREDBINRECORDER Bounded per-camera FIFO writer for headerless uint16 BIN.

    properties (Constant)
        BlockFrames double = 64
        SegmentSeconds double = 60
        MaxInFlightBlocksPerCamera double = 256
        IatProtectionFraction double = 0.80
        MetadataDetailLogLimit double = 100
    end

    properties (SetAccess = private)
        CameraIndices double = zeros(1, 0)
        OutputFolders cell = {"", ""}
        FrameSizes cell = {[], []}
        ExpectedFrames double = [0 0]
        ExpectedFPS double = [NaN NaN]
        SegmentFrames double = [0 0]
        RetrievedFrames double = [0 0]
        EnqueuedFrames double = [0 0]
        WrittenFrames double = [0 0]
        InFlightBlocks double = [0 0]
        InFlightFrames double = [0 0]
        MaxInFlightBlocks double = [0 0]
        MaxInFlightFrames double = [0 0]
        NextBlockIndex double = [1 1]
        LastFrameNumber double = [NaN NaN]
        FirstTimestamp double = [NaN NaN]
        LastTimestamp double = [NaN NaN]
        MetadataErrorCount double = [0 0]
        MetadataUnavailableBlockCount double = [0 0]
        WriterBlockOrderErrorCount double = [0 0]
        BinFiles cell = {strings(1, 0), strings(1, 0)}
        BinFileFrameCounts cell = {zeros(1, 0), zeros(1, 0)}
        BinInfoFiles cell = {strings(1, 0), strings(1, 0)}
        RecorderCreatedUtc string = ""
        CameraMetadata cell = {struct(), struct()}
        IatBufferPolicy struct = struct( ...
            'memory_measurement_available', false, ...
            'available_memory_bytes', Inf, ...
            'writer_queue_payload_bytes', 0, ...
            'iat_capacity_bytes', Inf, ...
            'iat_stop_fraction', 0.80, ...
            'iat_stop_bytes', Inf)
        Closed logical = false
        CycleActive logical = false
        ResourcesReleased logical = false
    end

    properties (Access = private)
        Logger
        CommandQueues cell = {[], []}
        StatusQueue = []
        WriterFutures cell = {[], []}
        WriterReady logical = false(1, 2)
        WriterCycleReady logical = false(1, 2)
        WriterClosed logical = false(1, 2)
        WriterTerminated logical = false(1, 2)
        WriterErrors string = ["" ""]
        CloseRequested logical = false
        MetadataDetailLogs double = [0 0]
    end

    methods
        function obj = BufferedBinRecorder(cameraIndices, outputFolders, ...
                frameSizes, expectedFrames, expectedFPS, logger, ...
                iatBufferPolicy, cameraMetadata, preallocation, deferFirstCycle)
            if nargin < 7 || isempty(iatBufferPolicy)
                iatBufferPolicy = ...
                    zoulab.BufferedBinRecorder.computeIatBufferPolicy(Inf, 0);
            end
            if nargin < 8 || isempty(cameraMetadata)
                cameraMetadata = {struct(), struct()};
            end
            if nargin < 9
                preallocation = struct([]);
            end
            if nargin < 10
                deferFirstCycle = false;
            end
            obj.CameraIndices = unique(double(cameraIndices(:).'), 'stable');
            obj.Logger = logger;
            obj.StatusQueue = parallel.pool.PollableDataQueue;
            writerCreatesCommandQueue = verLessThan('matlab', '25.1');
            if writerCreatesCommandQueue
                queueOwnership = 'writer_creator_compatibility';
            else
                queueOwnership = 'any_destination';
            end
            for cameraIndex = obj.CameraIndices
                if writerCreatesCommandQueue
                    commandQueue = [];
                else
                    commandQueue = ...
                        parallel.pool.PollableDataQueue(Destination="any");
                    obj.CommandQueues{cameraIndex} = commandQueue;
                end
                obj.WriterFutures{cameraIndex} = parfeval(backgroundPool, ...
                    @zoulab.BufferedBinRecorder.writerLoop, 0, ...
                    commandQueue, obj.StatusQueue, ...
                    cameraIndex);
            end
            obj.waitForWritersReady(30);
            if ~deferFirstCycle
                obj.beginCycle(outputFolders, frameSizes, expectedFrames, ...
                    expectedFPS, iatBufferPolicy, cameraMetadata, preallocation);
            end
            obj.Logger.log('SUCCESS', 'BIN_WRITER_TASK_READY', ...
                ['Cameras=%s | WriterThreads=%d | ', ...
                 'CommandQueueOwnership=%s | MATLABRelease=%s | ', ...
                 'ReuseBoundary=all_cycles_in_one_record_task'], ...
                mat2str(obj.CameraIndices), numel(obj.CameraIndices), ...
                queueOwnership, version('-release'));
        end

        function beginCycle(obj, outputFolders, frameSizes, expectedFrames, ...
                expectedFPS, iatBufferPolicy, cameraMetadata, preallocation)
            if obj.ResourcesReleased
                error('ZouLab:BinWriterResourcesReleased', ...
                    'Cannot begin a Cycle after the Record writer task was released.');
            end
            if obj.CycleActive
                error('ZouLab:BinCycleAlreadyActive', ...
                    'Finish the current BIN Cycle before beginning another.');
            end
            if nargin < 6 || isempty(iatBufferPolicy)
                iatBufferPolicy = ...
                    zoulab.BufferedBinRecorder.computeIatBufferPolicy(Inf, 0);
            end
            if nargin < 7 || isempty(cameraMetadata)
                cameraMetadata = {struct(), struct()};
            end
            if nargin < 8
                preallocation = struct([]);
            end
            obj.OutputFolders = outputFolders;
            obj.FrameSizes = frameSizes;
            obj.ExpectedFrames = obj.expandCameraValues(expectedFrames, 0);
            obj.ExpectedFPS = obj.expandCameraValues(expectedFPS, NaN);
            obj.IatBufferPolicy = iatBufferPolicy;
            obj.CameraMetadata = cameraMetadata;
            obj.RecorderCreatedUtc = string(zoulab.BinInfo.utcNow());
            obj.resetCycleState();

            normalizedFolders = strings(1, numel(obj.CameraIndices));
            for position = 1:numel(obj.CameraIndices)
                cameraIndex = obj.CameraIndices(position);
                frameSize = double(obj.FrameSizes{cameraIndex}(:).');
                if numel(frameSize) ~= 2 || any(frameSize < 1) || ...
                        any(~isfinite(frameSize))
                    error('ZouLab:BinFrameSizeInvalid', ...
                        'Camera %d requires a finite [height width] frame size.', ...
                        cameraIndex);
                end
                folder = string(obj.OutputFolders{cameraIndex});
                if strlength(folder) == 0
                    error('ZouLab:BinOutputFolderMissing', ...
                        'Camera %d requires a nonempty output folder.', cameraIndex);
                end
                if ~exist(folder, 'dir')
                    mkdir(folder);
                end
                if isempty(preallocation)
                    zoulab.BufferedBinRecorder.assertEmptyRecordNamespace( ...
                        folder, cameraIndex);
                end
                normalizedFolders(position) = ...
                    zoulab.BufferedBinRecorder.normalizedPath(folder);
                fps = obj.ExpectedFPS(cameraIndex);
                if ~isfinite(fps) || fps <= 0
                    error('ZouLab:BinExpectedFPSInvalid', ...
                        'Camera %d requires a positive expected FPS.', cameraIndex);
                end
                obj.SegmentFrames(cameraIndex) = max(obj.BlockFrames, ...
                    round(obj.SegmentSeconds * fps));
            end
            if numel(unique(normalizedFolders)) ~= numel(normalizedFolders)
                error('ZouLab:BinOutputFolderCollision', ...
                    ['Each camera must own a different BIN output folder. ', ...
                     'Shared folders can mix camera or Cycle data.']);
            end

            % Only mutate persistent writers after every camera-specific
            % Cycle destination has passed validation. This prevents one
            % writer entering a new Cycle when another destination is bad.
            for position = 1:numel(obj.CameraIndices)
                cameraIndex = obj.CameraIndices(position);
                folder = string(obj.OutputFolders{cameraIndex});
                frameSize = double(obj.FrameSizes{cameraIndex}(:).');
                [paths, preallocatedFrames] = ...
                    obj.cyclePreallocation(cameraIndex, preallocation);
                obj.BinFiles{cameraIndex} = paths;
                send(obj.CommandQueues{cameraIndex}, struct( ...
                    'Type', "BEGIN_CYCLE", 'OutputFolder', char(folder), ...
                    'FrameSize', frameSize, ...
                    'SegmentFrames', obj.SegmentFrames(cameraIndex), ...
                    'PreallocatedPaths', paths, ...
                    'PreallocatedFrameCounts', preallocatedFrames));
            end
            obj.waitForCycleReady(30);
            obj.CycleActive = true;
            obj.Logger.log('SUCCESS', 'BIN_RECORDER_READY', ...
                ['Cameras=%s | BlockFrames=%d | SegmentSeconds=%g | ', ...
                 'QueueLimitBlocksPerCamera=%d | ExpectedFrames=%s | ', ...
                 'ExpectedFPS=%s | MetadataCheck=enabled | ', ...
                 'IatCapacityBytes=%s | IatStopBytes=%s | IatStopFraction=%.3f'], ...
                mat2str(obj.CameraIndices), obj.BlockFrames, ...
                obj.SegmentSeconds, obj.MaxInFlightBlocksPerCamera, ...
                mat2str(obj.ExpectedFrames(obj.CameraIndices)), ...
                mat2str(obj.ExpectedFPS(obj.CameraIndices)), ...
                zoulab.BufferedBinRecorder.numberText( ...
                    obj.IatBufferPolicy.iat_capacity_bytes), ...
                zoulab.BufferedBinRecorder.numberText( ...
                    obj.IatBufferPolicy.iat_stop_bytes), ...
                obj.IatBufferPolicy.iat_stop_fraction);
        end

        function delete(obj)
            if obj.ResourcesReleased
                return;
            end
            try
                obj.finishTask(5);
            catch
                obj.releaseWriterResources(true);
            end
        end

        function value = canAccept(obj, cameraIndex)
            obj.processMessages(0);
            value = obj.InFlightBlocks(cameraIndex) < ...
                obj.MaxInFlightBlocksPerCamera && ...
                strlength(obj.WriterErrors(cameraIndex)) == 0;
        end

        function assertWritersHealthy(obj, cameraIndices)
            if nargin < 2 || isempty(cameraIndices)
                cameraIndices = obj.CameraIndices;
            end
            cameraIndices = unique(double(cameraIndices(:).'), 'stable');
            obj.processMessages(0);
            errors = obj.WriterErrors(cameraIndices);
            if any(strlength(errors) > 0)
                error('ZouLab:BinWriterFailed', '%s', ...
                    strjoin(errors(strlength(errors) > 0), ' | '));
            end
        end

        function ingest(obj, cameraIndex, frameData, frameTimes, metadata)
            if obj.CloseRequested
                error('ZouLab:BinRecorderAlreadyClosing', ...
                    'Cannot enqueue Camera %d after recorder close was requested.', ...
                    cameraIndex);
            end
            obj.assertWritersHealthy(cameraIndex);
            if ~obj.canAccept(cameraIndex)
                error('ZouLab:BinWriterQueueFull', ...
                    ['Camera %d writer queue has reached %d blocks; acquisition ', ...
                     'cannot be preserved safely.'], cameraIndex, ...
                    obj.MaxInFlightBlocksPerCamera);
            end
            frameSize = obj.FrameSizes{cameraIndex};
            if ~isa(frameData, 'uint16')
                error('ZouLab:BinDataTypeInvalid', ...
                    'Camera %d record data must be uint16, not %s.', ...
                    cameraIndex, class(frameData));
            end
            frameCount = numel(frameTimes);
            if frameCount < 1 || size(frameData, 1) ~= frameSize(1) || ...
                    size(frameData, 2) ~= frameSize(2) || ...
                    numel(frameData) ~= prod(frameSize) * frameCount
                error('ZouLab:BinBlockShapeInvalid', ...
                    ['Camera %d block shape %s does not match [%d %d 1 %d].'], ...
                    cameraIndex, mat2str(size(frameData)), frameSize(1), ...
                    frameSize(2), frameCount);
            end
            frameData = reshape(frameData, frameSize(1), frameSize(2), 1, ...
                frameCount);
            frameTimes = double(frameTimes(:));
            [issues, sequence] = zoulab.BufferedBinRecorder.validateMetadataSequence( ...
                metadata, frameTimes, obj.LastFrameNumber(cameraIndex), ...
                obj.LastTimestamp(cameraIndex));
            obj.recordMetadataIssues(cameraIndex, issues, ...
                obj.NextBlockIndex(cameraIndex));
            if sequence.MetadataAvailable
                obj.LastFrameNumber(cameraIndex) = sequence.LastFrameNumber;
            else
                obj.MetadataUnavailableBlockCount(cameraIndex) = ...
                    obj.MetadataUnavailableBlockCount(cameraIndex) + 1;
            end
            if isfinite(sequence.LastTimestamp)
                if ~isfinite(obj.FirstTimestamp(cameraIndex))
                    obj.FirstTimestamp(cameraIndex) = sequence.FirstTimestamp;
                end
                obj.LastTimestamp(cameraIndex) = sequence.LastTimestamp;
            end

            message = struct( ...
                'Type', "DATA", ...
                'BlockIndex', obj.NextBlockIndex(cameraIndex), ...
                'Frames', frameCount, ...
                'FirstFrameNumber', sequence.FirstFrameNumber, ...
                'LastFrameNumber', sequence.LastFrameNumber, ...
                'Data', frameData);
            send(obj.CommandQueues{cameraIndex}, message);
            obj.NextBlockIndex(cameraIndex) = ...
                obj.NextBlockIndex(cameraIndex) + 1;
            obj.RetrievedFrames(cameraIndex) = ...
                obj.RetrievedFrames(cameraIndex) + frameCount;
            obj.EnqueuedFrames(cameraIndex) = ...
                obj.EnqueuedFrames(cameraIndex) + frameCount;
            obj.InFlightBlocks(cameraIndex) = ...
                obj.InFlightBlocks(cameraIndex) + 1;
            obj.InFlightFrames(cameraIndex) = ...
                obj.InFlightFrames(cameraIndex) + frameCount;
            obj.MaxInFlightBlocks(cameraIndex) = max( ...
                obj.MaxInFlightBlocks(cameraIndex), ...
                obj.InFlightBlocks(cameraIndex));
            obj.MaxInFlightFrames(cameraIndex) = max( ...
                obj.MaxInFlightFrames(cameraIndex), ...
                obj.InFlightFrames(cameraIndex));
        end

        function processMessages(obj, waitSeconds)
            if isempty(obj.StatusQueue)
                return;
            end
            firstPoll = true;
            while true
                timeout = 0;
                if firstPoll
                    timeout = waitSeconds;
                end
                [message, received] = poll(obj.StatusQueue, timeout);
                firstPoll = false;
                if ~received
                    break;
                end
                cameraIndex = double(message.Camera);
                switch string(message.Type)
                    case "READY"
                        if isfield(message, 'CommandQueue') && ...
                                ~isempty(message.CommandQueue)
                            obj.CommandQueues{cameraIndex} = ...
                                message.CommandQueue;
                        end
                        obj.WriterReady(cameraIndex) = true;
                    case "CYCLE_READY"
                        obj.WriterCycleReady(cameraIndex) = true;
                    case "ACK"
                        obj.WrittenFrames(cameraIndex) = ...
                            obj.WrittenFrames(cameraIndex) + ...
                            double(message.Frames);
                        obj.InFlightBlocks(cameraIndex) = ...
                            obj.InFlightBlocks(cameraIndex) - 1;
                        obj.InFlightFrames(cameraIndex) = ...
                            obj.InFlightFrames(cameraIndex) - ...
                            double(message.Frames);
                    case "SEGMENT_CLOSED"
                        path = string(message.File);
                        if ~any(obj.BinFiles{cameraIndex} == path)
                            obj.BinFiles{cameraIndex}(end + 1) = path;
                        end
                        obj.Logger.log('SUCCESS', 'BIN_SEGMENT_CLOSED', ...
                            ['Camera=%d | Segment=%d | Frames=%d | Bytes=%.0f | ', ...
                             'File=%s'], cameraIndex, ...
                            double(message.SegmentIndex), ...
                            double(message.Frames), double(message.Bytes), path);
                    case "OVERFLOW_SEGMENT_OPENED"
                        obj.Logger.log('WARNING', ...
                            'BIN_OVERFLOW_SEGMENT_OPENED', ...
                            ['Camera=%d | Segment=%d | PlannedSegments=%d | ', ...
                             'File=%s | Folder=%s | ', ...
                             'SequentialGrowth=1 | PreallocationAttempted=0 | ', ...
                             'SameCycleNamespace=1'], cameraIndex, ...
                            double(message.SegmentIndex), ...
                            double(message.PlannedSegments), ...
                            string(message.File), string(message.Folder));
                    case "BLOCK_SEQUENCE_ERROR"
                        obj.WriterBlockOrderErrorCount(cameraIndex) = ...
                            obj.WriterBlockOrderErrorCount(cameraIndex) + 1;
                        obj.Logger.log('ERROR', 'BIN_WRITER_BLOCK_SEQUENCE_ERROR', ...
                            ['Camera=%d | ExpectedBlock=%d | ReceivedBlock=%d | ', ...
                             'AcquisitionContinues=1 | ReceivedOrderWritten=1'], ...
                            cameraIndex, double(message.ExpectedBlock), ...
                            double(message.ReceivedBlock));
                    case "CLOSED"
                        partFiles = string(message.Files);
                        fileFrameCounts = double(message.FileFrameCounts);
                        if numel(partFiles) ~= numel(fileFrameCounts)
                            error('ZouLab:BinWriterSegmentCountMismatch', ...
                                ['Camera %d closed with %d files but %d ', ...
                                 'segment frame counts.'], cameraIndex, ...
                                numel(partFiles), numel(fileFrameCounts));
                        end
                        bytesPerFrame = prod(obj.FrameSizes{cameraIndex}) * 2;
                        for fileIndex = 1:numel(partFiles)
                            zoulab.BufferedBinRecorder.setFileLength( ...
                                partFiles(fileIndex), ...
                                fileFrameCounts(fileIndex) * bytesPerFrame);
                        end
                        zoulab.BufferedBinRecorder.removeUnusedPreallocation( ...
                            string(message.PreallocatedPaths), partFiles);
                        files = zoulab.BufferedBinRecorder.publishPartFiles( ...
                            partFiles);
                        obj.BinFiles{cameraIndex} = files;
                        obj.BinFileFrameCounts{cameraIndex} = fileFrameCounts;
                        obj.WriterClosed(cameraIndex) = true;
                    case "TERMINATED"
                        obj.WriterTerminated(cameraIndex) = true;
                    case "ERROR"
                        obj.WriterErrors(cameraIndex) = ...
                            string(message.Identifier) + ": " + ...
                            string(message.Message);
                        obj.Logger.log('ERROR', 'BIN_WRITER_ERROR', ...
                            'Camera=%d | Error=%s', cameraIndex, ...
                            obj.WriterErrors(cameraIndex));
                end
            end
        end

        function requestClose(obj)
            if obj.CloseRequested
                return;
            end
            for cameraIndex = obj.CameraIndices
                send(obj.CommandQueues{cameraIndex}, ...
                    struct('Type', "CLOSE_CYCLE"));
            end
            obj.CloseRequested = true;
            obj.Logger.log('INFO', 'BIN_RECORDER_CLOSE_REQUESTED', ...
                'Cameras=%s | EnqueuedFrames=%s | InFlightFrames=%s', ...
                mat2str(obj.CameraIndices), ...
                mat2str(obj.EnqueuedFrames(obj.CameraIndices)), ...
                mat2str(obj.InFlightFrames(obj.CameraIndices)));
        end

        function manifest = finish(obj, timeoutSeconds)
            if nargin < 2
                timeoutSeconds = 180;
            end
            obj.requestClose();
            waitClock = tic;
            while ~all(obj.WriterClosed(obj.CameraIndices))
                obj.processMessages(0.25);
                errors = obj.WriterErrors(obj.CameraIndices);
                if any(strlength(errors) > 0)
                    error('ZouLab:BinWriterFailed', '%s', ...
                        strjoin(errors(strlength(errors) > 0), ' | '));
                end
                if toc(waitClock) > timeoutSeconds
                    error('ZouLab:BinWriterCloseTimeout', ...
                        'BIN writers did not close within %.1f seconds.', ...
                        timeoutSeconds);
                end
                drawnow limitrate;
            end
            obj.processMessages(0);
            if any(obj.InFlightBlocks(obj.CameraIndices) ~= 0) || ...
                    any(obj.WrittenFrames(obj.CameraIndices) ~= ...
                    obj.EnqueuedFrames(obj.CameraIndices))
                error('ZouLab:BinWriterCountMismatch', ...
                    ['BIN writer closed with mismatched counts: enqueued=%s, ', ...
                     'written=%s, blocks=%s.'], ...
                    mat2str(obj.EnqueuedFrames(obj.CameraIndices)), ...
                    mat2str(obj.WrittenFrames(obj.CameraIndices)), ...
                    mat2str(obj.InFlightBlocks(obj.CameraIndices)));
            end
            obj.Closed = true;
            obj.CycleActive = false;
            obj.writeBinInfoFiles();
            manifest = obj.manifest();
            obj.Logger.log('SUCCESS', 'BIN_RECORDER_COMPLETE', ...
                ['Cameras=%s | Retrieved=%s | Written=%s | ', ...
                 'MetadataErrors=%s | MetadataUnavailableBlocks=%s | ', ...
                 'WriterBlockOrderErrors=%s'], ...
                mat2str(obj.CameraIndices), ...
                mat2str(obj.RetrievedFrames(obj.CameraIndices)), ...
                mat2str(obj.WrittenFrames(obj.CameraIndices)), ...
                mat2str(obj.MetadataErrorCount(obj.CameraIndices)), ...
                mat2str(obj.MetadataUnavailableBlockCount(obj.CameraIndices)), ...
                mat2str(obj.WriterBlockOrderErrorCount(obj.CameraIndices)));
        end

        function finishTask(obj, timeoutSeconds)
            if nargin < 2
                timeoutSeconds = 30;
            end
            if obj.ResourcesReleased
                return;
            end
            if obj.CycleActive && ~obj.Closed
                obj.finish(timeoutSeconds);
            end
            for cameraIndex = obj.CameraIndices
                send(obj.CommandQueues{cameraIndex}, struct('Type', "SHUTDOWN"));
            end
            waitClock = tic;
            while ~all(obj.WriterTerminated(obj.CameraIndices))
                obj.processMessages(0.1);
                if toc(waitClock) > timeoutSeconds
                    error('ZouLab:BinWriterTaskCloseTimeout', ...
                        'BIN writer task did not terminate within %.1f seconds.', ...
                        timeoutSeconds);
                end
            end
            obj.releaseWriterResources(false);
            obj.Logger.log('SUCCESS', 'BIN_WRITER_TASK_RELEASED', ...
                ['Cameras=%s | FuturesDeleted=1 | QueuesCleared=1 | ', ...
                 'ReleaseBoundary=whole_record_task'], ...
                mat2str(obj.CameraIndices));
        end

        function result = manifest(obj)
            cameraResults = struct([]);
            for position = 1:numel(obj.CameraIndices)
                cameraIndex = obj.CameraIndices(position);
                cameraResult = struct( ...
                    'camera', cameraIndex, ...
                    'frame_size_hw', obj.FrameSizes{cameraIndex}, ...
                    'expected_frames', obj.ExpectedFrames(cameraIndex), ...
                    'retrieved_frames', obj.RetrievedFrames(cameraIndex), ...
                    'written_frames', obj.WrittenFrames(cameraIndex), ...
                    'expected_fps', obj.ExpectedFPS(cameraIndex), ...
                    'segment_frames', obj.SegmentFrames(cameraIndex), ...
                    'bin_files', {cellstr(obj.BinFiles{cameraIndex})}, ...
                    'bin_info_files', ...
                        {cellstr(obj.BinInfoFiles{cameraIndex})}, ...
                    'metadata_error_count', ...
                        obj.MetadataErrorCount(cameraIndex), ...
                    'metadata_unavailable_block_count', ...
                        obj.MetadataUnavailableBlockCount(cameraIndex), ...
                    'writer_block_order_error_count', ...
                        obj.WriterBlockOrderErrorCount(cameraIndex), ...
                    'last_frame_number', obj.LastFrameNumber(cameraIndex), ...
                    'first_timestamp_seconds', ...
                        obj.FirstTimestamp(cameraIndex), ...
                    'last_timestamp_seconds', obj.LastTimestamp(cameraIndex), ...
                    'max_writer_queue_blocks', ...
                        obj.MaxInFlightBlocks(cameraIndex), ...
                    'max_writer_queue_frames', ...
                        obj.MaxInFlightFrames(cameraIndex));
                if position == 1
                    cameraResults = cameraResult;
                else
                    cameraResults(position) = cameraResult;
                end
            end
            result = struct( ...
                'schema_version', '1.1.0', ...
                'format', 'headerless_uint16_bin', ...
                'endian', 'little', ...
                'frame_order', 'MATLAB column-major [height width channel frame]', ...
                'block_frames', obj.BlockFrames, ...
                'segment_seconds', obj.SegmentSeconds, ...
                'max_in_flight_blocks_per_camera', ...
                    obj.MaxInFlightBlocksPerCamera, ...
                'iat_buffer_policy', obj.IatBufferPolicy, ...
                'metadata_check', ...
                    'FrameNumber continuity and strictly increasing timestamps', ...
                'metadata_error_policy', ...
                    'log and continue acquisition; final integrity status is flagged', ...
                'recorder_created_utc', char(obj.RecorderCreatedUtc), ...
                'cameras', cameraResults);
        end
    end

    methods (Static)
        function result = prepareRecordFiles(cycleOutputFolders, ...
                cameraIndices, frameSizes, expectedFrames, expectedFPS, ...
                progressFcn)
            % Allocate every Cycle BIN before the Cycle schedule begins.
            if nargin < 6
                progressFcn = [];
            end
            cameraIndices = unique(double(cameraIndices(:).'), 'stable');
            cycleCount = size(cycleOutputFolders, 1);
            if size(cycleOutputFolders, 2) < 2 || cycleCount < 1
                error('ZouLab:RecordPreallocationFoldersInvalid', ...
                    'Cycle output folders must be an N-by-2 cell array.');
            end
            expectedFrames = zoulab.BufferedBinRecorder.expandForCameras( ...
                expectedFrames, cameraIndices, 0);
            expectedFPS = zoulab.BufferedBinRecorder.expandForCameras( ...
                expectedFPS, cameraIndices, NaN);
            cycles = repmat(struct('index', 0, ...
                'cameras', struct([])), 1, cycleCount);
            totalSegments = 0;
            totalBytes = 0;
            for cycleIndex = 1:cycleCount
                cameras = struct([]);
                for position = 1:numel(cameraIndices)
                    cameraIndex = cameraIndices(position);
                    folder = string(cycleOutputFolders{cycleIndex, cameraIndex});
                    if strlength(folder) == 0
                        error('ZouLab:RecordPreallocationFolderMissing', ...
                            'Cycle %d Camera %d folder is missing.', ...
                            cycleIndex, cameraIndex);
                    end
                    if ~isfolder(folder)
                        mkdir(folder);
                    end
                    zoulab.BufferedBinRecorder.assertEmptyRecordNamespace( ...
                        folder, cameraIndex);
                    frameSize = double(frameSizes{cameraIndex}(:).');
                    fps = expectedFPS(cameraIndex);
                    if numel(frameSize) ~= 2 || any(frameSize < 1) || ...
                            ~isfinite(fps) || fps <= 0
                        error('ZouLab:RecordPreallocationSettingsInvalid', ...
                            ['Cycle %d Camera %d requires [height width] and ', ...
                             'a positive expected FPS.'], cycleIndex, cameraIndex);
                    end
                    segmentFrames = max( ...
                        zoulab.BufferedBinRecorder.BlockFrames, ...
                        round(zoulab.BufferedBinRecorder.SegmentSeconds * fps));
                    expected = max(1, round(expectedFrames(cameraIndex)));
                    segmentCount = max(1, ceil(expected / segmentFrames));
                    paths = strings(1, segmentCount);
                    finalPaths = strings(1, segmentCount);
                    counts = zeros(1, segmentCount);
                    bytesPerFrame = prod(frameSize) * 2;
                    for segmentIndex = 1:segmentCount
                        firstFrame = (segmentIndex - 1) * segmentFrames + 1;
                        counts(segmentIndex) = min(segmentFrames, ...
                            expected - firstFrame + 1);
                        finalPaths(segmentIndex) = string(fullfile(folder, ...
                            sprintf('Rec_%03d.bin', segmentIndex)));
                        paths(segmentIndex) = finalPaths(segmentIndex) + ".part";
                        totalBytes = totalBytes + ...
                            counts(segmentIndex) * bytesPerFrame;
                    end
                    entry = struct('camera', cameraIndex, ...
                        'folder', char(folder), ...
                        'part_paths', {cellstr(paths)}, ...
                        'final_paths', {cellstr(finalPaths)}, ...
                        'frame_counts', counts, ...
                        'expected_frames', expected, ...
                        'expected_fps', fps, ...
                        'frame_size_hw', frameSize, ...
                        'segment_frames', segmentFrames);
                    if isempty(cameras)
                        cameras = entry;
                    else
                        cameras(position) = entry;
                    end
                    totalSegments = totalSegments + segmentCount;
                end
                cycles(cycleIndex).index = cycleIndex;
                cycles(cycleIndex).cameras = cameras;
            end
            completed = 0;
            for cycleIndex = 1:cycleCount
                for position = 1:numel(cycles(cycleIndex).cameras)
                    entry = cycles(cycleIndex).cameras(position);
                    bytesPerFrame = prod(entry.frame_size_hw) * 2;
                    paths = string(entry.part_paths);
                    for segmentIndex = 1:numel(paths)
                        zoulab.BufferedBinRecorder.setFileLength(paths(segmentIndex), ...
                            entry.frame_counts(segmentIndex) * bytesPerFrame);
                        completed = completed + 1;
                        if ~isempty(progressFcn)
                            progressFcn(completed, totalSegments, ...
                                cycleIndex, entry.camera, segmentIndex);
                        end
                    end
                end
            end
            result = struct('schema_version', '1.0.0', ...
                'created_utc', zoulab.BinInfo.utcNow(), ...
                'state', 'allocated_not_published', ...
                'cycle_count', cycleCount, ...
                'camera_indices', cameraIndices, ...
                'total_segments', totalSegments, ...
                'total_bytes', totalBytes, 'cycles', cycles);
        end

        function cleanupUnpublishedParts(preallocation, firstCycleToRemove)
            if nargin < 2
                firstCycleToRemove = 1;
            end
            if isempty(preallocation) || ~isfield(preallocation, 'cycles')
                return;
            end
            for cycleIndex = max(1, firstCycleToRemove):numel(preallocation.cycles)
                cameras = preallocation.cycles(cycleIndex).cameras;
                for position = 1:numel(cameras)
                    paths = string(cameras(position).part_paths);
                    for path = paths
                        if isfile(path)
                            delete(path);
                        end
                    end
                end
            end
        end

        function policy = computeIatBufferPolicy(availableMemoryBytes, ...
                writerQueuePayloadBytes)
            validateattributes(availableMemoryBytes, {'numeric'}, ...
                {'scalar','real','nonnegative'});
            validateattributes(writerQueuePayloadBytes, {'numeric'}, ...
                {'scalar','real','finite','nonnegative'});
            measured = isfinite(availableMemoryBytes);
            if measured
                capacityBytes = max(0, double(availableMemoryBytes) - ...
                    double(writerQueuePayloadBytes));
                stopBytes = ...
                    zoulab.BufferedBinRecorder.IatProtectionFraction * ...
                    capacityBytes;
            else
                capacityBytes = Inf;
                stopBytes = Inf;
            end
            policy = struct( ...
                'memory_measurement_available', measured, ...
                'available_memory_bytes', double(availableMemoryBytes), ...
                'writer_queue_payload_bytes', ...
                    double(writerQueuePayloadBytes), ...
                'iat_capacity_bytes', capacityBytes, ...
                'iat_stop_fraction', ...
                    zoulab.BufferedBinRecorder.IatProtectionFraction, ...
                'iat_stop_bytes', stopBytes);
        end

        function value = numberText(number)
            if isfinite(number)
                value = sprintf('%.0f', number);
            else
                value = 'Inf';
            end
        end

        function pressure = computeIatPressure(framesAvailable, ...
                bytesPerFrame, policy)
            framesAvailable = double(framesAvailable(:).');
            bytesPerFrame = double(bytesPerFrame(:).');
            if numel(framesAvailable) ~= numel(bytesPerFrame) || ...
                    any(~isfinite(framesAvailable)) || ...
                    any(framesAvailable < 0) || ...
                    any(~isfinite(bytesPerFrame)) || any(bytesPerFrame <= 0)
                error('ZouLab:IatPressureInputInvalid', ...
                    ['FramesAvailable and bytes-per-frame must be equal-length ', ...
                     'finite vectors with nonnegative frames and positive bytes.']);
            end
            bytesByStream = framesAvailable .* bytesPerFrame;
            totalBytes = sum(bytesByStream);
            capacityBytes = double(policy.iat_capacity_bytes);
            stopBytes = double(policy.iat_stop_bytes);
            if isfinite(capacityBytes) && capacityBytes > 0
                fraction = totalBytes / capacityBytes;
            else
                fraction = 0;
            end
            pressure = struct( ...
                'bytes_by_stream', bytesByStream, ...
                'total_bytes', totalBytes, ...
                'capacity_fraction', fraction, ...
                'stop_required', isfinite(stopBytes) && stopBytes > 0 && ...
                    totalBytes >= stopBytes);
        end

        function [issues, result] = validateMetadataSequence(metadata, ...
                frameTimes, previousFrameNumber, previousTimestamp)
            issues = struct('Code', {}, 'Severity', {}, 'Message', {});
            frameTimes = double(frameTimes(:));
            result = struct('MetadataAvailable', false, ...
                'FirstFrameNumber', NaN, 'LastFrameNumber', NaN, ...
                'FirstTimestamp', NaN, 'LastTimestamp', NaN);
            if ~isempty(frameTimes)
                result.FirstTimestamp = frameTimes(1);
                result.LastTimestamp = frameTimes(end);
                if any(~isfinite(frameTimes)) || ...
                        any(diff(frameTimes) <= 0) || ...
                        (isfinite(previousTimestamp) && ...
                        frameTimes(1) <= previousTimestamp)
                    issues(end + 1) = struct( ...
                        'Code', 'TIMESTAMP_NOT_STRICTLY_INCREASING', ...
                        'Severity', 'ERROR', ...
                        'Message', sprintf( ...
                        ['Previous=%.17g | First=%.17g | Last=%.17g | ', ...
                         'Count=%d'], previousTimestamp, frameTimes(1), ...
                        frameTimes(end), numel(frameTimes))); %#ok<AGROW>
                end
            end
            if isempty(metadata) || ~isstruct(metadata) || ...
                    ~isfield(metadata, 'FrameNumber') || ...
                    numel(metadata) ~= numel(frameTimes)
                issues(end + 1) = struct( ...
                    'Code', 'METADATA_UNAVAILABLE', ...
                    'Severity', 'WARNING', ...
                    'Message', sprintf('MetadataCount=%d | FrameCount=%d', ...
                    numel(metadata), numel(frameTimes))); %#ok<AGROW>
                return;
            end
            frameNumbers = double([metadata.FrameNumber]).';
            result.MetadataAvailable = true;
            result.FirstFrameNumber = frameNumbers(1);
            result.LastFrameNumber = frameNumbers(end);
            badInternal = find(diff(frameNumbers) ~= 1, 1);
            badCrossBlock = isfinite(previousFrameNumber) && ...
                frameNumbers(1) ~= previousFrameNumber + 1;
            if any(~isfinite(frameNumbers)) || badCrossBlock || ...
                    ~isempty(badInternal)
                issues(end + 1) = struct( ...
                    'Code', 'FRAME_NUMBER_DISCONTINUITY', ...
                    'Severity', 'ERROR', ...
                    'Message', sprintf( ...
                    ['Previous=%.17g | First=%.17g | Last=%.17g | ', ...
                     'FirstInternalBreak=%s | Count=%d'], ...
                    previousFrameNumber, frameNumbers(1), frameNumbers(end), ...
                    mat2str(badInternal), numel(frameNumbers))); %#ok<AGROW>
            end
        end

        function writerLoop(commandQueue, statusQueue, cameraIndex)
            outputFolder = "";
            frameSize = [];
            segmentFrames = 0;
            preallocatedPaths = strings(1, 0);
            preallocatedFrameCounts = zeros(1, 0);
            bytesPerFrame = 0;
            segmentIndex = 0;
            framesInSegment = 0;
            totalFrames = 0;
            expectedBlock = 1;
            fid = -1;
            currentPath = "";
            usedFiles = strings(1, 0);
            usedFileFrameCounts = zeros(1, 0);
            cycleActive = false;
            try
                if isempty(commandQueue)
                    % Before R2025a, PollableDataQueue can only be polled by
                    % its creator.  Let this writer create the command queue
                    % and return its send endpoint to the camera service.
                    commandQueue = parallel.pool.PollableDataQueue;
                end
                send(statusQueue, struct('Type', "READY", ...
                    'Camera', cameraIndex, 'CommandQueue', commandQueue));
                while true
                    command = poll(commandQueue, Inf);
                    switch string(command.Type)
                        case "BEGIN_CYCLE"
                            if cycleActive
                                error('ZouLab:BinWriterCycleAlreadyOpen', ...
                                    'Camera %d received BEGIN_CYCLE while active.', ...
                                    cameraIndex);
                            end
                            outputFolder = string(command.OutputFolder);
                            frameSize = double(command.FrameSize(:).');
                            segmentFrames = double(command.SegmentFrames);
                            preallocatedPaths = ...
                                string(command.PreallocatedPaths);
                            preallocatedFrameCounts = ...
                                double(command.PreallocatedFrameCounts);
                            bytesPerFrame = prod(frameSize) * 2;
                            segmentIndex = 0;
                            framesInSegment = 0;
                            totalFrames = 0;
                            expectedBlock = 1;
                            fid = -1;
                            currentPath = "";
                            usedFiles = strings(1, 0);
                            usedFileFrameCounts = zeros(1, 0);
                            cycleActive = true;
                            send(statusQueue, struct('Type', "CYCLE_READY", ...
                                'Camera', cameraIndex));
                        case "DATA"
                            if ~cycleActive
                                error('ZouLab:BinWriterCycleNotOpen', ...
                                    'Camera %d received DATA without an active Cycle.', ...
                                    cameraIndex);
                            end
                            if double(command.BlockIndex) ~= expectedBlock
                                send(statusQueue, struct( ...
                                    'Type', "BLOCK_SEQUENCE_ERROR", ...
                                    'Camera', cameraIndex, ...
                                    'ExpectedBlock', expectedBlock, ...
                                    'ReceivedBlock', double(command.BlockIndex)));
                            end
                            expectedBlock = double(command.BlockIndex) + 1;
                            blockFrames = double(command.Frames);
                            offset = 1;
                            while offset <= blockFrames
                                if fid < 0
                                    segmentIndex = segmentIndex + 1;
                                    [currentPath, fid, overflowSegment] = ...
                                        zoulab.BufferedBinRecorder.openSegment( ...
                                        outputFolder, segmentIndex, ...
                                        preallocatedPaths, ...
                                        preallocatedFrameCounts);
                                    if overflowSegment
                                        send(statusQueue, struct( ...
                                            'Type', "OVERFLOW_SEGMENT_OPENED", ...
                                            'Camera', cameraIndex, ...
                                            'SegmentIndex', segmentIndex, ...
                                            'PlannedSegments', ...
                                                numel(preallocatedPaths), ...
                                            'File', currentPath, ...
                                            'Folder', string(outputFolder)));
                                    end
                                    usedFiles(end + 1) = currentPath; %#ok<AGROW>
                                    framesInSegment = 0;
                                end
                                available = segmentFrames - framesInSegment;
                                take = min(available, blockFrames - offset + 1);
                                elementsWritten = fwrite(fid, ...
                                    command.Data(:, :, :, offset:offset + take - 1), ...
                                    'uint16');
                                expectedElements = prod(frameSize) * take;
                                if elementsWritten ~= expectedElements
                                    error('ZouLab:BinWriterShortWrite', ...
                                        ['Camera %d segment %d wrote %d of %d ', ...
                                         'uint16 elements.'], cameraIndex, ...
                                        segmentIndex, elementsWritten, ...
                                        expectedElements);
                                end
                                framesInSegment = framesInSegment + take;
                                totalFrames = totalFrames + take;
                                offset = offset + take;
                                if framesInSegment == segmentFrames
                                    fclose(fid);
                                    fid = -1;
                                    usedFileFrameCounts(segmentIndex) = ...
                                        framesInSegment;
                                    send(statusQueue, struct( ...
                                        'Type', "SEGMENT_CLOSED", ...
                                        'Camera', cameraIndex, ...
                                        'SegmentIndex', segmentIndex, ...
                                        'Frames', framesInSegment, ...
                                        'Bytes', framesInSegment * bytesPerFrame, ...
                                        'File', currentPath));
                                end
                            end
                            send(statusQueue, struct('Type', "ACK", ...
                                'Camera', cameraIndex, ...
                                'BlockIndex', command.BlockIndex, ...
                                'Frames', blockFrames));
                            clear command
                        case "CLOSE_CYCLE"
                            if ~cycleActive
                                error('ZouLab:BinWriterCycleNotOpen', ...
                                    'Camera %d received CLOSE_CYCLE while idle.', ...
                                    cameraIndex);
                            end
                            if fid >= 0
                                fclose(fid);
                                fid = -1;
                                usedFileFrameCounts(segmentIndex) = ...
                                    framesInSegment;
                                send(statusQueue, struct( ...
                                    'Type', "SEGMENT_CLOSED", ...
                                    'Camera', cameraIndex, ...
                                    'SegmentIndex', segmentIndex, ...
                                    'Frames', framesInSegment, ...
                                    'Bytes', framesInSegment * bytesPerFrame, ...
                                    'File', currentPath));
                            end
                            send(statusQueue, struct('Type', "CLOSED", ...
                                'Camera', cameraIndex, ...
                                'FramesWritten', totalFrames, ...
                                'Files', usedFiles, ...
                                'FileFrameCounts', usedFileFrameCounts, ...
                                'PreallocatedPaths', preallocatedPaths));
                            cycleActive = false;
                        case "SHUTDOWN"
                            if cycleActive
                                if fid >= 0
                                    fclose(fid);
                                    fid = -1;
                                    usedFileFrameCounts(segmentIndex) = ...
                                        framesInSegment;
                                    send(statusQueue, struct( ...
                                        'Type', "SEGMENT_CLOSED", ...
                                        'Camera', cameraIndex, ...
                                        'SegmentIndex', segmentIndex, ...
                                        'Frames', framesInSegment, ...
                                        'Bytes', framesInSegment * bytesPerFrame, ...
                                        'File', currentPath));
                                end
                                send(statusQueue, struct('Type', "CLOSED", ...
                                    'Camera', cameraIndex, ...
                                    'FramesWritten', totalFrames, ...
                                    'Files', usedFiles, ...
                                    'FileFrameCounts', usedFileFrameCounts, ...
                                    'PreallocatedPaths', preallocatedPaths));
                            end
                            send(statusQueue, struct('Type', "TERMINATED", ...
                                'Camera', cameraIndex));
                            return;
                        otherwise
                            error('ZouLab:BinWriterUnknownCommand', ...
                                'Camera %d received command %s.', ...
                                cameraIndex, string(command.Type));
                    end
                end
            catch ME
                if fid >= 0
                    try
                        fclose(fid);
                    catch
                    end
                end
                send(statusQueue, struct('Type', "ERROR", ...
                    'Camera', cameraIndex, 'Identifier', string(ME.identifier), ...
                    'Message', string(ME.message)));
            end
        end

        function [path, fid, overflowSegment] = openSegment( ...
                outputFolder, segmentIndex, ...
                preallocatedPaths, preallocatedFrameCounts)
            path = string(fullfile(outputFolder, sprintf( ...
                'Rec_%03d.bin.part', segmentIndex)));
            overflowSegment = segmentIndex > numel(preallocatedPaths);
            if segmentIndex <= numel(preallocatedPaths)
                path = string(preallocatedPaths(segmentIndex));
                permission = 'r+';
            else
                % An unexpected segment remains inside this recorder's
                % camera/Cycle folder.  Create it empty and let sequential
                % fwrite calls grow it. MATLAB fseek cannot extend a new
                % empty file beyond EOF, which caused the old preallocation
                % failure. Never overwrite a stale namespace.
                if isfile(path)
                    error('ZouLab:BinOverflowSegmentExists', ...
                        ['Unexpected overflow segment already exists: %s. ', ...
                         'Refusing to mix or overwrite record data.'], path);
                end
                permission = 'w';
            end
            if segmentIndex <= numel(preallocatedFrameCounts) && ...
                    preallocatedFrameCounts(segmentIndex) <= 0
                error('ZouLab:BinPreallocationInvalid', ...
                    'Segment %d has an invalid preallocated frame count.', ...
                    segmentIndex);
            end
            fid = fopen(path, permission, 'ieee-le');
            if fid < 0
                error('ZouLab:BinOpenFailed', 'Cannot open BIN file: %s', path);
            end
        end

        function setFileLength(path, byteCount)
            fileObject = javaObject('java.io.RandomAccessFile', char(path), 'rw');
            cleanup = onCleanup(@() fileObject.close()); %#ok<NASGU>
            fileObject.setLength(int64(byteCount));
        end

        function assertEmptyRecordNamespace(folder, cameraIndex)
            binEntries = dir(fullfile(folder, 'Rec_*.bin'));
            partEntries = dir(fullfile(folder, 'Rec_*.bin.part'));
            infoEntries = dir(fullfile(folder, 'Rec_*.info.json'));
            if ~isempty(binEntries) || ~isempty(partEntries) || ...
                    ~isempty(infoEntries)
                names = string({binEntries.name partEntries.name infoEntries.name});
                error('ZouLab:BinRecordNamespaceNotEmpty', ...
                    ['Camera %d output folder already contains record ', ...
                     'segments or sidecars: %s | Folder=%s | ', ...
                     'RefusingToMixCycles=1'], cameraIndex, ...
                    strjoin(names, ','), string(folder));
            end
        end

        function path = normalizedPath(path)
            path = lower(replace(string(path), '/', '\'));
            while strlength(path) > 3 && endsWith(path, '\')
                path = extractBefore(path, strlength(path));
            end
        end

        function removeUnusedPreallocation(preallocatedPaths, usedFiles)
            for index = 1:numel(preallocatedPaths)
                path = string(preallocatedPaths(index));
                if ~any(usedFiles == path) && isfile(path)
                    delete(path);
                end
            end
        end

        function finalFiles = publishPartFiles(partFiles)
            finalFiles = strings(size(partFiles));
            for index = 1:numel(partFiles)
                partPath = string(partFiles(index));
                if endsWith(partPath, ".part")
                    finalPath = extractBefore(partPath, strlength(partPath) - 4);
                else
                    finalPath = partPath;
                end
                if finalPath ~= partPath
                    if isfile(finalPath)
                        error('ZouLab:BinPublishTargetExists', ...
                            'Refusing to overwrite published BIN: %s', finalPath);
                    end
                    [ok, message] = movefile(partPath, finalPath, 'f');
                    if ~ok
                        error('ZouLab:BinPublishFailed', ...
                            'Cannot publish %s as %s: %s', ...
                            partPath, finalPath, message);
                    end
                end
                finalFiles(index) = finalPath;
            end
        end

        function values = expandForCameras(inputValues, cameraIndices, fallback)
            values = repmat(fallback, 1, 2);
            inputValues = double(inputValues(:).');
            if numel(inputValues) == 2
                values = inputValues;
            elseif numel(inputValues) == numel(cameraIndices)
                values(cameraIndices) = inputValues;
            elseif isscalar(inputValues)
                values(cameraIndices) = inputValues;
            else
                error('ZouLab:BinCameraValueCountInvalid', ...
                    'Values must be scalar, per-active-camera, or length two.');
            end
        end
    end

    methods (Access = private)
        function resetCycleState(obj)
            obj.RetrievedFrames = [0 0];
            obj.EnqueuedFrames = [0 0];
            obj.WrittenFrames = [0 0];
            obj.InFlightBlocks = [0 0];
            obj.InFlightFrames = [0 0];
            obj.MaxInFlightBlocks = [0 0];
            obj.MaxInFlightFrames = [0 0];
            obj.NextBlockIndex = [1 1];
            obj.LastFrameNumber = [NaN NaN];
            obj.FirstTimestamp = [NaN NaN];
            obj.LastTimestamp = [NaN NaN];
            obj.MetadataErrorCount = [0 0];
            obj.MetadataUnavailableBlockCount = [0 0];
            obj.WriterBlockOrderErrorCount = [0 0];
            obj.BinFiles = {strings(1, 0), strings(1, 0)};
            obj.BinFileFrameCounts = {zeros(1, 0), zeros(1, 0)};
            obj.BinInfoFiles = {strings(1, 0), strings(1, 0)};
            obj.WriterCycleReady = false(1, 2);
            obj.WriterClosed = false(1, 2);
            obj.CloseRequested = false;
            obj.MetadataDetailLogs = [0 0];
            obj.Closed = false;
            obj.CycleActive = false;
        end

        function waitForCycleReady(obj, timeoutSeconds)
            waitClock = tic;
            while ~all(obj.WriterCycleReady(obj.CameraIndices))
                obj.processMessages(0.1);
                obj.assertWritersHealthy(obj.CameraIndices);
                if toc(waitClock) > timeoutSeconds
                    error('ZouLab:BinWriterCycleReadyTimeout', ...
                        'BIN writers did not open the Cycle within %.1f seconds.', ...
                        timeoutSeconds);
                end
            end
        end

        function releaseWriterResources(obj, cancelRunning)
            if obj.ResourcesReleased
                return;
            end
            for cameraIndex = obj.CameraIndices
                future = obj.WriterFutures{cameraIndex};
                if ~isempty(future)
                    if cancelRunning
                        try
                            cancel(future);
                        catch
                        end
                    end
                    try
                        delete(future);
                    catch
                    end
                end
                obj.WriterFutures{cameraIndex} = [];
                obj.CommandQueues{cameraIndex} = [];
            end
            obj.StatusQueue = [];
            obj.ResourcesReleased = true;
            obj.CycleActive = false;
            obj.Closed = true;
        end

        function values = expandCameraValues(obj, inputValues, fallback)
            values = repmat(fallback, 1, 2);
            inputValues = double(inputValues(:).');
            if numel(inputValues) == 2
                values = inputValues;
            elseif numel(inputValues) == numel(obj.CameraIndices)
                values(obj.CameraIndices) = inputValues;
            elseif isscalar(inputValues)
                values(obj.CameraIndices) = inputValues;
            else
                error('ZouLab:BinCameraValueCountInvalid', ...
                    'Values must be scalar, per-active-camera, or length two.');
            end
        end

        function [paths, frameCounts] = preallocateCameraFiles(obj, cameraIndex)
            expected = max(1, round(obj.ExpectedFrames(cameraIndex)));
            segmentFrames = obj.SegmentFrames(cameraIndex);
            segmentCount = max(1, ceil(expected / segmentFrames));
            paths = strings(1, segmentCount);
            frameCounts = zeros(1, segmentCount);
            bytesPerFrame = prod(obj.FrameSizes{cameraIndex}) * 2;
            for segmentIndex = 1:segmentCount
                firstFrame = (segmentIndex - 1) * segmentFrames + 1;
                frameCounts(segmentIndex) = min(segmentFrames, ...
                    expected - firstFrame + 1);
                paths(segmentIndex) = string(fullfile( ...
                    obj.OutputFolders{cameraIndex}, sprintf( ...
                    'Rec_%03d.bin.part', segmentIndex)));
                zoulab.BufferedBinRecorder.setFileLength(paths(segmentIndex), ...
                    frameCounts(segmentIndex) * bytesPerFrame);
            end
        end

        function [paths, frameCounts] = cyclePreallocation(obj, ...
                cameraIndex, preallocation)
            if isempty(preallocation)
                [paths, frameCounts] = obj.preallocateCameraFiles(cameraIndex);
                return;
            end
            cameras = preallocation;
            if isstruct(preallocation) && isfield(preallocation, 'cameras')
                cameras = preallocation.cameras;
            end
            match = find([cameras.camera] == cameraIndex, 1);
            if isempty(match)
                error('ZouLab:BinPreallocationCameraMissing', ...
                    'No preallocation entry exists for Camera %d.', cameraIndex);
            end
            entry = cameras(match);
            paths = string(entry.part_paths);
            frameCounts = double(entry.frame_counts(:).');
            expectedFolder = zoulab.BufferedBinRecorder.normalizedPath( ...
                obj.OutputFolders{cameraIndex});
            bytesPerFrame = prod(obj.FrameSizes{cameraIndex}) * 2;
            if isempty(paths) || numel(paths) ~= numel(frameCounts)
                error('ZouLab:BinPreallocationInvalid', ...
                    'Camera %d preallocation has mismatched paths and counts.', ...
                    cameraIndex);
            end
            for index = 1:numel(paths)
                actualFolder = zoulab.BufferedBinRecorder.normalizedPath( ...
                    fileparts(paths(index)));
                listing = dir(paths(index));
                expectedBytes = frameCounts(index) * bytesPerFrame;
                if actualFolder ~= expectedFolder || ...
                        ~endsWith(paths(index), ".bin.part") || ...
                        isempty(listing) || listing.bytes ~= expectedBytes
                    error('ZouLab:BinPreallocationValidationFailed', ...
                        ['Camera %d segment %d failed folder, suffix, ', ...
                         'existence, or byte-count validation.'], ...
                        cameraIndex, index);
                end
            end
        end

        function waitForWritersReady(obj, timeoutSeconds)
            waitClock = tic;
            while ~all(obj.WriterReady(obj.CameraIndices))
                obj.processMessages(0.1);
                errors = obj.WriterErrors(obj.CameraIndices);
                if any(strlength(errors) > 0)
                    error('ZouLab:BinWriterStartFailed', '%s', ...
                        strjoin(errors(strlength(errors) > 0), ' | '));
                end
                if toc(waitClock) > timeoutSeconds
                    error('ZouLab:BinWriterReadyTimeout', ...
                        'BIN writers were not ready within %.1f seconds.', ...
                        timeoutSeconds);
                end
            end
        end

        function recordMetadataIssues(obj, cameraIndex, issues, blockIndex)
            for issueIndex = 1:numel(issues)
                issue = issues(issueIndex);
                if strcmp(issue.Code, 'METADATA_UNAVAILABLE')
                    level = 'WARNING';
                else
                    level = 'ERROR';
                    obj.MetadataErrorCount(cameraIndex) = ...
                        obj.MetadataErrorCount(cameraIndex) + 1;
                end
                if obj.MetadataDetailLogs(cameraIndex) < ...
                        obj.MetadataDetailLogLimit
                    obj.Logger.log(level, 'RECORD_METADATA_SEQUENCE_ISSUE', ...
                        ['Camera=%d | Block=%d | Code=%s | %s | ', ...
                         'AcquisitionContinues=1'], cameraIndex, blockIndex, ...
                        issue.Code, issue.Message);
                    obj.MetadataDetailLogs(cameraIndex) = ...
                        obj.MetadataDetailLogs(cameraIndex) + 1;
                elseif obj.MetadataDetailLogs(cameraIndex) == ...
                        obj.MetadataDetailLogLimit
                    obj.Logger.log('WARNING', ...
                        'RECORD_METADATA_DETAIL_LOG_LIMIT_REACHED', ...
                        ['Camera=%d | Limit=%d | FurtherDetailsSuppressed=1 | ', ...
                         'FinalAggregateRetained=1'], cameraIndex, ...
                        obj.MetadataDetailLogLimit);
                    obj.MetadataDetailLogs(cameraIndex) = ...
                        obj.MetadataDetailLogs(cameraIndex) + 1;
                end
            end
        end

        function writeBinInfoFiles(obj)
            for cameraIndex = obj.CameraIndices
                files = obj.BinFiles{cameraIndex};
                counts = obj.BinFileFrameCounts{cameraIndex};
                if numel(files) ~= numel(counts)
                    error('ZouLab:BinInfoSegmentCountMismatch', ...
                        ['Camera %d has %d BIN files but %d segment frame ', ...
                         'counts.'], cameraIndex, numel(files), numel(counts));
                end
                infoFiles = strings(1, numel(files));
                firstFrame = 1;
                for segmentIndex = 1:numel(files)
                    cameraMetadata = struct();
                    if numel(obj.CameraMetadata) >= cameraIndex && ...
                            ~isempty(obj.CameraMetadata{cameraIndex})
                        cameraMetadata = obj.CameraMetadata{cameraIndex};
                    end
                    value = zoulab.BinInfo.create(files(segmentIndex), ...
                        cameraIndex, segmentIndex, ...
                        obj.FrameSizes{cameraIndex}, counts(segmentIndex), ...
                        obj.ExpectedFPS(cameraIndex), ...
                        obj.RecorderCreatedUtc, cameraMetadata);
                    value.segment_first_record_frame_index = firstFrame;
                    value.segment_last_record_frame_index = ...
                        firstFrame + counts(segmentIndex) - 1;
                    value.integrity = struct( ...
                        'metadata_error_count_acquisition_total', ...
                            obj.MetadataErrorCount(cameraIndex), ...
                        'metadata_unavailable_block_count_acquisition_total', ...
                            obj.MetadataUnavailableBlockCount(cameraIndex), ...
                        'writer_block_order_error_count_acquisition_total', ...
                            obj.WriterBlockOrderErrorCount(cameraIndex));
                    infoFiles(segmentIndex) = ...
                        zoulab.BinInfo.sidecarPath(files(segmentIndex));
                    zoulab.BinInfo.write(infoFiles(segmentIndex), value);
                    cycleText = 'unscoped';
                    if isfield(value, 'storage') && ...
                            ~isempty(value.storage.cycle_index)
                        cycleText = sprintf('%d', ...
                            value.storage.cycle_index);
                    end
                    obj.Logger.log('SUCCESS', 'BIN_INFO_SAVED', ...
                        ['Cycle=%s | Camera=%d | Segment=%d | Frames=%d | ', ...
                         'Bin=%s | Info=%s | OneInfoPerBin=1 | ', ...
                         'FrameTimestampsStored=0'], cycleText, cameraIndex, ...
                        segmentIndex, counts(segmentIndex), ...
                        files(segmentIndex), infoFiles(segmentIndex));
                    firstFrame = firstFrame + counts(segmentIndex);
                end
                obj.BinInfoFiles{cameraIndex} = infoFiles;
            end
        end
    end
end
