classdef DmdCalibration
    %DMDCALIBRATION iDMD-compatible camera-to-DMD grid calibration.
    % Camera 1 uses the standard grid and camera 2 uses the horizontally
    % flipped grid. Physical identity is read from the private rig config.

    properties (Constant)
        DmdWidth = 1920
        DmdHeight = 1080
        GridWidth = 240
        GridHeight = 120
        GridLineWidth = 10
        SchemaVersion = "2.0.0"
    end

    methods (Static)
        function definition = definition()
            rows = 1:zoulab.DmdCalibration.GridHeight: ...
                zoulab.DmdCalibration.DmdHeight;
            columns = 1:zoulab.DmdCalibration.GridWidth: ...
                zoulab.DmdCalibration.DmdWidth;
            [columnGrid, rowGrid] = meshgrid(columns, rows);
            % iDMD numbers cells row-by-row: 1..8 on the first row,
            % 9..16 on the second row, and so on.
            rowMajorRows = reshape(rowGrid.', [], 1);
            rowMajorColumns = reshape(columnGrid.', [], 1);
            coords = [rowMajorRows, rowMajorColumns];
            coordsFlipped = coords;
            coordsFlipped(:, 2) = zoulab.DmdCalibration.DmdWidth - ...
                coordsFlipped(:, 2) + 1;
            definition = struct( ...
                'numbers', (1:size(coords, 1)).', ...
                'coords', coords, ...
                'coordsflipped', coordsFlipped, ...
                'dmd_width', zoulab.DmdCalibration.DmdWidth, ...
                'dmd_height', zoulab.DmdCalibration.DmdHeight, ...
                'grid_width', zoulab.DmdCalibration.GridWidth, ...
                'grid_height', zoulab.DmdCalibration.GridHeight, ...
                'line_width', zoulab.DmdCalibration.GridLineWidth);
        end

        function gridSet = generateGridSet(rootFolder, eightBitFileCount, logger)
            rootFolder = string(rootFolder);
            validateattributes(eightBitFileCount, {'numeric'}, ...
                {'scalar','integer','positive','finite'});
            if strlength(strtrim(rootFolder)) == 0
                error('ZouLab:DmdCalibrationRootRequired', ...
                    'Choose a DMD calibration folder first.');
            end
            if ~isfolder(rootFolder)
                mkdir(rootFolder);
            end
            standardFolder = fullfile(rootFolder, 'Standard_Matrix');
            flippedFolder = fullfile(rootFolder, 'Flipped_Matrix');
            if ~isfolder(standardFolder)
                mkdir(standardFolder);
            end
            if ~isfolder(flippedFolder)
                mkdir(flippedFolder);
            end
            assetRoot = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
                'assets', 'dmd_calibration');
            standardAsset = fullfile(assetRoot, 'standard_grid.bmp');
            flippedAsset = fullfile(assetRoot, 'flipped_grid.bmp');
            if ~isfile(standardAsset) || ~isfile(flippedAsset)
                error('ZouLab:DmdCalibrationAssetsMissing', ...
                    'The packaged iDMD standard/flipped grid assets are missing.');
            end
            zoulab.DmdCalibration.clearGeneratedBmps(standardFolder);
            zoulab.DmdCalibration.clearGeneratedBmps(flippedFolder);
            for imageIndex = 1:eightBitFileCount
                copyfile(standardAsset, fullfile(standardFolder, ...
                    sprintf('%04d.bmp', imageIndex)));
                copyfile(flippedAsset, fullfile(flippedFolder, ...
                    sprintf('%04d.bmp', imageIndex)));
            end
            definition = zoulab.DmdCalibration.definition();
            numbers = definition.numbers; %#ok<NASGU>
            coords = definition.coords; %#ok<NASGU>
            coordsflipped = definition.coordsflipped; %#ok<NASGU>
            metadata = struct( ... %#ok<NASGU>
                'schema_version', char(zoulab.DmdCalibration.SchemaVersion), ...
                'created_at', char(datetime('now', ...
                    'Format', 'yyyy-MM-dd HH:mm:ss.SSS')), ...
                'source', 'packaged exact iDMD grid assets', ...
                'upload_bit_depth', 8, ...
                'upload_file_count', double(eightBitFileCount), ...
                'binary_frame_count', double(eightBitFileCount) * 8, ...
                'camera_mapping', struct( ...
                    'camera1', 'Standard_Matrix / Camera 1', ...
                    'camera2', 'Flipped_Matrix / Camera 2'));
            parameterFile = fullfile(rootFolder, ...
                '0_Standard parameters.mat');
            save(parameterFile, 'numbers', 'coords', 'coordsflipped', 'metadata');
            gridSet = struct( ...
                'root', char(rootFolder), ...
                'standard_folder', char(standardFolder), ...
                'flipped_folder', char(flippedFolder), ...
                'parameter_file', char(parameterFile), ...
                'image_count', double(eightBitFileCount), ...
                'binary_frame_count', double(eightBitFileCount) * 8);
            zoulab.DmdCalibration.writeGridManifest(standardFolder, ...
                'calibration_standard', eightBitFileCount);
            zoulab.DmdCalibration.writeGridManifest(flippedFolder, ...
                'calibration_flipped', eightBitFileCount);
            if nargin >= 3 && ~isempty(logger)
                logger.log('SUCCESS', 'DMD_CALIBRATION_GRIDS_GENERATED', ...
                    ['Root=%s | StandardFolder=%s | FlippedFolder=%s | ', ...
                     'ImagesPerFolder=%d | ExactIDMDAssets=1'], ...
                    rootFolder, standardFolder, flippedFolder, eightBitFileCount);
            end
        end

        function mapping = mappingForCamera(cameraIndex, gridSet)
            validateattributes(cameraIndex, {'numeric'}, ...
                {'scalar','integer','>=',1,'<=',2});
            if cameraIndex == 1
                mapping = struct('camera_index', 1, 'serial', '', ...
                    'bus', '', 'orientation', 'standard', ...
                    'folder', gridSet.standard_folder);
            else
                mapping = struct('camera_index', 2, 'serial', '', ...
                    'bus', '', 'orientation', 'flipped', ...
                    'folder', gridSet.flipped_folder);
            end
        end

        function calibration = solve(cameraPoints, selectedNumbers, ...
                cameraIndex, sourceImageFile)
            validateattributes(cameraPoints, {'numeric'}, ...
                {'size',[3 2],'finite','real'});
            selectedNumbers = double(selectedNumbers(:));
            validateattributes(selectedNumbers, {'numeric'}, ...
                {'size',[3 1],'integer','>=',1,'<=',72,'finite'});
            if numel(unique(selectedNumbers)) ~= 3
                error('ZouLab:DmdCalibrationLabelsRepeated', ...
                    'The three grid labels must be different.');
            end
            if abs(det([cameraPoints.'; ones(1, 3)])) < 1e-9
                error('ZouLab:DmdCalibrationPointsCollinear', ...
                    'Choose three grid intersections that form a triangle.');
            end
            definition = zoulab.DmdCalibration.definition();
            if cameraIndex == 1
                coords = definition.coords;
                orientation = 'standard';
                serial = '';
                bus = '';
            elseif cameraIndex == 2
                coords = definition.coordsflipped;
                orientation = 'flipped';
                serial = '';
                bus = '';
            else
                error('ZouLab:DmdCalibrationCameraInvalid', ...
                    'DMD calibration camera must be 1 or 2.');
            end
            pointsStandard = coords(selectedNumbers, :);
            tPoints = [cameraPoints(:, 1).'; cameraPoints(:, 2).'; ones(1, 3)];
            tPointsStandard = [pointsStandard(:, 1).'; ...
                pointsStandard(:, 2).'; ones(1, 3)];
            transform = tPointsStandard / tPoints;
            if any(~isfinite(transform), 'all')
                error('ZouLab:DmdCalibrationTransformInvalid', ...
                    'The selected points produced an invalid transform.');
            end
            calibration = struct( ...
                'schema_version', char(zoulab.DmdCalibration.SchemaVersion), ...
                'created_at', char(datetime('now', ...
                    'Format', 'yyyy-MM-dd HH:mm:ss.SSS')), ...
                'camera_index', double(cameraIndex), ...
                'camera_serial', serial, ...
                'camera_bus', bus, ...
                'grid_orientation', orientation, ...
                'camera_points', double(cameraPoints), ...
                'selected_numbers', selectedNumbers, ...
                'points_standard', pointsStandard, ...
                'T_points', tPoints, ...
                'T_points_standard', tPointsStandard, ...
                'T', transform, ...
                'source_image_file', char(string(sourceImageFile)), ...
                'point_semantics', ...
                    'raw camera image [x=column,y=row]; iDMD T convention preserved');
        end

        function sensorPoints = displayToSensorPoints(displayPoints, roi, ...
                binFactor, transposeDisplay)
            validateattributes(displayPoints, {'numeric'}, ...
                {'2d','ncols',2,'finite','real'});
            validateattributes(roi, {'numeric'}, ...
                {'vector','numel',4,'finite','real','nonnegative'});
            validateattributes(binFactor, {'numeric'}, ...
                {'scalar','integer','positive','finite'});
            if logical(transposeDisplay)
                localRaw = double(displayPoints(:, [2 1]));
            else
                localRaw = double(displayPoints);
            end
            roi = double(roi(:).');
            % Image Acquisition ROIPosition is zero-based in the currently
            % binned image.  Convert each displayed pixel centre into the
            % common unbinned, full-sensor, one-based pixel-centre system.
            centreOffset = (double(binFactor) + 1) / 2;
            sensorPoints = zeros(size(localRaw));
            sensorPoints(:, 1) = roi(1) * binFactor + ...
                (localRaw(:, 1) - 1) * binFactor + centreOffset;
            sensorPoints(:, 2) = roi(2) * binFactor + ...
                (localRaw(:, 2) - 1) * binFactor + centreOffset;
        end

        function calibration = solveWithGeometry(displayPoints, ...
                selectedNumbers, cameraInfo, gridOrientation, sourceImageFile)
            required = {'camera_index','serial','bus','roi','bin','transpose_display'};
            for index = 1:numel(required)
                if ~isfield(cameraInfo, required{index})
                    error('ZouLab:DmdCalibrationCameraMetadataMissing', ...
                        'DMD calibration camera metadata is missing %s.', ...
                        required{index});
                end
            end
            validateattributes(displayPoints, {'numeric'}, ...
                {'size',[3 2],'finite','real'});
            selectedNumbers = double(selectedNumbers(:));
            validateattributes(selectedNumbers, {'numeric'}, ...
                {'size',[3 1],'integer','>=',1,'<=',72,'finite'});
            if numel(unique(selectedNumbers)) ~= 3
                error('ZouLab:DmdCalibrationLabelsRepeated', ...
                    'The three grid labels must be different.');
            end
            sensorPoints = zoulab.DmdCalibration.displayToSensorPoints( ...
                displayPoints, cameraInfo.roi, cameraInfo.bin, ...
                cameraInfo.transpose_display);
            if abs(det([sensorPoints.'; ones(1, 3)])) < 1e-9
                error('ZouLab:DmdCalibrationPointsCollinear', ...
                    'Choose three grid intersections that form a triangle.');
            end
            definition = zoulab.DmdCalibration.definition();
            orientation = lower(string(gridOrientation));
            if orientation == "standard"
                coords = definition.coords;
            elseif orientation == "flipped"
                coords = definition.coordsflipped;
            else
                error('ZouLab:DmdCalibrationGridOrientationInvalid', ...
                    'DMD calibration grid must be standard or flipped.');
            end
            pointsStandard = coords(selectedNumbers, :);
            sensorHomogeneous = [sensorPoints.'; ones(1, 3)];
            dmdHomogeneous = [pointsStandard(:, 1).'; ...
                pointsStandard(:, 2).'; ones(1, 3)];
            transform = dmdHomogeneous / sensorHomogeneous;
            calibration = struct( ...
                'schema_version', char(zoulab.DmdCalibration.SchemaVersion), ...
                'created_at', char(datetime('now', ...
                    'Format', 'yyyy-MM-dd HH:mm:ss.SSS')), ...
                'coordinate_space', 'full_sensor_pixel_center_unbinned', ...
                'camera_index', double(cameraInfo.camera_index), ...
                'camera_serial', char(string(cameraInfo.serial)), ...
                'camera_bus', char(string(cameraInfo.bus)), ...
                'camera_roi_at_calibration', double(cameraInfo.roi(:).'), ...
                'camera_bin_at_calibration', double(cameraInfo.bin), ...
                'display_transpose_at_calibration', ...
                    logical(cameraInfo.transpose_display), ...
                'grid_orientation', char(orientation), ...
                'display_points_xy', double(displayPoints), ...
                'sensor_points_xy', sensorPoints, ...
                'camera_points', sensorPoints, ...
                'selected_numbers', selectedNumbers, ...
                'points_standard', pointsStandard, ...
                'T_points', sensorHomogeneous, ...
                'T_points_standard', dmdHomogeneous, ...
                'T', transform, ...
                'source_image_file', char(string(sourceImageFile)), ...
                'point_semantics', ...
                    ['input=[full sensor x,y pixel centres, unbinned]; ', ...
                     'output=[DMD row,column]; iDMD matrix convention preserved']);
        end

        function result = compatibility(calibration, cameraInfo)
            result = struct('compatible', false, 'verified', false, ...
                'message', '', 'legacy', false);
            if ~isfield(calibration, 'coordinate_space') || ...
                    string(calibration.coordinate_space) ~= ...
                    "full_sensor_pixel_center_unbinned"
                result.legacy = true;
                result.message = ['Legacy iDMD calibration uses ROI-local pixels; ', ...
                    'reuse requires the original ROI, Bin and orientation.'];
                if isfield(calibration, 'camera_index') && ...
                        double(calibration.camera_index) == ...
                        double(cameraInfo.camera_index)
                    result.compatible = true;
                end
                return;
            end
            serialMatches = strcmpi(string(calibration.camera_serial), ...
                string(cameraInfo.serial));
            result.compatible = serialMatches;
            result.verified = serialMatches;
            if serialMatches
                result.message = ['Full-sensor calibration is compatible with ', ...
                    'the current ROI, Bin and display transpose.'];
            else
                result.message = sprintf( ...
                    'Calibration camera %s does not match current camera %s.', ...
                    string(calibration.camera_serial), string(cameraInfo.serial));
            end
        end

        function saveCalibration(filePath, calibration, imageData, logger)
            zoulab.DmdCalibration.validateCalibration(calibration, ...
                calibration.camera_index);
            folder = fileparts(filePath);
            if ~isfolder(folder)
                mkdir(folder);
            end
            T_points = calibration.T_points; %#ok<NASGU>
            T_points_standard = calibration.T_points_standard; %#ok<NASGU>
            T = calibration.T; %#ok<NASGU>
            selected_numbers = calibration.selected_numbers; %#ok<NASGU>
            im = imageData; %#ok<NASGU>
            metadata = calibration; %#ok<NASGU>
            save(filePath, 'T_points', 'T_points_standard', 'T', ...
                'selected_numbers', 'im', 'metadata', '-v7.3');
            if nargin >= 4 && ~isempty(logger)
                logger.log('SUCCESS', 'DMD_CALIBRATION_SAVED', ...
                    ['File=%s | Camera=%d | Serial=%s | Grid=%s | ', ...
                     'SelectedNumbers=%s | T=%s'], filePath, ...
                    calibration.camera_index, calibration.camera_serial, ...
                    calibration.grid_orientation, ...
                    mat2str(calibration.selected_numbers.'), ...
                    mat2str(calibration.T, 9));
            end
        end

        function calibration = loadCalibration(filePath, expectedCameraIndex)
            loaded = load(filePath);
            if isfield(loaded, 'metadata') && isstruct(loaded.metadata)
                calibration = loaded.metadata;
            elseif isfield(loaded, 'T')
                calibration = struct( ...
                    'schema_version', 'legacy_iDMD', ...
                    'created_at', '', ...
                    'camera_index', double(expectedCameraIndex), ...
                    'camera_serial', '', 'camera_bus', '', ...
                    'grid_orientation', 'legacy_unspecified', ...
                    'camera_points', zeros(0, 2), ...
                    'selected_numbers', zoulab.DmdCalibration.optionalField( ...
                        loaded, 'selected_numbers', zeros(0, 1)), ...
                    'points_standard', zeros(0, 2), ...
                    'T_points', zoulab.DmdCalibration.optionalField( ...
                        loaded, 'T_points', zeros(0, 0)), ...
                    'T_points_standard', zoulab.DmdCalibration.optionalField( ...
                        loaded, 'T_points_standard', zeros(0, 0)), ...
                    'T', loaded.T, 'source_image_file', char(string(filePath)), ...
                    'point_semantics', 'legacy iDMD file; camera mapping supplied by user');
            else
                error('ZouLab:DmdCalibrationFileInvalid', ...
                    'Calibration file does not contain T or metadata.');
            end
            zoulab.DmdCalibration.validateCalibration( ...
                calibration, expectedCameraIndex);
        end

        function validateCalibration(calibration, expectedCameraIndex)
            if ~isstruct(calibration) || ~isfield(calibration, 'T')
                error('ZouLab:DmdCalibrationInvalid', ...
                    'A DMD calibration matrix is required.');
            end
            validateattributes(calibration.T, {'numeric'}, ...
                {'size',[3 3],'finite','real'});
            if abs(det(double(calibration.T))) < eps
                error('ZouLab:DmdCalibrationSingular', ...
                    'The DMD calibration matrix is singular.');
            end
            if nargin >= 2 && isfield(calibration, 'camera_index') && ...
                    double(calibration.camera_index) ~= double(expectedCameraIndex)
                error('ZouLab:DmdCalibrationCameraMismatch', ...
                    'Calibration is for camera %d, not camera %d.', ...
                    calibration.camera_index, expectedCameraIndex);
            end
        end
    end

    methods (Static, Access = private)
        function writeGridManifest(folder, name, fileCount)
            fileNames = arrayfun(@(index) sprintf('%04d.bmp', index), ...
                1:fileCount, 'UniformOutput', false);
            manifest = struct('schema_version', '1.0.0', ...
                'created_utc', zoulab.BinInfo.utcNow(), ...
                'name', name, 'source', 'iDMD_calibration_grid', ...
                'folder', char(string(folder)), 'width', 1920, 'height', 1080, ...
                'bit_depth', 8, 'transfer_type', 2, ...
                'logical_mask_count', 1, 'upload_file_count', fileCount, ...
                'binary_frame_count_before_padding', fileCount * 8, ...
                'binary_frame_count', fileCount * 8, ...
                'required_binary_multiple', fileCount * 8, ...
                'padding_file_count', 0, 'padding_binary_frame_count', 0, ...
                'padding_file_indices', [], 'repeated_grid_file_indices', 2:fileCount, ...
                'file_names', {fileNames}, 'start_binary_position', 1, ...
                'calibration_file', '', ...
                'polarity', 'grid_white_bit255');
            zoulab.SessionManager.writeJson(fullfile(folder, ...
                'pattern_manifest.json'), manifest);
        end

        function clearGeneratedBmps(folder)
            files = dir(fullfile(folder, '*.bmp'));
            for index = 1:numel(files)
                if ~isempty(regexp(files(index).name, '^\d{4}\.bmp$', 'once'))
                    delete(fullfile(files(index).folder, files(index).name));
                end
            end
        end

        function value = optionalField(source, name, fallback)
            if isfield(source, name)
                value = source.(name);
            else
                value = fallback;
            end
        end
    end
end
