classdef LightStimulusController < handle
    %LIGHTSTIMULUSCONTROLLER Owns light/DMD stimulus configuration state.

    properties (SetAccess = private)
        Spec struct
        Armed logical = false
        State string = "OFF"
        LastPlan struct = struct()
    end

    methods
        function obj = LightStimulusController()
            obj.Spec = obj.defaultSpec();
        end

        function configure(obj, spec, logger)
            spec = obj.mergeSpec(spec);
            validationSpec = spec;
            requiredSeconds = spec.stimulus_delay_seconds + ...
                spec.stimulus_duration_seconds;
            selectedNames = intersect(string(spec.stimulus_light_names), ...
                ["Laser405", "Laser445"], 'stable');
            for laserName = selectedNames(:).'
                analogSpec = spec.analog_waveforms.(char(laserName));
                requiredSeconds = max(requiredSeconds, ...
                    analogSpec.delay_seconds + analogSpec.duration_seconds);
            end
            validationSpec.camera_window_seconds = max(requiredSeconds, 0.01);
            validationSpec.cameras = 1;
            validationSpec.imaging_light_lead_seconds = 0;
            validationSpec.imaging_light_tail_seconds = 0;
            validationSpec.imaging_light_names = strings(1, 0);
            validationSpec.light_stimulus_armed = true;
            % Editing the DMD controls is allowed before a pattern is
            % compiled.  Exact DMD trigger validation begins once a
            % manifest supplies a nonzero binary-frame count; Arm and
            % acquisition preflight still reject a missing manifest.
            validationSpec.dmd_armed = logical(spec.dmd_enabled) && ...
                obj.isExternalDmd(spec) && spec.dmd_trigger_count > 0;
            zoulab.StimulusWaveformCompiler.compile(validationSpec);
            obj.Spec = spec;
            logger.log('SUCCESS', 'LIGHT_STIMULUS_CONFIGURATION_VALIDATED', ...
                ['Sources=%s | DOWaveform=%s | Analog405=%s | Analog445=%s | ', ...
                 'Spec=%s'], strjoin(string(spec.stimulus_light_names), ','), ...
                spec.waveform_type, ...
                jsonencode(spec.analog_waveforms.Laser405), ...
                jsonencode(spec.analog_waveforms.Laser445), jsonencode(spec));
        end

        function arm(obj, dmdController, logger)
            if obj.Armed
                return;
            end
            if obj.Spec.dmd_enabled && obj.isExternalDmd(obj.Spec)
                if isempty(dmdController) || ~dmdController.Connected
                    error('ZouLab:DmdRequiredForLightStimulus', ...
                        'Connect the DMD and load a pattern before arming light stimulus.');
                end
                if startsWith(string(dmdController.State), "ARMED_EXTERNAL")
                    logger.log('INFO', 'DMD_EXTERNAL_ARM_REUSED', ...
                        'State=%s | NewHardwareCommandIssued=0', ...
                        dmdController.State);
                else
                    if startsWith(string(dmdController.State), "PLAYING") || ...
                            string(dmdController.State) == "PAUSED_INTERNAL"
                        dmdController.stop(logger);
                    end
                    dmdController.armExternal(obj.Spec.dmd_loop, logger);
                end
            end
            obj.Armed = true;
            obj.State = "ARMED";
            logger.log('SUCCESS', 'LIGHT_STIMULUS_ARMED', ...
                ['Sources=%s | DOWaveform=%s | DurationSeconds=%.6g | ', ...
                 'DelaySeconds=%.6g | Analog405=%s | Analog445=%s | ', ...
                 'DMDEnabled=%d | DMDPlayback=%s | DAQRequired=1'], ...
                strjoin(string(obj.Spec.stimulus_light_names), ','), ...
                obj.Spec.waveform_type, obj.Spec.stimulus_duration_seconds, ...
                obj.Spec.stimulus_delay_seconds, ...
                jsonencode(obj.Spec.analog_waveforms.Laser405), ...
                jsonencode(obj.Spec.analog_waveforms.Laser445), ...
                obj.Spec.dmd_enabled, ...
                obj.dmdModeText());
        end

        function disarm(obj, dmdController, logger)
            dmdStopped = false;
            if obj.Spec.dmd_enabled && obj.isExternalDmd(obj.Spec) && ...
                    ~isempty(dmdController) && dmdController.Connected
                dmdController.stop(logger);
                dmdStopped = true;
            end
            wasArmed = obj.Armed;
            obj.Armed = false;
            obj.State = "OFF";
            if wasArmed
                logger.log('INFO', 'LIGHT_STIMULUS_DISARMED', ...
                    ['DMDMode=%s | DMDStopped=%d | InternalPlaybackIndependent=%d | ', ...
                     'LaserTTLPlanCleared=1 | LaserAOPlanCleared=1 | ', ...
                     'AOHardwareSafeStateOwnedByDAQ=0V'], obj.dmdModeText(), ...
                    dmdStopped, obj.Spec.dmd_enabled && ...
                    ~obj.isExternalDmd(obj.Spec));
            end
        end

        function plan = compileAcquisitionPlan(obj, acquisitionSpec, channelNames, logger, previewDraft)
            if nargin < 5
                previewDraft = false;
            end
            spec = acquisitionSpec;
            includeStimulus = obj.Armed || logical(previewDraft);
            spec.light_stimulus_armed = includeStimulus;
            spec.stimulus_light_names = obj.Spec.stimulus_light_names;
            spec.waveform_type = obj.Spec.waveform_type;
            spec.digital_table_helper = obj.Spec.digital_table_helper;
            spec.stimulus_delay_seconds = obj.Spec.stimulus_delay_seconds;
            spec.light_stimulus_start_offset_seconds = ...
                obj.Spec.stimulus_delay_seconds;
            spec.stimulus_duration_seconds = obj.Spec.stimulus_duration_seconds;
            spec.pulse_width_seconds = obj.Spec.pulse_width_seconds;
            spec.pulse_period_seconds = obj.Spec.pulse_period_seconds;
            spec.digital_point_times_seconds = ...
                obj.Spec.digital_point_times_seconds;
            spec.digital_point_values = obj.Spec.digital_point_values;
            spec.digital_repeat_count = obj.Spec.digital_repeat_count;
            spec.digital_points_are_expanded = ...
                obj.Spec.digital_points_are_expanded;
            spec.custom_onsets_seconds = obj.Spec.custom_onsets_seconds;
            spec.custom_durations_seconds = obj.Spec.custom_durations_seconds;
            spec.analog_waveforms = obj.Spec.analog_waveforms;
            % A draft without a compiled DMD manifest remains useful for
            % previewing laser DO/AO.  Exact DMD pulses appear only when a
            % nonzero binary-frame count is available.
            spec.dmd_armed = includeStimulus && obj.Spec.dmd_enabled && ...
                obj.isExternalDmd(obj.Spec) && obj.Spec.dmd_trigger_count > 0;
            spec.dmd_frame_rate_hz = obj.Spec.dmd_frame_rate_hz;
            spec.dmd_trigger_count = obj.Spec.dmd_trigger_count;
            spec.dmd_trigger_times_seconds = ...
                obj.Spec.dmd_trigger_times_seconds;
            spec.dmd_trigger_frame_indices = ...
                obj.Spec.dmd_trigger_frame_indices;
            spec.dmd_trigger_point_times_seconds = ...
                obj.Spec.dmd_trigger_point_times_seconds;
            spec.dmd_trigger_point_values = ...
                obj.Spec.dmd_trigger_point_values;
            spec.dmd_trigger_points_are_expanded = ...
                obj.Spec.dmd_trigger_points_are_expanded;
            spec.dmd_trigger_repeat_count = ...
                obj.Spec.dmd_trigger_repeat_count;
            spec.dmd_trigger_cycle_seconds = ...
                obj.Spec.dmd_trigger_cycle_seconds;
            spec.dmd_trigger_width_seconds = obj.Spec.dmd_trigger_width_seconds;
            spec.dmd_start_offset_seconds = obj.Spec.dmd_start_offset_seconds;
            spec.dmd_repeat_to_fill_timeline = ...
                obj.Spec.dmd_repeat_to_fill_timeline;
            plan = zoulab.StimulusWaveformCompiler.compile(spec, channelNames);
            obj.LastPlan = plan;
            logger.log('INFO', 'DAQ_TIMELINE_COMPILED', ...
                ['DurationSeconds=%.6g | Rate=%.6g | Samples=%d | Channels=%s | ', ...
                 ['LightStimulusArmed=%d | DMDArmed=%d | DmdBinaryTriggers=%d | ', ...
                  'CameraTriggerSemantics=%s']], ...
                plan.duration_seconds, plan.sample_rate_hz, size(plan.output, 1), ...
                strjoin(plan.channel_names, ','), obj.Armed, spec.dmd_armed, ...
                round(spec.dmd_trigger_count), ...
                plan.camera_trigger_semantics);
        end

        function value = snapshot(obj)
            value = struct('state', char(obj.State), 'armed', obj.Armed, ...
                'spec', obj.Spec);
        end

        function secondsValue = requiredWindowSeconds(obj)
            secondsValue = obj.Spec.stimulus_delay_seconds + ...
                obj.Spec.stimulus_duration_seconds;
            selected = string(obj.Spec.stimulus_light_names);
            for laserName = intersect(selected, ["Laser405", "Laser445"], 'stable')
                analogSpec = obj.Spec.analog_waveforms.(char(laserName));
                secondsValue = max(secondsValue, ...
                    analogSpec.delay_seconds + analogSpec.duration_seconds);
            end
        end

        function secondsValue = digitalEndSeconds(obj)
            secondsValue = obj.Spec.stimulus_delay_seconds + ...
                obj.Spec.stimulus_duration_seconds;
        end
    end

    methods (Access = private)
        function spec = mergeSpec(obj, incoming)
            spec = obj.Spec;
            names = fieldnames(incoming);
            for k = 1:numel(names)
                spec.(names{k}) = incoming.(names{k});
            end
            spec.waveform_type = char(string(spec.waveform_type));
            spec.stimulus_light_names = cellstr(string(spec.stimulus_light_names));
            spec.custom_onsets_seconds = double(spec.custom_onsets_seconds(:).');
            spec.custom_durations_seconds = double(spec.custom_durations_seconds(:).');
            spec.digital_point_times_seconds = ...
                double(spec.digital_point_times_seconds(:).');
            spec.digital_point_values = double(spec.digital_point_values(:).');
            spec.digital_repeat_count = double(spec.digital_repeat_count);
            spec.dmd_trigger_times_seconds = ...
                double(spec.dmd_trigger_times_seconds(:).');
            spec.dmd_trigger_frame_indices = ...
                double(spec.dmd_trigger_frame_indices(:).');
            spec.dmd_trigger_point_times_seconds = ...
                double(spec.dmd_trigger_point_times_seconds(:).');
            spec.dmd_trigger_point_values = ...
                double(spec.dmd_trigger_point_values(:).');
            spec.dmd_trigger_repeat_count = double(spec.dmd_trigger_repeat_count);
            spec.dmd_trigger_cycle_seconds = double(spec.dmd_trigger_cycle_seconds);
            spec.dmd_enabled = logical(spec.dmd_enabled);
            spec.dmd_loop = logical(spec.dmd_loop);
            spec.dmd_trigger_mode = char(string(spec.dmd_trigger_mode));
            spec.dmd_trigger_count = double(spec.dmd_trigger_count);
            analogDefaults = zoulab.StimulusWaveformCompiler.defaultAnalogWaveforms();
            if ~isfield(spec, 'analog_waveforms') || ...
                    ~isstruct(spec.analog_waveforms)
                spec.analog_waveforms = analogDefaults;
            end
            laserNames = ["Laser405", "Laser445"];
            for laserName = laserNames
                field = char(laserName);
                if ~isfield(spec.analog_waveforms, field)
                    spec.analog_waveforms.(field) = analogDefaults.(field);
                else
                    entry = analogDefaults.(field);
                    incomingEntry = spec.analog_waveforms.(field);
                    entryNames = fieldnames(incomingEntry);
                    for entryIndex = 1:numel(entryNames)
                        entry.(entryNames{entryIndex}) = ...
                            incomingEntry.(entryNames{entryIndex});
                    end
                    entry.waveform_type = char(string(entry.waveform_type));
                    vectorFields = {'step_voltages','step_durations_seconds', ...
                        'custom_onsets_seconds','custom_durations_seconds', ...
                        'custom_voltages'};
                    for vectorIndex = 1:numel(vectorFields)
                        vectorField = vectorFields{vectorIndex};
                        vectorValue = entry.(vectorField);
                        entry.(vectorField) = double(vectorValue(:).');
                    end
                    spec.analog_waveforms.(field) = entry;
                end
            end
        end

        function value = dmdModeText(obj)
            if ~obj.Spec.dmd_enabled
                value = 'disabled';
            elseif ~obj.isExternalDmd(obj.Spec)
                value = 'internal_independent';
            elseif obj.Spec.dmd_loop
                value = 'external_loop';
            else
                value = 'external_single';
            end
        end
    end

    methods (Static)
        function spec = defaultSpec()
            spec = struct( ...
                'stimulus_light_names', {{'Laser405'}}, ...
                'waveform_type', 'Step', ...
                'digital_table_helper', 'ON/OFF cycles', ...
                'stimulus_delay_seconds', 0, ...
                'stimulus_duration_seconds', 1, ...
                'pulse_width_seconds', 0.1, ...
                'pulse_period_seconds', 1, ...
                'digital_point_times_seconds', [0 0 0.1 0.1 1], ...
                'digital_point_values', [0 1 1 0 0], ...
                'digital_repeat_count', 1, ...
                'digital_points_are_expanded', true, ...
                'custom_onsets_seconds', zeros(1, 0), ...
                'custom_durations_seconds', zeros(1, 0), ...
                'analog_waveforms', ...
                    zoulab.StimulusWaveformCompiler.defaultAnalogWaveforms(), ...
                'dmd_enabled', true, ...
                'dmd_trigger_mode', 'Internal', ...
                'dmd_pattern', 'ALL_OFF', ...
                'dmd_loop', true, ...
                'dmd_frame_rate_hz', 10, ...
                'dmd_trigger_count', 0, ...
                'dmd_trigger_times_seconds', zeros(1, 0), ...
                'dmd_trigger_frame_indices', zeros(1, 0), ...
                'dmd_trigger_point_times_seconds', zeros(1, 0), ...
                'dmd_trigger_point_values', zeros(1, 0), ...
                'dmd_trigger_points_are_expanded', true, ...
                'dmd_trigger_repeat_count', 1, ...
                'dmd_trigger_cycle_seconds', 0.1, ...
                'dmd_trigger_width_seconds', 0.001, ...
                'dmd_start_offset_seconds', 0, ...
                'dmd_repeat_to_fill_timeline', false);
        end

        function value = isExternalDmd(spec)
            value = isfield(spec, 'dmd_trigger_mode') && ...
                string(spec.dmd_trigger_mode) == "External IN1";
        end
    end
end
