classdef ParallelTiffConverter
    %PARALLELTIFFCONVERTER Background Record post-processing engine.
    %
    % Visual BIN physical cropping and optional TIFF conversion run after
    % every acquisition Cycle has completed. Independent Cycles may crop in
    % parallel; each TIFF worker exclusively owns one output TIFF.

    properties (Constant)
        MaxWorkers = 8
        BufferBytesPerWorker = 256 * 1024^2
        EstimatedMatlabBytesPerWorker = 1.5 * 1024^3
        ReservedSystemAndCoordinatorBytes = 6 * 1024^3
        ProgressIntervalFrames = 250
    end

    methods (Static)
        function [job, config] = submit(recordPath, plan, projectRoot)
            config = zoulab.ParallelTiffConverter.prepare( ...
                recordPath, plan, projectRoot);
            configPath = string(fullfile(recordPath, ...
                'record_conversion_job.mat'));
            save(configPath, 'config', '-v7');
            zoulab.ParallelTiffConverter.writeInitialManifest(config);

            cluster = parcluster('Processes');
            if config.convert_to_tiff || config.crop_visual_bins
                job = batch(cluster, @zoulab.ParallelTiffConverter.run, 0, ...
                    {char(configPath)}, 'Pool', config.worker_count, ...
                    'AutoAddClientPath', true, ...
                    'AdditionalPaths', {char(projectRoot)});
            else
                job = batch(cluster, @zoulab.ParallelTiffConverter.run, 0, ...
                    {char(configPath)}, 'AutoAddClientPath', true, ...
                    'AdditionalPaths', {char(projectRoot)});
            end
        end

        function config = prepare(recordPath, plan, projectRoot)
            recordPath = string(recordPath);
            projectRoot = string(projectRoot);
            cropRequested = isfield(plan, 'visual_stimulus_armed') && ...
                logical(plan.visual_stimulus_armed);
            convertRequested = isfield(plan, 'convert_record_to_tiff') && ...
                logical(plan.convert_record_to_tiff);
            unitTemplate = struct('index', 0, 'cycle', 0, 'camera', 0, ...
                'expected_frames', 0, 'bytes_per_frame', 0, ...
                'bin_info_files', {{}}, 'source_bin_files', {{}}, ...
                'output_path', '', 'frame_range', [], ...
                'crop_required', cropRequested, ...
                'crop_status', 'not_requested', 'crop_error', '');
            units = repmat(unitTemplate, 0, 1);
            for cycleIndex = 1:plan.cycles
                cyclePath = string(fullfile(recordPath, ...
                    sprintf('Cycle%d', cycleIndex)));
                loaded = load(fullfile(cyclePath, ...
                    'record_stream_manifest.mat'), 'manifest');
                for cameraIndex = plan.cameras
                    position = find([loaded.manifest.cameras.camera] == ...
                        cameraIndex, 1);
                    if isempty(position)
                        error('ZouLab:RecordConversionCameraMissing', ...
                            'Cycle %d has no Camera %d stream manifest.', ...
                            cycleIndex, cameraIndex);
                    end
                    cameraManifest = loaded.manifest.cameras(position);
                    infoFiles = string(cameraManifest.bin_info_files);
                    [~, binFiles, frameSize, frameCount] = ...
                        zoulab.BinInfo.loadAndValidate(infoFiles);
                    frameRange = [];
                    expectedFrames = frameCount;
                    if isfield(cameraManifest, 'visual_alignment') && ...
                            isfield(cameraManifest.visual_alignment, ...
                            'applied_frame_range') && ...
                            isfield(cameraManifest.visual_alignment, ...
                            'valid_frame_count')
                        frameRange = double(cameraManifest.visual_alignment. ...
                            applied_frame_range);
                        expectedFrames = double(cameraManifest.visual_alignment. ...
                            valid_frame_count);
                    end
                    cropStatus = 'not_requested';
                    if cropRequested
                        cropStatus = 'pending';
                    end
                    units(end + 1, 1) = struct( ... %#ok<AGROW>
                        'index', numel(units) + 1, ...
                        'cycle', cycleIndex, 'camera', cameraIndex, ...
                        'expected_frames', expectedFrames, ...
                        'bytes_per_frame', prod(frameSize) * 2, ...
                        'bin_info_files', {cellstr(infoFiles)}, ...
                        'source_bin_files', {cellstr(binFiles)}, ...
                        'output_path', char(fullfile(fileparts(infoFiles(1)), ...
                            'Rec.tif')), 'frame_range', frameRange, ...
                        'crop_required', cropRequested, ...
                        'crop_status', cropStatus, 'crop_error', '');
                end
            end
            if isempty(units)
                error('ZouLab:RecordConversionUnitsEmpty', ...
                    'No Cycle-by-Camera TIFF conversion units were found.');
            end

            stageUnitCounts = zeros(1, 0);
            if cropRequested
                stageUnitCounts(end + 1) = plan.cycles; %#ok<AGROW>
            end
            if convertRequested
                stageUnitCounts(end + 1) = numel(units); %#ok<AGROW>
            end
            if isempty(stageUnitCounts)
                maximumStageConcurrency = 1;
            else
                maximumStageConcurrency = max(stageUnitCounts);
            end
            cluster = parcluster('Processes');
            selection = zoulab.ParallelTiffConverter.selectWorkerCount( ...
                maximumStageConcurrency, cluster.NumWorkers);
            availableBytes = selection.available_memory_bytes;
            perWorkerBytes = selection.estimated_bytes_per_worker;
            coreCount = selection.physical_core_count;
            workerCount = selection.worker_count;

            progressFolder = string(fullfile(recordPath, ...
                'record_postprocessing_progress'));
            if ~exist(progressFolder, 'dir')
                mkdir(progressFolder);
            end
            cropCycles = zeros(1, 0);
            if cropRequested
                cropCycles = 1:plan.cycles;
            end
            conversionFrames = double(convertRequested) * ...
                sum([units.expected_frames]);
            cropFrames = double(cropRequested) * ...
                sum([units.expected_frames]);
            totalWorkUnits = numel(cropCycles) + ...
                double(convertRequested) * numel(units);
            totalBytes = (double(cropRequested) + ...
                double(convertRequested)) * ...
                sum([units.expected_frames] .* [units.bytes_per_frame]);
            nowValue = datetime('now');
            config = struct( ...
                'schema_version', '1.0.0', ...
                'kind', 'zoulab_record_postprocessing_job', ...
                'record_path', char(recordPath), ...
                'project_root', char(projectRoot), ...
                'progress_folder', char(progressFolder), ...
                'stage_path', char(fullfile(progressFolder, ...
                    'postprocessing_stage.json')), ...
                'submitted_at', char(nowValue, ...
                    'yyyy-MM-dd HH:mm:ss.SSS'), ...
                'submitted_posix', posixtime(nowValue), ...
                'worker_count', workerCount, ...
                'worker_limit', ...
                    zoulab.ParallelTiffConverter.MaxWorkers, ...
                'cluster_total_worker_limit', ...
                    selection.cluster_total_worker_limit, ...
                'coordinator_worker_count', ...
                    selection.coordinator_worker_count, ...
                'pool_worker_capacity', ...
                    selection.pool_worker_capacity, ...
                'maximum_stage_concurrency', maximumStageConcurrency, ...
                'physical_core_count', coreCount, ...
                'available_memory_bytes_at_submit', availableBytes, ...
                'reserved_memory_bytes', ...
                    zoulab.ParallelTiffConverter. ...
                    ReservedSystemAndCoordinatorBytes, ...
                'estimated_bytes_per_worker', perWorkerBytes, ...
                'buffer_bytes_per_worker', ...
                    zoulab.ParallelTiffConverter.BufferBytesPerWorker, ...
                'read_mode', 'fread', ...
                'read_mode_basis', ...
                    'local benchmark: memmap lacked >=5% advantage', ...
                'unit_policy', 'cycle_camera_exclusive_output', ...
                'crop_visual_bins', cropRequested, ...
                'convert_to_tiff', convertRequested, ...
                'crop_cycles', cropCycles, ...
                'crop_frame_total', cropFrames, ...
                'conversion_frame_total', conversionFrames, ...
                'total_units', totalWorkUnits, ...
                'total_frames', cropFrames + conversionFrames, ...
                'total_bytes', totalBytes, ...
                'plan_cycles', plan.cycles, ...
                'units', units);
        end

        function selection = selectWorkerCount(unitCount, clusterTotalWorkerLimit)
            validateattributes(unitCount, {'numeric'}, ...
                {'scalar','finite','integer','positive'});
            if nargin < 2
                cluster = parcluster('Processes');
                clusterTotalWorkerLimit = cluster.NumWorkers;
            end
            validateattributes(clusterTotalWorkerLimit, {'numeric'}, ...
                {'scalar','finite','integer','positive'});
            availableBytes = ...
                zoulab.ParallelTiffConverter.availablePhysicalMemoryBytes();
            perWorkerBytes = ...
                zoulab.ParallelTiffConverter.EstimatedMatlabBytesPerWorker + ...
                zoulab.ParallelTiffConverter.BufferBytesPerWorker;
            usableBytes = max(0, availableBytes - ...
                zoulab.ParallelTiffConverter.ReservedSystemAndCoordinatorBytes);
            memoryWorkers = max(1, floor(usableBytes / perWorkerBytes));
            coreCount = zoulab.ParallelTiffConverter.physicalCoreCount();
            coordinatorWorkerCount = 1;
            poolWorkerCapacity = max(1, double(clusterTotalWorkerLimit) - ...
                coordinatorWorkerCount);
            physicalPoolCapacity = max(1, coreCount - ...
                coordinatorWorkerCount);
            workerCount = max(1, min([ ...
                zoulab.ParallelTiffConverter.MaxWorkers, poolWorkerCapacity, ...
                physicalPoolCapacity, ...
                double(unitCount), memoryWorkers]));
            selection = struct('worker_count', workerCount, ...
                'worker_limit', ...
                    zoulab.ParallelTiffConverter.MaxWorkers, ...
                'cluster_total_worker_limit', ...
                    double(clusterTotalWorkerLimit), ...
                'coordinator_worker_count', coordinatorWorkerCount, ...
                'pool_worker_capacity', poolWorkerCapacity, ...
                'physical_core_count', coreCount, ...
                'memory_limited_worker_count', memoryWorkers, ...
                'available_memory_bytes', availableBytes, ...
                'reserved_memory_bytes', ...
                    zoulab.ParallelTiffConverter. ...
                    ReservedSystemAndCoordinatorBytes, ...
                'estimated_bytes_per_worker', perWorkerBytes, ...
                'buffer_bytes_per_worker', ...
                    zoulab.ParallelTiffConverter.BufferBytesPerWorker, ...
                'estimated_process_memory_bytes', ...
                    workerCount * perWorkerBytes + ...
                    zoulab.ParallelTiffConverter. ...
                    EstimatedMatlabBytesPerWorker);
        end

        function run(configPath)
            loaded = load(configPath, 'config');
            config = loaded.config;
            coordinatorLogger = zoulab.AppLogger(fullfile( ...
                config.progress_folder, 'coordinator_log'));
            cleanup = onCleanup(@() coordinatorLogger.close()); %#ok<NASGU>
            coordinatorLogger.log('INFO', ...
                'RECORD_POSTPROCESSING_BEGIN', ...
                ['RecordPath=%s | CropVisualBins=%d | ConvertToTiff=%d | ', ...
                 'WorkUnits=%d | PoolWorkers=%d | CoordinatorWorkers=%d | ', ...
                 'ClusterTotalWorkerLimit=%d | WorkerLimit=%d | ', ...
                 'ReadMode=%s | BufferBytesPerWorker=%.0f | ', ...
                 'CropExecution=parallel_by_cycle_before_optional_tiff'], ...
                config.record_path, config.crop_visual_bins, ...
                config.convert_to_tiff, config.total_units, ...
                config.worker_count, config.coordinator_worker_count, ...
                config.cluster_total_worker_limit, config.worker_limit, ...
                config.read_mode, ...
                config.buffer_bytes_per_worker);

            [config, cropResults] = ...
                zoulab.ParallelTiffConverter.runCropStage( ...
                config, coordinatorLogger);

            resultTemplate = zoulab.ParallelTiffConverter.resultTemplate();
            results = repmat(resultTemplate, 0, 1);
            if config.convert_to_tiff
                zoulab.ParallelTiffConverter.writeStage(config, ...
                    'converting_tiff', numel(config.crop_cycles), ...
                    numel(config.crop_cycles), 0, '', '');
                units = config.units;
                results = repmat(resultTemplate, numel(units), 1);
                parfor unitIndex = 1:numel(units)
                    results(unitIndex) = ...
                        zoulab.ParallelTiffConverter.convertUnit( ...
                        units(unitIndex), config);
                end
            end
            final = zoulab.ParallelTiffConverter.persistFinal( ...
                config, cropResults, results);
            zoulab.ParallelTiffConverter.writeStage(config, ...
                char(final.status), numel(config.crop_cycles), ...
                numel(config.crop_cycles), 0, final.error, '');
            if any(string(final.status) == ["complete", ...
                    "complete_with_source_bin_retained"])
                coordinatorLogger.log('SUCCESS', ...
                    'RECORD_POSTPROCESSING_COMPLETE', ...
                    ['Status=%s | CompletedUnits=%d/%d | ', ...
                     'CroppedCycles=%d/%d | ConvertedFrames=%d'], ...
                    final.status, ...
                    final.completed_units, final.total_units, ...
                    final.crop_completed_cycles, final.crop_total_cycles, ...
                    final.converted_frames);
            else
                coordinatorLogger.log('ERROR', ...
                    'RECORD_POSTPROCESSING_INCOMPLETE', ...
                    'Status=%s | Error=%s', final.status, final.error);
            end
        end

        function progress = readProgress(config)
            framesDone = 0;
            completedConversionUnits = 0;
            errorUnits = 0;
            activeUnits = 0;
            if config.convert_to_tiff
                for unitIndex = 1:numel(config.units)
                    path = zoulab.ParallelTiffConverter.progressPath( ...
                        config, unitIndex);
                    if ~isfile(path)
                        continue;
                    end
                    try
                        value = jsondecode(fileread(path));
                        framesDone = framesDone + min( ...
                            double(value.frames_done), ...
                            double(value.frames_total));
                        status = string(value.status);
                        completedConversionUnits = ...
                            completedConversionUnits + any(status == ...
                            ["complete","complete_with_source_bin_retained"]);
                        errorUnits = errorUnits + startsWith(status, "error");
                        activeUnits = activeUnits + status == "converting";
                    catch
                    end
                end
            end
            stage = struct('status', 'queued', ...
                'completed_crop_cycles', 0, 'total_crop_cycles', ...
                numel(config.crop_cycles), 'current_cycle', 0, ...
                'error_count', 0, 'detail', '');
            if isfile(config.stage_path)
                try
                    stage = jsondecode(fileread(config.stage_path));
                catch
                end
            end
            cropDone = 0;
            cropActive = 0;
            cropErrors = 0;
            for cycleIndex = config.crop_cycles
                cropPath = zoulab.ParallelTiffConverter.cropProgressPath( ...
                    config, cycleIndex);
                if ~isfile(cropPath)
                    continue;
                end
                try
                    cropValue = jsondecode(fileread(cropPath));
                    cropStatus = string(cropValue.status);
                    cropDone = cropDone + any(cropStatus == ...
                        ["complete","error_original_bin_preserved"]);
                    cropActive = cropActive + cropStatus == "cropping";
                    cropErrors = cropErrors + startsWith(cropStatus, "error");
                catch
                end
            end
            cropDone = max(cropDone, min( ...
                double(stage.completed_crop_cycles), ...
                numel(config.crop_cycles)));
            conversionWork = 0;
            for unitIndex = 1:numel(config.units)
                if ~config.convert_to_tiff
                    break;
                end
                path = zoulab.ParallelTiffConverter.progressPath( ...
                    config, unitIndex);
                if ~isfile(path)
                    continue;
                end
                try
                    value = jsondecode(fileread(path));
                    conversionWork = conversionWork + min(1, ...
                        double(value.frames_done) / ...
                        max(1, double(value.frames_total)));
                    if startsWith(string(value.status), "error")
                        conversionWork = conversionWork + ...
                            double(value.frames_done == 0);
                    end
                catch
                end
            end
            fraction = min(1, (cropDone + conversionWork) / ...
                max(1, config.total_units));
            elapsed = max(0, posixtime(datetime('now')) - ...
                double(config.submitted_posix));
            if fraction > 0 && fraction < 1
                eta = elapsed * (1 - fraction) / fraction;
            elseif fraction >= 1
                eta = 0;
            else
                eta = NaN;
            end
            progress = struct('frames_done', framesDone, ...
                'frames_total', config.total_frames, ...
                'bytes_done', NaN, ...
                'bytes_total', config.total_bytes, ...
                'fraction', fraction, 'elapsed_seconds', elapsed, ...
                'eta_seconds', eta, 'completed_units', ...
                    cropDone + completedConversionUnits, ...
                'total_units', config.total_units, ...
                'active_units', activeUnits + cropActive, ...
                'error_units', errorUnits + cropErrors + ...
                    double(stage.error_count), ...
                'stage', char(string(stage.status)), ...
                'stage_detail', char(string(stage.detail)), ...
                'current_cycle', double(stage.current_cycle));
        end

        function result = loadFinal(recordPath)
            path = string(fullfile(recordPath, ...
                'record_postprocessing_manifest.mat'));
            if ~isfile(path)
                path = string(fullfile(recordPath, ...
                    'record_conversion_manifest.mat'));
            end
            if ~isfile(path)
                result = struct();
                return;
            end
            loaded = load(path, 'manifest');
            result = loaded.manifest;
        end
    end

    methods (Static, Access = private)
        function [config, results] = runCropStage(config, logger)
            template = struct('cycle', 0, 'status', 'not_requested', ...
                'started_at', '', 'completed_at', '', ...
                'source_frames', 0, 'stored_frames', 0, ...
                'removed_frames', 0, 'error_identifier', '', 'error', '');
            results = repmat(template, numel(config.crop_cycles), 1);
            if ~config.crop_visual_bins
                zoulab.ParallelTiffConverter.writeStage(config, ...
                    'crop_not_requested', 0, 0, 0, '', '');
                return;
            end
            zoulab.ParallelTiffConverter.writeStage(config, ...
                'cropping_bin', 0, numel(config.crop_cycles), 0, ...
                sprintf('Cropping %d Cycle(s) in the process pool.', ...
                numel(config.crop_cycles)), '');
            manifests = cell(numel(config.crop_cycles), 1);
            cropCycles = config.crop_cycles;
            if numel(cropCycles) == 1
                [results(1), manifests{1}] = ...
                    zoulab.ParallelTiffConverter.cropOneCycle( ...
                    config, cropCycles(1), template);
            else
                parfor position = 1:numel(cropCycles)
                    [results(position), manifests{position}] = ...
                        zoulab.ParallelTiffConverter.cropOneCycle( ...
                        config, cropCycles(position), template);
                end
            end
            errorCount = 0;
            completedCount = 0;
            for position = 1:numel(cropCycles)
                cycleIndex = cropCycles(position);
                result = results(position);
                manifest = manifests{position};
                cyclePath = string(fullfile(config.record_path, ...
                    sprintf('Cycle%d', cycleIndex)));
                if strcmp(result.status, 'complete')
                    completedCount = completedCount + 1;
                    config = zoulab.ParallelTiffConverter. ...
                        refreshCycleUnitsAfterCrop(config, manifest, cycleIndex);
                else
                    errorCount = errorCount + 1;
                    config = zoulab.ParallelTiffConverter. ...
                        markCycleUnitsCropFailed(config, cycleIndex, result.error);
                end
                if ~isempty(fieldnames(manifest))
                    zoulab.ParallelTiffConverter.writeCycleStreamManifest( ...
                        cyclePath, manifest);
                    zoulab.ParallelTiffConverter. ...
                        updateVisualStimulusCropManifest(cyclePath, manifest);
                end
            end
            if config.convert_to_tiff
                nextStage = 'converting_tiff';
            elseif errorCount > 0
                nextStage = 'partial_error';
            else
                nextStage = 'crop_complete';
            end
            zoulab.ParallelTiffConverter.writeStage(config, nextStage, ...
                numel(config.crop_cycles), numel(config.crop_cycles), 0, ...
                'BIN crop stage finished.', '');
        end

        function [result, manifest] = cropOneCycle(config, cycleIndex, template)
            result = template;
            result.cycle = cycleIndex;
            result.status = 'cropping';
            result.started_at = zoulab.ParallelTiffConverter.timestamp();
            manifest = struct();
            progressPath = zoulab.ParallelTiffConverter.cropProgressPath( ...
                config, cycleIndex);
            zoulab.SessionManager.writeJson(progressPath, struct( ...
                'cycle', cycleIndex, 'status', 'cropping', ...
                'started_at', result.started_at, 'completed_at', '', ...
                'error', ''));
            logFolder = fullfile(config.progress_folder, sprintf( ...
                'crop_cycle_%03d_log', cycleIndex));
            workerLogger = zoulab.AppLogger(logFolder);
            cleanup = onCleanup(@() workerLogger.close()); %#ok<NASGU>
            cyclePath = string(fullfile(config.record_path, ...
                sprintf('Cycle%d', cycleIndex)));
            streamPath = string(fullfile(cyclePath, ...
                'record_stream_manifest.mat'));
            try
                loaded = load(streamPath, 'manifest');
                manifest = loaded.manifest;
                if ~isfield(manifest, 'visual_alignment') || ...
                        ~isfield(manifest.visual_alignment, ...
                        'all_cameras_valid') || ...
                        ~manifest.visual_alignment.all_cameras_valid
                    error('ZouLab:VisualCropAlignmentInvalid', ...
                        ['Cycle %d has no valid all-camera visual alignment; ', ...
                         'original BIN files are retained.'], cycleIndex);
                end
                sourceFrames = sum([manifest.cameras.written_frames]);
                manifest = zoulab.VisualBinCropper.apply(manifest, ...
                    [manifest.cameras.camera], workerLogger);
                storedFrames = sum([manifest.cameras.written_frames]);
                result.status = 'complete';
                result.source_frames = sourceFrames;
                result.stored_frames = storedFrames;
                result.removed_frames = sourceFrames - storedFrames;
                if isfield(manifest, 'postprocessing')
                    if config.convert_to_tiff
                        manifest.postprocessing.status = ...
                            'crop_complete_tiff_pending';
                    else
                        manifest.postprocessing.status = 'complete';
                    end
                end
                workerLogger.log('SUCCESS', ...
                    'RECORD_POSTPROCESSING_CYCLE_CROP_COMPLETE', ...
                    ['Cycle=%d | SourceFrames=%d | StoredFrames=%d | ', ...
                     'RemovedFrames=%d | TiffPending=%d'], cycleIndex, ...
                    sourceFrames, storedFrames, sourceFrames - storedFrames, ...
                    config.convert_to_tiff);
            catch ME
                result.status = 'error_original_bin_preserved';
                result.error_identifier = ME.identifier;
                result.error = ME.message;
                if ~isempty(fieldnames(manifest))
                    manifest.visual_physical_crop = struct( ...
                        'schema_version', '1.1.0', ...
                        'status', 'error_original_bin_preserved', ...
                        'completed_utc', zoulab.BinInfo.utcNow(), ...
                        'error_identifier', ME.identifier, ...
                        'error', ME.message);
                    if isfield(manifest, 'postprocessing')
                        manifest.postprocessing.status = ...
                            'crop_error_original_bin_preserved';
                        manifest.postprocessing.error = ME.message;
                    end
                end
                workerLogger.logException( ...
                    'RECORD_POSTPROCESSING_CYCLE_CROP_FAILED', ME);
            end
            result.completed_at = zoulab.ParallelTiffConverter.timestamp();
            zoulab.SessionManager.writeJson(progressPath, struct( ...
                'cycle', cycleIndex, 'status', result.status, ...
                'started_at', result.started_at, ...
                'completed_at', result.completed_at, ...
                'error', result.error));
        end

        function config = refreshCycleUnitsAfterCrop(config, manifest, cycleIndex)
            unitIndices = find([config.units.cycle] == cycleIndex);
            for unitIndex = unitIndices
                cameraIndex = config.units(unitIndex).camera;
                position = find([manifest.cameras.camera] == cameraIndex, 1);
                cameraManifest = manifest.cameras(position);
                infoFiles = string(cameraManifest.bin_info_files);
                [~, binFiles, frameSize, frameCount] = ...
                    zoulab.BinInfo.loadAndValidate(infoFiles);
                config.units(unitIndex).expected_frames = frameCount;
                config.units(unitIndex).bytes_per_frame = prod(frameSize) * 2;
                config.units(unitIndex).bin_info_files = cellstr(infoFiles);
                config.units(unitIndex).source_bin_files = cellstr(binFiles);
                config.units(unitIndex).frame_range = [];
                config.units(unitIndex).crop_status = 'complete';
                config.units(unitIndex).crop_error = '';
            end
        end

        function config = markCycleUnitsCropFailed(config, cycleIndex, errorText)
            unitIndices = find([config.units.cycle] == cycleIndex);
            for unitIndex = unitIndices
                config.units(unitIndex).crop_status = 'error';
                config.units(unitIndex).crop_error = char(string(errorText));
            end
        end

        function writeCycleStreamManifest(cyclePath, manifest)
            zoulab.SessionManager.writeMatManifest(fullfile(cyclePath, ...
                'record_stream_manifest.mat'), manifest);
            zoulab.SessionManager.writeJson(fullfile(cyclePath, ...
                'record_stream_manifest.json'), manifest);
        end

        function updateVisualStimulusCropManifest(cyclePath, streamManifest)
            path = string(fullfile(cyclePath, ...
                'visual_stimulus_manifest.json'));
            if ~isfile(path) || ...
                    ~isfield(streamManifest, 'visual_physical_crop')
                return;
            end
            value = jsondecode(fileread(path));
            value.visual_bin_physical_crop = ...
                streamManifest.visual_physical_crop;
            value.updated_at = zoulab.ParallelTiffConverter.timestamp();
            zoulab.SessionManager.writeJson(path, value);
        end

        function result = convertUnit(unit, config)
            result = zoulab.ParallelTiffConverter.resultTemplate();
            result.cycle = unit.cycle;
            result.camera = unit.camera;
            result.expected_frames = unit.expected_frames;
            result.bin_info_files = unit.bin_info_files;
            result.source_bin_files = unit.source_bin_files;
            result.started_at = zoulab.ParallelTiffConverter.timestamp();
            if unit.crop_required && string(unit.crop_status) ~= "complete"
                result.status = 'error_source_bin_retained';
                result.error = sprintf( ...
                    'TIFF conversion skipped because required BIN crop failed: %s', ...
                    unit.crop_error);
                result.completed_at = ...
                    zoulab.ParallelTiffConverter.timestamp();
                zoulab.ParallelTiffConverter.writeUnitProgress( ...
                    config, unit, 0, result.status, result.error, ...
                    result.started_at);
                return;
            end
            result.status = 'converting';
            zoulab.ParallelTiffConverter.writeUnitProgress( ...
                config, unit, 0, 'converting', '', result.started_at);
            logFolder = fullfile(config.progress_folder, sprintf( ...
                'unit_%03d_log', unit.index));
            logger = zoulab.AppLogger(logFolder);
            loggerCleanup = onCleanup(@() logger.close()); %#ok<NASGU>
            readOptions = struct('mode', config.read_mode, ...
                'buffer_bytes', config.buffer_bytes_per_worker, ...
                'progress_interval_frames', ...
                    zoulab.ParallelTiffConverter.ProgressIntervalFrames);
            try
                progressFcn = @(done, total, stack, stackTotal) ...
                    zoulab.ParallelTiffConverter.writeUnitProgress( ...
                    config, unit, done, 'converting', sprintf( ...
                    'Stack %d/%d', stack, stackTotal), result.started_at);
                [tiffFiles, written, validatedBinFiles] = ...
                    zoulab.TiffStackWriter.writeFromBinInfo( ...
                    string(unit.bin_info_files), unit.output_path, logger, ...
                    progressFcn, [], unit.frame_range, readOptions);
                if written ~= unit.expected_frames
                    error('ZouLab:ParallelTiffFrameCountMismatch', ...
                        'Unit wrote %d frames; %d expected.', written, ...
                        unit.expected_frames);
                end
                zoulab.BinInfo.markConversion( ...
                    string(unit.bin_info_files), 'complete', tiffFiles, '');
                retained = strings(1, 0);
                for fileIndex = 1:numel(validatedBinFiles)
                    try
                        delete(validatedBinFiles(fileIndex));
                    catch
                        retained(end + 1) = validatedBinFiles(fileIndex); %#ok<AGROW>
                    end
                end
                result.written_frames = written;
                result.tiff_files = cellstr(tiffFiles);
                result.source_bin_deleted = isempty(retained);
                if isempty(retained)
                    result.status = 'complete';
                else
                    result.status = 'complete_with_source_bin_retained';
                    result.error = sprintf( ...
                        'TIFF verified but BIN deletion failed: %s', ...
                        strjoin(retained, ','));
                    zoulab.BinInfo.markConversion( ...
                        string(unit.bin_info_files), result.status, ...
                        tiffFiles, result.error);
                end
            catch ME
                result.status = 'error_source_bin_retained';
                result.error = ME.message;
                result.partial_tiff_files_deleted = cellstr( ...
                    zoulab.ParallelTiffConverter.deletePartialTiffs( ...
                    unit.output_path));
                try
                    zoulab.BinInfo.markConversion( ...
                        string(unit.bin_info_files), result.status, ...
                        strings(1, 0), ME.message);
                catch
                end
                logger.logException('PARALLEL_TIFF_UNIT_FAILED', ME);
            end
            result.completed_at = ...
                zoulab.ParallelTiffConverter.timestamp();
            zoulab.ParallelTiffConverter.writeUnitProgress( ...
                config, unit, result.written_frames, result.status, ...
                result.error, result.started_at);
        end

        function final = persistFinal(config, cropResults, results)
            cropStatuses = string({cropResults.status});
            cropComplete = cropStatuses == "complete";
            cropOK = ~config.crop_visual_bins || ...
                (~isempty(cropResults) && all(cropComplete));
            conversionStatuses = string({results.status});
            conversionComplete = ismember(conversionStatuses, ...
                ["complete","complete_with_source_bin_retained"]);
            conversionOK = ~config.convert_to_tiff || ...
                (~isempty(results) && all(conversionComplete));
            retainedWarning = config.convert_to_tiff && conversionOK && ...
                any(conversionStatuses == "complete_with_source_bin_retained");
            errors = strings(1, 0);
            if ~cropOK
                cropErrors = string({cropResults.error});
                cropErrors = cropErrors(strlength(cropErrors) > 0);
                if isempty(cropErrors)
                    cropErrors = "One or more visual BIN crop cycles failed.";
                end
                errors(end + 1) = strjoin(cropErrors, ' | '); %#ok<AGROW>
            end
            if ~conversionOK
                conversionErrors = string({results.error});
                conversionErrors = conversionErrors( ...
                    strlength(conversionErrors) > 0);
                if isempty(conversionErrors)
                    conversionErrors = ...
                        "One or more Cycle-by-Camera TIFF units failed.";
                end
                errors(end + 1) = strjoin(conversionErrors, ' | '); %#ok<AGROW>
            end
            if cropOK && conversionOK
                if retainedWarning
                    overallStatus = 'complete_with_source_bin_retained';
                    errors(end + 1) = [ ...
                        "All TIFF files verified; one or more source BIN " ...
                        "files could not be deleted."]; %#ok<AGROW>
                else
                    overallStatus = 'complete';
                end
            else
                overallStatus = 'partial_error';
            end
            errorText = char(strjoin(unique(errors, 'stable'), ' | '));
            convertedFrames = sum([results.written_frames]);
            completedUnits = sum(cropComplete) + sum(conversionComplete);
            final = struct('schema_version', '2.0.0', ...
                'kind', 'record_post_capture_processing', ...
                'status', overallStatus, ...
                'started_at', config.submitted_at, ...
                'completed_at', zoulab.ParallelTiffConverter.timestamp(), ...
                'capture_all_cycles_completed_before_postprocessing', true, ...
                'execution', ...
                    'background_batch_crop_then_optional_process_pool', ...
                'unit_policy', config.unit_policy, ...
                'physical_bin_crop_requested', config.crop_visual_bins, ...
                'crop_total_cycles', numel(config.crop_cycles), ...
                'crop_completed_cycles', sum(cropComplete), ...
                'crop_results', cropResults, ...
                'tiff_conversion_requested', config.convert_to_tiff, ...
                'exclusive_output_file_per_worker', ...
                    logical(config.convert_to_tiff), ...
                'worker_count', config.worker_count, ...
                'worker_limit', config.worker_limit, ...
                'read_mode', config.read_mode, ...
                'buffer_bytes_per_worker', config.buffer_bytes_per_worker, ...
                'total_units', config.total_units, ...
                'completed_units', completedUnits, ...
                'total_frames', config.total_frames, ...
                'converted_frames', convertedFrames, ...
                'progress_fraction', completedUnits / ...
                    max(1, config.total_units), ...
                'units', results, 'error', errorText, ...
                'plan_cycles', config.plan_cycles);
            zoulab.ParallelTiffConverter.writeManifest(config.record_path, final);
            zoulab.ParallelTiffConverter.updateCycleManifests( ...
                config, cropResults, results, final);
        end

        function updateCycleManifests(config, cropResults, results, final)
            for cycleIndex = 1:config.plan_cycles
                cyclePath = string(fullfile(config.record_path, ...
                    sprintf('Cycle%d', cycleIndex)));
                streamPath = string(fullfile(cyclePath, ...
                    'record_stream_manifest.mat'));
                if ~isfile(streamPath)
                    continue;
                end
                loaded = load(streamPath, 'manifest');
                manifest = loaded.manifest;
                cropStatus = 'not_requested';
                cropError = '';
                cropPosition = find([cropResults.cycle] == cycleIndex, 1);
                if ~isempty(cropPosition)
                    cropStatus = cropResults(cropPosition).status;
                    cropError = cropResults(cropPosition).error;
                end
                cycleUnits = results([results.cycle] == cycleIndex);
                conversionStatus = 'not_requested';
                conversionError = '';
                if config.convert_to_tiff && ~isempty(cycleUnits)
                    statuses = string({cycleUnits.status});
                    if all(statuses == "complete")
                        conversionStatus = 'complete';
                    elseif all(ismember(statuses, ["complete", ...
                            "complete_with_source_bin_retained"]))
                        conversionStatus = ...
                            'complete_with_source_bin_retained';
                    else
                        conversionStatus = 'partial_error';
                    end
                    errors = string({cycleUnits.error});
                    conversionError = char(strjoin( ...
                        errors(strlength(errors) > 0), ' | '));
                elseif config.convert_to_tiff
                    conversionStatus = 'partial_error';
                    conversionError = ...
                        'No TIFF conversion units were returned for this Cycle.';
                end
                if startsWith(string(cropStatus), "error") || ...
                        string(conversionStatus) == "partial_error"
                    cycleStatus = 'partial_error';
                elseif string(conversionStatus) == ...
                        "complete_with_source_bin_retained"
                    cycleStatus = 'complete_with_source_bin_retained';
                else
                    cycleStatus = 'complete';
                end
                manifest.conversion.status = conversionStatus;
                manifest.conversion.units = cycleUnits;
                manifest.conversion.source_bin_deleted = ...
                    config.convert_to_tiff && ~isempty(cycleUnits) && ...
                    all([cycleUnits.source_bin_deleted]);
                if isempty(cycleUnits)
                    manifest.conversion.tiff_files = {};
                else
                    manifest.conversion.tiff_files = cellstr(string( ...
                        [cycleUnits.tiff_files]));
                end
                manifest.conversion.error = conversionError;
                if ~isfield(manifest, 'postprocessing')
                    manifest.postprocessing = struct();
                end
                manifest.postprocessing.status = cycleStatus;
                manifest.postprocessing.physical_bin_crop_status = ...
                    cropStatus;
                manifest.postprocessing.convert_to_tiff_status = ...
                    conversionStatus;
                cycleErrors = string({cropError, conversionError});
                cycleErrors = cycleErrors(strlength(cycleErrors) > 0);
                manifest.postprocessing.error = char(strjoin( ...
                    cycleErrors, ' | '));
                finalFiles = strings(1, 0);
                if ~isempty(cycleUnits)
                    for unitIndex = 1:numel(cycleUnits)
                        finalFiles = [finalFiles ... %#ok<AGROW>
                            string(cycleUnits(unitIndex).bin_info_files) ...
                            string(cycleUnits(unitIndex).tiff_files)];
                        bins = string(cycleUnits(unitIndex).source_bin_files);
                        finalFiles = [finalFiles bins(isfile(bins))]; %#ok<AGROW>
                    end
                else
                    for cameraIndex = 1:numel(manifest.cameras)
                        finalFiles = [finalFiles ... %#ok<AGROW>
                            string(manifest.cameras(cameraIndex). ...
                            bin_info_files)];
                        bins = string(manifest.cameras(cameraIndex).bin_files);
                        finalFiles = [finalFiles bins(isfile(bins))]; %#ok<AGROW>
                    end
                end
                finalFiles = unique(finalFiles(isfile(finalFiles)), 'stable');
                manifest.final_data_files = cellstr(finalFiles);
                zoulab.SessionManager.writeMatManifest(streamPath, manifest);
                zoulab.SessionManager.writeJson(fullfile(cyclePath, ...
                    'record_stream_manifest.json'), manifest);

                cycleJson = string(fullfile(cyclePath, 'cycle_manifest.json'));
                if isfile(cycleJson)
                    cycleValue = jsondecode(fileread(cycleJson));
                    cycleValue.files = cellstr(finalFiles);
                    cycleValue.postprocessing = final;
                    cycleValue.postprocessing.cycle_status = cycleStatus;
                    if config.convert_to_tiff
                        cycleValue.conversion = final;
                        cycleValue.conversion.cycle_status = conversionStatus;
                    end
                    cycleValue.updated_at = ...
                        zoulab.ParallelTiffConverter.timestamp();
                    zoulab.SessionManager.writeJson(cycleJson, cycleValue);
                end
                cycleMat = string(fullfile(cyclePath, 'cycle_manifest.mat'));
                if isfile(cycleMat)
                    cycleLoaded = load(cycleMat, 'manifest');
                    compatible = cycleLoaded.manifest;
                    compatible.actual.movie_paths = cellstr(finalFiles);
                    compatible.notes.postprocessing_status = cycleStatus;
                    compatible.notes.postprocessing_manifest = char(fullfile( ...
                        config.record_path, ...
                        'record_postprocessing_manifest.mat'));
                    if config.convert_to_tiff
                        compatible.notes.conversion_status = conversionStatus;
                        compatible.notes.conversion_manifest = char(fullfile( ...
                            config.record_path, ...
                            'record_conversion_manifest.mat'));
                    end
                    compatible.timestamps.updated_at = ...
                        zoulab.ParallelTiffConverter.timestamp();
                    zoulab.SessionManager.writeMatManifest( ...
                        cycleMat, compatible);
                end
            end
        end

        function writeInitialManifest(config)
            units = repmat(zoulab.ParallelTiffConverter.resultTemplate(), ...
                numel(config.units), 1);
            for index = 1:numel(config.units)
                units(index).cycle = config.units(index).cycle;
                units(index).camera = config.units(index).camera;
                units(index).expected_frames = ...
                    config.units(index).expected_frames;
                units(index).bin_info_files = ...
                    config.units(index).bin_info_files;
                units(index).source_bin_files = ...
                    config.units(index).source_bin_files;
            end
            manifest = struct('schema_version', '2.0.0', ...
                'kind', 'record_post_capture_processing', ...
                'status', 'queued', 'started_at', config.submitted_at, ...
                'completed_at', '', ...
                'capture_all_cycles_completed_before_postprocessing', true, ...
                'execution', ...
                    'background_batch_crop_then_optional_process_pool', ...
                'unit_policy', config.unit_policy, ...
                'physical_bin_crop_requested', config.crop_visual_bins, ...
                'crop_total_cycles', numel(config.crop_cycles), ...
                'crop_completed_cycles', 0, 'crop_results', struct([]), ...
                'tiff_conversion_requested', config.convert_to_tiff, ...
                'exclusive_output_file_per_worker', ...
                    logical(config.convert_to_tiff), ...
                'worker_count', config.worker_count, ...
                'worker_limit', config.worker_limit, ...
                'read_mode', config.read_mode, ...
                'buffer_bytes_per_worker', config.buffer_bytes_per_worker, ...
                'total_units', config.total_units, 'completed_units', 0, ...
                'total_frames', config.total_frames, 'converted_frames', 0, ...
                'progress_fraction', 0, 'units', units, 'error', '', ...
                'plan_cycles', config.plan_cycles);
            zoulab.ParallelTiffConverter.writeManifest( ...
                config.record_path, manifest);
            zoulab.ParallelTiffConverter.writeStage(config, 'queued', ...
                0, numel(config.crop_cycles), 0, ...
                'Waiting for background Record post-processing.', '');
        end

        function writeManifest(recordPath, manifest)
            bases = string(fullfile(recordPath, [ ...
                "record_postprocessing_manifest", ...
                "record_conversion_manifest"]));
            for base = bases
                zoulab.SessionManager.writeMatManifest( ...
                    base + ".mat", manifest);
                zoulab.SessionManager.writeJson(base + ".json", manifest);
            end
        end

        function writeStage(config, status, completedCropCycles, ...
                totalCropCycles, currentCycle, detail, errorText)
            errorCount = 0;
            if isfile(config.stage_path)
                try
                    previous = jsondecode(fileread(config.stage_path));
                    if isfield(previous, 'error_count')
                        errorCount = double(previous.error_count);
                    end
                catch
                end
            end
            if strlength(string(errorText)) > 0
                errorCount = errorCount + 1;
            end
            value = struct('schema_version', '1.0.0', ...
                'status', char(string(status)), ...
                'completed_crop_cycles', double(completedCropCycles), ...
                'total_crop_cycles', double(totalCropCycles), ...
                'current_cycle', double(currentCycle), ...
                'error_count', errorCount, ...
                'detail', char(string(detail)), ...
                'error', char(string(errorText)), ...
                'updated_at', zoulab.ParallelTiffConverter.timestamp());
            zoulab.SessionManager.writeJson(config.stage_path, value);
        end

        function writeUnitProgress(config, unit, framesDone, status, ...
                detail, startedAt)
            value = struct('schema_version', '1.0.0', ...
                'unit_index', unit.index, 'cycle', unit.cycle, ...
                'camera', unit.camera, 'status', char(status), ...
                'frames_done', double(framesDone), ...
                'frames_total', double(unit.expected_frames), ...
                'bytes_per_frame', double(unit.bytes_per_frame), ...
                'started_at', char(startedAt), ...
                'updated_at', ...
                    zoulab.ParallelTiffConverter.timestamp(), ...
                'detail', char(detail));
            zoulab.SessionManager.writeJson( ...
                zoulab.ParallelTiffConverter.progressPath( ...
                config, unit.index), value);
        end

        function path = progressPath(config, unitIndex)
            path = string(fullfile(config.progress_folder, sprintf( ...
                'unit_%03d.json', unitIndex)));
        end

        function path = cropProgressPath(config, cycleIndex)
            path = string(fullfile(config.progress_folder, sprintf( ...
                'crop_cycle_%03d.json', cycleIndex)));
        end

        function files = deletePartialTiffs(outputPath)
            [folder, baseName] = fileparts(outputPath);
            entries = dir(fullfile(folder, [baseName '_stack*.tif']));
            files = strings(1, 0);
            for index = 1:numel(entries)
                path = string(fullfile(entries(index).folder, ...
                    entries(index).name));
                try
                    delete(path);
                    files(end + 1) = path; %#ok<AGROW>
                catch
                end
            end
        end

        function result = resultTemplate()
            result = struct('cycle', 0, 'camera', 0, ...
                'status', 'pending', 'expected_frames', 0, ...
                'written_frames', 0, 'bin_info_files', {{}}, ...
                'source_bin_files', {{}}, 'tiff_files', {{}}, ...
                'source_bin_deleted', false, ...
                'partial_tiff_files_deleted', {{}}, ...
                'started_at', '', 'completed_at', '', 'error', '');
        end

        function value = availablePhysicalMemoryBytes()
            value = 16 * 1024^3;
            try
                [~, systemView] = memory;
                value = double(systemView.PhysicalMemory.Available);
            catch
            end
        end

        function value = physicalCoreCount()
            value = 1;
            try
                value = max(1, double(feature('numcores')));
            catch
            end
        end

        function value = timestamp()
            value = char(datetime('now', ...
                'Format', 'yyyy-MM-dd HH:mm:ss.SSS'));
        end
    end
end
