classdef RegistrationService
    %REGISTRATIONSERVICE Translation-only alignment for the two cameras.

    methods (Static)
        function result = register(camera1Raw, camera2Raw, baseROI, sensorLimit, logger)
            validateattributes(camera1Raw, {'uint16'}, {'2d','nonempty'});
            validateattributes(camera2Raw, {'uint16'}, {'2d','nonempty'});
            moving = camera1Raw.';
            reference = camera2Raw;
            [optimizer, metric] = imregconfig('multimodal');
            started = tic;
            tform = imregtform(moving, reference, 'translation', optimizer, metric);
            offset = [tform.T(3, 1), tform.T(3, 2)];
            roi1 = double(baseROI);
            roi1(1) = round(baseROI(1) - offset(2));
            roi1(2) = round(baseROI(2) - offset(1));
            if roi1(1) < 0 || roi1(2) < 0 || ...
                    roi1(1) + roi1(3) > sensorLimit || roi1(2) + roi1(4) > sensorLimit
                error('ZouLab:RegistrationROIOutOfBounds', ...
                    'Registration offset %s produces invalid Camera 1 ROI %s.', ...
                    mat2str(offset), mat2str(roi1));
            end
            result = struct( ...
                'status', 'success', ...
                'mode', 'multimodal_translation', ...
                'moving_camera', 1, ...
                'reference_camera', 2, ...
                'camera1_transposed_for_registration', true, ...
                'offset_xy', offset, ...
                'base_roi', double(baseROI), ...
                'camera1_roi', roi1, ...
                'tform_T', tform.T, ...
                'elapsed_seconds', toc(started), ...
                'created_at', char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss.SSS')));
            logger.log('SUCCESS', 'REGISTRATION_SUCCESS', ...
                'OffsetXY=%s | Camera1ROI=%s | Elapsed=%.3f s | Camera1Transposed=true', ...
                mat2str(offset), mat2str(roi1), result.elapsed_seconds);
        end

        function artifactFolder = beginArtifacts( ...
                recordFolder, camera1Raw, camera2Raw, mode, context)
            validateattributes(camera1Raw, {'uint16'}, {'2d','nonempty'});
            validateattributes(camera2Raw, {'uint16'}, {'2d','nonempty'});
            if nargin < 5 || isempty(context)
                context = struct();
            end
            root = fullfile(recordFolder, 'registration');
            if ~isfolder(root)
                mkdir(root);
            end
            stamp = char(datetime('now', 'Format', 'yyMMdd_HHmmss_SSS'));
            artifactFolder = fullfile(root, ['Reg_' stamp]);
            suffix = 1;
            while isfolder(artifactFolder)
                artifactFolder = fullfile(root, sprintf( ...
                    'Reg_%s_%02d', stamp, suffix));
                suffix = suffix + 1;
            end
            mkdir(artifactFolder);
            imwrite(camera1Raw, fullfile(artifactFolder, ...
                'camera1_raw.tif'), 'tif', 'Compression', 'none');
            imwrite(camera2Raw, fullfile(artifactFolder, ...
                'camera2_raw.tif'), 'tif', 'Compression', 'none');
            zoulab.RegistrationService.saveOverlap( ...
                fullfile(artifactFolder, 'overlap_before.png'), ...
                camera1Raw.', camera2Raw, 'Before registration');
            result = struct( ...
                'status', 'captured', ...
                'mode', char(string(mode)), ...
                'created_at', char(datetime('now', ...
                    'Format', 'yyyy-MM-dd HH:mm:ss.SSS')), ...
                'camera1_raw_file', 'camera1_raw.tif', ...
                'camera2_raw_file', 'camera2_raw.tif', ...
                'overlap_before_file', 'overlap_before.png', ...
                'raw_class', 'uint16', ...
                'raw_transposed', false, ...
                'camera1_transposed_for_registration', true, ...
                'context', context);
            save(fullfile(artifactFolder, 'registration.mat'), 'result');
            zoulab.SessionManager.writeJson(fullfile(artifactFolder, ...
                'registration.json'), result);
        end

        function finishArtifacts(artifactFolder, camera1Raw, camera2Raw, result)
            captured = load(fullfile(artifactFolder, 'registration.mat'));
            registered = imtranslate(camera1Raw.', result.offset_xy);
            zoulab.RegistrationService.saveOverlap( ...
                fullfile(artifactFolder, 'overlap_after.png'), ...
                registered, camera2Raw, sprintf( ...
                'After registration: offset [%.2f, %.2f] px', ...
                result.offset_xy));
            result.status = 'success';
            result.camera1_raw_file = 'camera1_raw.tif';
            result.camera2_raw_file = 'camera2_raw.tif';
            result.overlap_before_file = 'overlap_before.png';
            result.overlap_after_file = 'overlap_after.png';
            result.raw_class = 'uint16';
            result.raw_transposed = false;
            result.artifact_folder = char(artifactFolder);
            if isfield(captured, 'result') && ...
                    isfield(captured.result, 'context')
                result.context = captured.result.context;
                result.captured_at = captured.result.created_at;
            end
            save(fullfile(artifactFolder, 'registration.mat'), 'result');
            zoulab.SessionManager.writeJson(fullfile(artifactFolder, ...
                'registration.json'), result);
        end

        function markArtifactsCancelled(artifactFolder, reason)
            if strlength(string(artifactFolder)) == 0 || ...
                    ~isfolder(artifactFolder)
                return;
            end
            loaded = load(fullfile(artifactFolder, 'registration.mat'));
            result = loaded.result;
            result.status = 'cancelled';
            result.cancel_reason = char(string(reason));
            result.cancelled_at = char(datetime('now', ...
                'Format', 'yyyy-MM-dd HH:mm:ss.SSS'));
            save(fullfile(artifactFolder, 'registration.mat'), 'result');
            zoulab.SessionManager.writeJson(fullfile(artifactFolder, ...
                'registration.json'), result);
        end

        function savePreview(folder, camera1Raw, camera2Raw, result)
            save(fullfile(folder, 'registration.mat'), 'result');
            fig = figure('Visible', 'off', 'Color', 'w', ...
                'Position', [100 100 1100 500]);
            cleanup = onCleanup(@() delete(fig)); %#ok<NASGU>
            tiledlayout(fig, 1, 2, 'Padding', 'compact');
            nexttile;
            imshowpair(camera1Raw.', camera2Raw);
            title('Before Registration');
            nexttile;
            registered = imtranslate(camera1Raw.', result.offset_xy);
            imshowpair(registered, camera2Raw);
            title(sprintf('After: [%.2f, %.2f] px', result.offset_xy));
            exportgraphics(fig, fullfile(folder, 'registration.png'));
            zoulab.SessionManager.writeJson(fullfile(folder, ...
                'registration.json'), result);
        end

        function saveOverlap(filePath, camera1RegistrationView, camera2Raw, titleText)
            fig = figure('Visible', 'off', 'Color', 'w', ...
                'Position', [100 100 800 700]);
            cleanup = onCleanup(@() delete(fig)); %#ok<NASGU>
            axesHandle = axes(fig);
            imshowpair(camera1RegistrationView, camera2Raw, ...
                'falsecolor', 'Parent', axesHandle, ...
                'ColorChannels', 'red-cyan');
            title(axesHandle, titleText, 'Interpreter', 'none');
            exportgraphics(axesHandle, filePath, 'Resolution', 150);
        end

        function result = manualResultFromPolygons(position1, position2, baseROI, sensorLimit)
            validateattributes(position1, {'numeric'}, {'2d','ncols',2,'finite'});
            validateattributes(position2, {'numeric'}, {'2d','ncols',2,'finite'});
            if size(position1, 1) < 3 || size(position2, 1) < 3
                error('ZouLab:ManualRegistrationPolygonTooSmall', ...
                    'Each registration polygon requires at least three vertices.');
            end
            [centroid1X, centroid1Y] = centroid(polyshape(position1(:,1), position1(:,2)));
            [centroid2X, centroid2Y] = centroid(polyshape(position2(:,1), position2(:,2)));
            centroid1 = [centroid1X centroid1Y];
            centroid2 = [centroid2X centroid2Y];
            offset = centroid2 - centroid1;
            roi1 = double(baseROI);
            % Camera 1 was transposed for the displayed selection.  Display
            % X therefore corrects raw ROI Y, and display Y corrects raw ROI X.
            roi1(1) = round(baseROI(1) - offset(2));
            roi1(2) = round(baseROI(2) - offset(1));
            if roi1(1) < 0 || roi1(2) < 0 || ...
                    roi1(1) + roi1(3) > sensorLimit || roi1(2) + roi1(4) > sensorLimit
                error('ZouLab:RegistrationROIOutOfBounds', ...
                    'Polygon centroid offset %s produces invalid Camera 1 ROI %s.', ...
                    mat2str(offset), mat2str(roi1));
            end
            result = struct( ...
                'status', 'success', ...
                'mode', 'manual_polygon_geometric_centroid', ...
                'moving_camera', 1, ...
                'reference_camera', 2, ...
                'camera1_transposed_for_registration', true, ...
                'centroid_definition', ...
                    'geometric centroid of selected polygon; no intensity weighting', ...
                'camera1_polygon_xy', double(position1), ...
                'camera2_polygon_xy', double(position2), ...
                'camera1_centroid_xy', centroid1, ...
                'camera2_centroid_xy', centroid2, ...
                'offset_xy', offset, ...
                'base_roi', double(baseROI), ...
                'camera1_roi', roi1, ...
                'created_at', char(datetime('now', ...
                    'Format', 'yyyy-MM-dd HH:mm:ss.SSS')));
        end

        function result = manualResultFromDisplayedPolygons( ...
                position1Display, position2Display, baseROI, sensorLimit, ...
                displayTranspose)
            % Normalize points drawn on the live preview axes into the
            % fixed registration coordinate system used by register():
            % Camera 1 transposed, Camera 2 normal.
            validateattributes(displayTranspose, {'logical','numeric'}, ...
                {'vector','numel',2});
            displayTranspose = logical(displayTranspose(:).');
            expectedTranspose = [true false];
            positions = {double(position1Display), double(position2Display)};
            normalized = positions;
            for cameraIndex = 1:2
                if xor(displayTranspose(cameraIndex), ...
                        expectedTranspose(cameraIndex))
                    normalized{cameraIndex} = positions{cameraIndex}(:, [2 1]);
                end
            end
            result = zoulab.RegistrationService.manualResultFromPolygons( ...
                normalized{1}, normalized{2}, baseROI, sensorLimit);
            result.display_transpose = displayTranspose;
            result.camera1_display_polygon_xy = positions{1};
            result.camera2_display_polygon_xy = positions{2};
            result.camera1_polygon_normalized_from_display = ...
                ~isequal(displayTranspose(1), expectedTranspose(1));
            result.camera2_polygon_normalized_from_display = ...
                ~isequal(displayTranspose(2), expectedTranspose(2));
        end
    end
end
