classdef VisualFrameAlignment
    %VISUALFRAMEALIGNMENT Reproduce rebuilt DAQ-counter movie cropping.

    methods (Static)
        function streamManifest = apply(streamManifest, syncTable, ...
                cameraIndices, logger)
            cameraIndices = unique(double(cameraIndices(:).'), 'stable');
            alignmentCells = cell(1, numel(cameraIndices));
            for position = 1:numel(cameraIndices)
                cameraIndex = cameraIndices(position);
                manifestPosition = find( ...
                    [streamManifest.cameras.camera] == cameraIndex, 1);
                if isempty(manifestPosition)
                    error('ZouLab:VisualAlignmentCameraMissing', ...
                        'Stream manifest has no Camera %d entry.', cameraIndex);
                end
                rawFrames = double(streamManifest.cameras( ...
                    manifestPosition).written_frames);
                alignment = zoulab.VisualFrameAlignment.compute( ...
                    syncTable, cameraIndex, rawFrames);
                streamManifest.cameras(manifestPosition).visual_alignment = ...
                    alignment;
                if isfield(streamManifest.cameras(manifestPosition), ...
                        'bin_info_files')
                    zoulab.BinInfo.markVisualAlignment(string( ...
                        streamManifest.cameras( ...
                        manifestPosition).bin_info_files), alignment);
                end
                alignmentCells{position} = alignment;
                if alignment.valid
                    logger.log('SUCCESS', 'VISUAL_FRAME_ALIGNMENT_COMPUTED', ...
                        ['Camera=%d | Counter=%s | RawFrames=%d | ', ...
                         'ValidRange=%s | ValidFrames=%d | ', ...
                         'DroppedBefore=%d | DroppedAfter=%d | ', ...
                         'Method=rebuilt_second_counter_to_last_plus_mean_step'], ...
                        cameraIndex, alignment.counter_variable, rawFrames, ...
                        mat2str(alignment.applied_frame_range), ...
                        alignment.valid_frame_count, ...
                        alignment.dropped_before, alignment.dropped_after);
                else
                    logger.log('ERROR', 'VISUAL_FRAME_ALIGNMENT_INVALID', ...
                        ['Camera=%d | Counter=%s | RawFrames=%d | ', ...
                         'Reason=%s | RawBinPreserved=1 | ', ...
                         'FullRangeFallback=%s | AcquisitionStopped=0'], ...
                        cameraIndex, alignment.counter_variable, rawFrames, ...
                        alignment.error, ...
                        mat2str(alignment.applied_frame_range));
                end
            end
            alignments = [alignmentCells{:}];
            streamManifest.visual_alignment = struct( ...
                'schema_version', '1.0.0', ...
                'method', 'rebuilt_daq_counter_crop', ...
                'all_cameras_valid', all([alignments.valid]), ...
                'cameras', alignments);
        end

        function value = compute(syncTable, cameraIndex, rawFrames)
            rawFrames = double(rawFrames);
            counterVariable = sprintf('Camera%dFrame', cameraIndex);
            value = struct( ...
                'schema_version', '1.0.0', ...
                'method', 'rebuilt_daq_counter_crop', ...
                'counter_variable', counterVariable, ...
                'valid', false, ...
                'status', 'invalid', ...
                'error', '', ...
                'raw_frame_count', rawFrames, ...
                'matched_visual_rows', height(syncTable), ...
                'first_counter', NaN, ...
                'second_counter', NaN, ...
                'last_counter', NaN, ...
                'mean_counter_step_per_flip', NaN, ...
                'requested_frame_range', [NaN NaN], ...
                'applied_frame_range', zoulab.VisualFrameAlignment.fullRange( ...
                    rawFrames), ...
                'valid_frame_count', rawFrames, ...
                'dropped_before', 0, ...
                'dropped_after', 0, ...
                'fallback', 'preserve_full_raw_bin');
            if rawFrames < 1 || mod(rawFrames, 1) ~= 0
                value.error = 'Raw written frame count is not a positive integer.';
                return;
            end
            if height(syncTable) < 2
                value.error = 'Fewer than two matched PTB/DAQ rows are available.';
                return;
            end
            if ~ismember(counterVariable, ...
                    syncTable.Properties.VariableNames)
                value.error = sprintf('DAQ sync table lacks %s.', ...
                    counterVariable);
                return;
            end
            counters = double(syncTable.(counterVariable)(:));
            if any(~isfinite(counters))
                value.error = 'DAQ camera counter contains non-finite values.';
                return;
            end
            increments = diff(counters);
            meanStep = mean(increments);
            value.first_counter = counters(1);
            value.second_counter = counters(2);
            value.last_counter = counters(end);
            value.mean_counter_step_per_flip = meanStep;
            if counters(end) <= counters(1) || meanStep <= 0 || ...
                    any(increments < 0)
                value.error = ...
                    'DAQ camera counter did not increase monotonically.';
                return;
            end

            % This intentionally matches SaveCameraData in rebuilt.m:
            % start = the second visual-stamp camera count; end = the last
            % count plus one mean inter-flip camera-count increment.
            requested = [counters(2), ...
                counters(end) + ceil(meanStep)];
            applied = [max(1, ceil(requested(1))), ...
                min(rawFrames, floor(requested(2)))];
            value.requested_frame_range = requested;
            if applied(2) < applied(1)
                value.error = sprintf( ...
                    'DAQ-derived range %s does not overlap %d raw frames.', ...
                    mat2str(requested), rawFrames);
                return;
            end
            value.applied_frame_range = applied;
            value.valid_frame_count = applied(2) - applied(1) + 1;
            value.dropped_before = applied(1) - 1;
            value.dropped_after = rawFrames - applied(2);
            value.valid = true;
            value.status = 'complete';
            value.error = '';
            value.fallback = 'none';
        end
    end

    methods (Static, Access = private)
        function range = fullRange(rawFrames)
            if isfinite(rawFrames) && rawFrames >= 1
                range = [1 rawFrames];
            else
                range = [NaN NaN];
            end
        end
    end
end
