classdef VisualBinCropper
    %VISUALBINCROPPER Physically remove DAQ-derived visual head/tail frames.
    % Preparation is non-destructive. Original files are replaced only
    % after every retained segment for every camera has been verified.

    methods (Static)
        function streamManifest = apply(streamManifest, cameraIndices, logger)
            cameraIndices = unique(double(cameraIndices(:).'), 'stable');
            transactionID = char(datetime('now', ...
                'Format', 'yyyyMMdd_HHmmss_SSS'));
            planCells = cell(1, numel(cameraIndices));
            logger.log('INFO', 'VISUAL_BIN_PHYSICAL_CROP_BEGIN', ...
                ['Transaction=%s | Cameras=%s | Timing=after_writer_close | ', ...
                 'IATInteraction=none | PTBInteraction=none | ', ...
                 'OriginalsPreservedUntilAllPreparationsVerify=1'], ...
                transactionID, mat2str(cameraIndices));
            try
                for position = 1:numel(cameraIndices)
                    cameraIndex = cameraIndices(position);
                    manifestPosition = find( ...
                        [streamManifest.cameras.camera] == cameraIndex, 1);
                    if isempty(manifestPosition)
                        error('ZouLab:VisualCropCameraMissing', ...
                            'Stream manifest has no Camera %d entry.', ...
                            cameraIndex);
                    end
                    planCells{position} = ...
                        zoulab.VisualBinCropper.prepareCamera( ...
                        streamManifest.cameras(manifestPosition), ...
                        transactionID, logger);
                end
                plans = [planCells{:}];
                zoulab.VisualBinCropper.commit(plans, logger);
            catch ME
                zoulab.VisualBinCropper.cleanupPrepared(planCells);
                logger.logException('VISUAL_BIN_PHYSICAL_CROP_FAILED', ME);
                logger.log('ERROR', 'VISUAL_BIN_PHYSICAL_CROP_ROLLED_BACK', ...
                    ['Transaction=%s | Cameras=%s | OriginalBinPreserved=1 | ', ...
                     'AcquisitionAlreadyComplete=1'], transactionID, ...
                    mat2str(cameraIndices));
                rethrow(ME);
            end

            cameraSummaries = cell(1, numel(plans));
            for position = 1:numel(plans)
                plan = plans(position);
                manifestPosition = find( ...
                    [streamManifest.cameras.camera] == plan.camera, 1);
                streamManifest.cameras(manifestPosition). ...
                    writer_written_frames_before_visual_crop = ...
                    streamManifest.cameras(manifestPosition).written_frames;
                streamManifest.cameras(manifestPosition).written_frames = ...
                    plan.stored_frames;
                streamManifest.cameras(manifestPosition).bin_files = ...
                    cellstr(plan.output_bin_files);
                streamManifest.cameras(manifestPosition).bin_info_files = ...
                    cellstr(plan.output_info_files);
                streamManifest.cameras(manifestPosition).visual_alignment = ...
                    plan.alignment;
                streamManifest.cameras(manifestPosition).physical_crop = ...
                    plan.summary;
                cameraSummaries{position} = plan.summary;
            end
            summaries = [cameraSummaries{:}];
            streamManifest.visual_physical_crop = struct( ...
                'schema_version', '1.0.0', ...
                'status', 'complete', ...
                'transaction_id', transactionID, ...
                'completed_utc', zoulab.BinInfo.utcNow(), ...
                'strategy', ...
                    'rewrite_partial_boundary_segments_keep_full_middle', ...
                'cameras', summaries);
            logger.log('SUCCESS', 'VISUAL_BIN_PHYSICAL_CROP_COMPLETE', ...
                ['Transaction=%s | Cameras=%s | RawFrames=%s | ', ...
                 'StoredFrames=%s | RemovedFrames=%s | ', ...
                 'HeadTailRemainInFinalBin=0'], transactionID, ...
                mat2str(cameraIndices), ...
                mat2str([summaries.source_frame_count]), ...
                mat2str([summaries.stored_frame_count]), ...
                mat2str([summaries.removed_frame_count]));
        end
    end

    methods (Static, Access = private)
        function plan = prepareCamera(cameraManifest, transactionID, logger)
            cameraIndex = double(cameraManifest.camera);
            if ~isfield(cameraManifest, 'visual_alignment') || ...
                    ~cameraManifest.visual_alignment.valid
                error('ZouLab:VisualCropAlignmentInvalid', ...
                    ['Camera %d has no valid DAQ-counter alignment; physical ', ...
                     'crop is refused and the complete raw BIN is retained.'], ...
                    cameraIndex);
            end
            alignment = cameraManifest.visual_alignment;
            if isfield(alignment, 'storage_crop_applied') && ...
                    alignment.storage_crop_applied
                error('ZouLab:VisualCropAlreadyApplied', ...
                    'Camera %d BIN is already physically cropped.', cameraIndex);
            end
            infoFiles = string(cameraManifest.bin_info_files(:).');
            [infos, binFiles, frameSize, totalFrames] = ...
                zoulab.BinInfo.loadAndValidate(infoFiles);
            sourceRange = double(alignment.applied_frame_range(:).');
            if totalFrames ~= double(cameraManifest.written_frames) || ...
                    numel(sourceRange) ~= 2 || ...
                    sourceRange(1) < 1 || sourceRange(2) > totalFrames || ...
                    sourceRange(2) < sourceRange(1)
                error('ZouLab:VisualCropContractMismatch', ...
                    ['Camera %d source has %d frames, manifest reports %d, ', ...
                     'and crop range is %s.'], cameraIndex, totalFrames, ...
                    cameraManifest.written_frames, mat2str(sourceRange));
            end

            storedFrames = sourceRange(2) - sourceRange(1) + 1;
            croppedAlignment = alignment;
            croppedAlignment.source_applied_frame_range = sourceRange;
            croppedAlignment.source_raw_frame_count = totalFrames;
            croppedAlignment.storage_crop_applied = true;
            croppedAlignment.storage_crop_transaction_id = transactionID;
            croppedAlignment.storage_crop_completed_utc = ...
                zoulab.BinInfo.utcNow();
            croppedAlignment.stored_frame_count = storedFrames;
            croppedAlignment.applied_frame_range = [1 storedFrames];
            croppedAlignment.status = 'physically_cropped';

            entryCells = cell(1, numel(binFiles));
            preparedTempFiles = strings(1, 0);
            outputBinFiles = strings(1, 0);
            outputInfoFiles = strings(1, 0);
            sourceOffset = 0;
            storedOffset = 0;
            try
                for segmentIndex = 1:numel(binFiles)
                sourceFrames = double(infos(segmentIndex).frame_count);
                sourceGlobal = sourceOffset + [1 sourceFrames];
                overlap = [max(sourceRange(1), sourceGlobal(1)), ...
                    min(sourceRange(2), sourceGlobal(2))];
                sourceBin = binFiles(segmentIndex);
                sourceInfo = infoFiles(segmentIndex);
                entry = zoulab.VisualBinCropper.emptyEntry( ...
                    sourceBin, sourceInfo, sourceGlobal);
                if overlap(2) < overlap(1)
                    entry.action = "delete_outside_range";
                    entry.output_frames = 0;
                else
                    localRange = overlap - sourceOffset;
                    outputFrames = overlap(2) - overlap(1) + 1;
                    storedGlobal = storedOffset + [1 outputFrames];
                    entry.source_local_range = localRange;
                    entry.stored_global_range = storedGlobal;
                    entry.output_frames = outputFrames;
                    if isequal(localRange, [1 sourceFrames])
                        entry.action = "keep_full_segment";
                        contentPath = sourceBin;
                    else
                        entry.action = "replace_partial_segment";
                        entry.temp_bin = string(tempname(fileparts( ...
                            sourceBin))) + ".visualcrop.bin";
                        preparedTempFiles(end + 1) = entry.temp_bin; %#ok<AGROW>
                        zoulab.VisualBinCropper.copyFrameRange( ...
                            sourceBin, entry.temp_bin, frameSize, localRange);
                        contentPath = entry.temp_bin;
                    end
                    segmentCrop = struct( ...
                        'schema_version', '1.0.0', ...
                        'status', 'complete', ...
                        'transaction_id', transactionID, ...
                        'completed_utc', zoulab.BinInfo.utcNow(), ...
                        'action', char(entry.action), ...
                        'source_global_frame_range', sourceGlobal, ...
                        'source_local_frame_range', localRange, ...
                        'stored_global_frame_range', storedGlobal, ...
                        'source_segment_frame_count', sourceFrames, ...
                        'stored_segment_frame_count', outputFrames, ...
                        'removed_segment_frame_count', ...
                            sourceFrames - outputFrames);
                    updatedInfo = zoulab.BinInfo.updateForPhysicalCrop( ...
                        infos(segmentIndex), contentPath, outputFrames, ...
                        croppedAlignment, segmentCrop);
                    entry.temp_info = string(tempname(fileparts( ...
                        sourceInfo))) + ".visualcrop.json";
                    preparedTempFiles(end + 1) = entry.temp_info; %#ok<AGROW>
                    zoulab.BinInfo.write(entry.temp_info, updatedInfo);
                    outputBinFiles(end + 1) = sourceBin; %#ok<AGROW>
                    outputInfoFiles(end + 1) = sourceInfo; %#ok<AGROW>
                    storedOffset = storedOffset + outputFrames;
                end
                entry.backup_bin = string(tempname(fileparts( ...
                    sourceBin))) + ".visualcrop.backup.bin";
                entry.backup_info = string(tempname(fileparts( ...
                    sourceInfo))) + ".visualcrop.backup.json";
                entryCells{segmentIndex} = entry;
                sourceOffset = sourceOffset + sourceFrames;
                logger.log('INFO', 'VISUAL_BIN_CROP_SEGMENT_PREPARED', ...
                    ['Transaction=%s | Camera=%d | Segment=%d | Action=%s | ', ...
                     'SourceGlobalRange=%s | SourceLocalRange=%s | ', ...
                     'OutputFrames=%d | Source=%s'], transactionID, ...
                    cameraIndex, segmentIndex, entry.action, ...
                    mat2str(sourceGlobal), ...
                    mat2str(entry.source_local_range), entry.output_frames, ...
                    sourceBin);
                end
                if sourceOffset ~= totalFrames || storedOffset ~= storedFrames
                    error('ZouLab:VisualCropPreparedCountMismatch', ...
                        ['Camera %d traversed %d/%d source frames and ', ...
                         'prepared %d/%d selected frames.'], cameraIndex, ...
                        sourceOffset, totalFrames, storedOffset, storedFrames);
                end
            catch ME
                for preparedPath = preparedTempFiles
                    zoulab.VisualBinCropper.deleteQuietly(preparedPath);
                end
                rethrow(ME);
            end
            entries = [entryCells{:}];
            plan = struct( ...
                'camera', cameraIndex, ...
                'transaction_id', transactionID, ...
                'entries', entries, ...
                'alignment', croppedAlignment, ...
                'source_frames', totalFrames, ...
                'stored_frames', storedFrames, ...
                'output_bin_files', outputBinFiles, ...
                'output_info_files', outputInfoFiles, ...
                'summary', struct( ...
                    'camera', cameraIndex, ...
                    'status', 'complete', ...
                    'source_frame_count', totalFrames, ...
                    'stored_frame_count', storedFrames, ...
                    'removed_frame_count', totalFrames - storedFrames, ...
                    'source_valid_frame_range', sourceRange, ...
                    'final_stored_frame_range', [1 storedFrames], ...
                    'source_segment_count', numel(binFiles), ...
                    'final_segment_count', numel(outputBinFiles), ...
                    'rewritten_boundary_segments', sum( ...
                        [entries.action] == "replace_partial_segment"), ...
                    'unchanged_full_segments', sum( ...
                        [entries.action] == "keep_full_segment"), ...
                    'deleted_outside_segments', sum( ...
                        [entries.action] == "delete_outside_range")));
        end

        function entry = emptyEntry(sourceBin, sourceInfo, sourceGlobal)
            entry = struct( ...
                'action', "", ...
                'source_bin', string(sourceBin), ...
                'source_info', string(sourceInfo), ...
                'source_global_range', double(sourceGlobal), ...
                'source_local_range', [NaN NaN], ...
                'stored_global_range', [NaN NaN], ...
                'output_frames', 0, ...
                'temp_bin', "", ...
                'temp_info', "", ...
                'backup_bin', "", ...
                'backup_info', "");
        end

        function commit(plans, logger)
            try
                for planIndex = 1:numel(plans)
                    entries = plans(planIndex).entries;
                    for entryIndex = 1:numel(entries)
                        entry = entries(entryIndex);
                        if entry.action ~= "keep_full_segment"
                            zoulab.VisualBinCropper.moveRequired( ...
                                entry.source_bin, entry.backup_bin);
                        end
                        zoulab.VisualBinCropper.moveRequired( ...
                            entry.source_info, entry.backup_info);
                        if entry.action == "replace_partial_segment"
                            zoulab.VisualBinCropper.moveRequired( ...
                                entry.temp_bin, entry.source_bin);
                        end
                        if entry.action ~= "delete_outside_range"
                            zoulab.VisualBinCropper.moveRequired( ...
                                entry.temp_info, entry.source_info);
                        end
                    end
                end
            catch ME
                zoulab.VisualBinCropper.rollback(plans, logger);
                rethrow(ME);
            end
            for planIndex = 1:numel(plans)
                entries = plans(planIndex).entries;
                for entryIndex = 1:numel(entries)
                    zoulab.VisualBinCropper.deleteIfPresent( ...
                        entries(entryIndex).backup_bin, logger, ...
                        'VISUAL_CROP_BIN_BACKUP_DELETE_FAILED');
                    zoulab.VisualBinCropper.deleteIfPresent( ...
                        entries(entryIndex).backup_info, logger, ...
                        'VISUAL_CROP_INFO_BACKUP_DELETE_FAILED');
                end
            end
        end

        function rollback(plans, logger)
            for planIndex = numel(plans):-1:1
                if isempty(plans(planIndex)) || ...
                        ~isfield(plans(planIndex), 'entries')
                    continue;
                end
                entries = plans(planIndex).entries;
                for entryIndex = numel(entries):-1:1
                    entry = entries(entryIndex);
                    try
                        if isfile(entry.backup_info)
                            if isfile(entry.source_info)
                                delete(entry.source_info);
                            end
                            movefile(entry.backup_info, entry.source_info, 'f');
                        end
                        if isfile(entry.backup_bin)
                            if isfile(entry.source_bin)
                                delete(entry.source_bin);
                            end
                            movefile(entry.backup_bin, entry.source_bin, 'f');
                        end
                    catch ME
                        logger.logException('VISUAL_BIN_CROP_ROLLBACK_FAILED', ME);
                    end
                end
            end
        end

        function cleanupPrepared(planCells)
            for planIndex = 1:numel(planCells)
                plan = planCells{planIndex};
                if isempty(plan) || ~isfield(plan, 'entries')
                    continue;
                end
                for entry = plan.entries
                    zoulab.VisualBinCropper.deleteQuietly(entry.temp_bin);
                    zoulab.VisualBinCropper.deleteQuietly(entry.temp_info);
                end
            end
        end

        function copyFrameRange(source, target, frameSize, localRange)
            bytesPerFrame = prod(frameSize) * 2;
            input = fopen(source, 'r', 'ieee-le');
            if input < 0
                error('ZouLab:VisualCropSourceOpenFailed', ...
                    'Cannot open source BIN: %s', source);
            end
            inputCleanup = onCleanup(@() ...
                zoulab.VisualBinCropper.closeFile(input));
            output = fopen(target, 'w', 'ieee-le');
            if output < 0
                error('ZouLab:VisualCropTargetOpenFailed', ...
                    'Cannot open crop staging BIN: %s', target);
            end
            outputCleanup = onCleanup(@() ...
                zoulab.VisualBinCropper.closeFile(output));
            if fseek(input, (localRange(1) - 1) * bytesPerFrame, 'bof') ~= 0
                error('ZouLab:VisualCropSeekFailed', ...
                    'Cannot seek to frame %d in %s.', localRange(1), source);
            end
            remaining = localRange(2) - localRange(1) + 1;
            valuesPerFrame = prod(frameSize);
            while remaining > 0
                take = min(64, remaining);
                [values, readCount] = fread(input, ...
                    [valuesPerFrame take], '*uint16');
                if readCount ~= valuesPerFrame * take
                    error('ZouLab:VisualCropShortRead', ...
                        'Short read while cropping %s.', source);
                end
                written = fwrite(output, values, 'uint16');
                if written ~= readCount
                    error('ZouLab:VisualCropShortWrite', ...
                        'Short write while preparing %s.', target);
                end
                remaining = remaining - take;
            end
            fclose(output);
            outputCleanup = []; %#ok<NASGU>
            fclose(input);
            inputCleanup = []; %#ok<NASGU>
            entry = dir(target);
            expectedBytes = (localRange(2) - localRange(1) + 1) * ...
                bytesPerFrame;
            if isempty(entry) || double(entry.bytes) ~= expectedBytes
                error('ZouLab:VisualCropVerificationFailed', ...
                    'Prepared file %s failed byte-count verification.', target);
            end
        end

        function moveRequired(source, target)
            [success, message] = movefile(source, target, 'f');
            if ~success
                error('ZouLab:VisualCropMoveFailed', ...
                    'Cannot move %s to %s: %s', source, target, message);
            end
        end

        function deleteIfPresent(path, logger, eventName)
            if strlength(path) == 0 || ~isfile(path)
                return;
            end
            try
                delete(path);
            catch ME
                logger.logException(eventName, ME);
            end
        end

        function deleteQuietly(path)
            if strlength(path) > 0 && isfile(path)
                try
                    delete(path);
                catch
                end
            end
        end

        function closeFile(fid)
            try
                fclose(fid);
            catch
            end
        end
    end
end
